/** Technical metadata only: no store names, periods, amounts, or business facts. */
export const monthlyMetricDefinitions = [
  { group: "pnl", label: "Выручка", field: "revenue", unit: "amount" },
  { group: "pnl", label: "Валовая прибыль", field: "gross_profit", unit: "amount" },
  { group: "pnl", label: "Чистая прибыль", field: "net_profit", unit: "amount" },
  { group: "pnl", label: "Валовая маржа", field: "gross_margin_pct", unit: "percent" },
  { group: "pnl", label: "Чистая маржа", field: "net_margin_pct", unit: "percent" },
  { group: "product", label: "Закупка всего", field: "purchases", unit: "amount" },
  { group: "product", label: "З. Коп. — закупка копченой", field: "purchase_smoked", unit: "amount" },
  { group: "product", label: "З. Мор. — закупка мороженой", field: "purchase_frozen", unit: "amount" },
  { group: "product", label: "П. Коп. — продажа копченой", field: "sales_smoked", unit: "amount" },
  { group: "product", label: "П. Мор. — продажа мороженой", field: "sales_frozen", unit: "amount" },
  { group: "pricing", label: "Наценка Коп.", field: "smoked_markup_pct", unit: "percent" },
  { group: "pricing", label: "Наценка Мор.", field: "frozen_markup_pct", unit: "percent" },
  { group: "expense", label: "Хоз. нужды", field: "household", unit: "amount" },
  { group: "expense", label: "Доставка", field: "delivery", unit: "amount" },
  { group: "expense", label: "Уборка", field: "cleaning", unit: "amount" },
  { group: "expense", label: "Премия", field: "bonus", unit: "amount" },
  { group: "expense", label: "Выслуга", field: "service_bonus", unit: "amount" },
  { group: "expense", label: "Доплата", field: "extra_pay", unit: "amount" },
  { group: "expense", label: "Водитель (наличные)", field: "driver_cash", unit: "amount" },
  { group: "expense", label: "Коммунальные (наличные)", field: "utilities_cash", unit: "amount" },
  { group: "expense", label: "Прочие наличные расходы", field: "other_cash_expenses", unit: "amount" },
  { group: "expense", label: "Водитель (безнал)", field: "driver_cashless", unit: "amount" },
  { group: "expense", label: "Коммунальные (безнал)", field: "utilities_cashless", unit: "amount" },
  { group: "expense", label: "Аренда", field: "rent", unit: "amount" },
  { group: "expense", label: "Банковская комиссия", field: "bank_fee", unit: "amount" },
  { group: "expense", label: "Налог с валовой прибыли", field: "gross_profit_tax", unit: "amount" },
  { group: "expense", label: "Зарплата (безнал)", field: "salary_cashless", unit: "amount" },
  { group: "expense", label: "Налоги на ФОТ", field: "payroll_tax", unit: "amount" },
  { group: "expense", label: "Отпускные (безнал)", field: "vacation_cashless", unit: "amount" },
  { group: "expense", label: "Налоги на отпускные", field: "vacation_tax", unit: "amount" },
  { group: "expense", label: "Зарплата (наличные)", field: "salary_cash", unit: "amount" },
  { group: "expense", label: "Отпускные (наличные)", field: "vacation_cash", unit: "amount" },
  { group: "expense", label: "НДФЛ", field: "personal_income_tax", unit: "amount" },
  { group: "expense", label: "Списания М. — расход P&L", field: "writeoff_frozen", unit: "amount" },
  { group: "inventory", label: "Остаток на начало", field: "stock_open", unit: "amount" },
  { group: "inventory", label: "Остаток на конец", field: "stock_close", unit: "amount" },
  { group: "inventory", label: "Изменение остатка", field: "stock_change", unit: "amount" },
  { group: "inventory", label: "Перемещение", field: "movement", unit: "amount" },
  { group: "inventory", label: "Уценка", field: "discount", unit: "amount" },
  { group: "inventory", label: "Переоценка", field: "revaluation", unit: "amount" },
  { group: "inventory", label: "Списания К. — производственный сигнал", field: "writeoff_smoked", unit: "amount" },
  { group: "inventory", label: "Списания М. — расход P&L", field: "writeoff_frozen", unit: "amount" },
] as const;
