import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { adminProcedure, protectedProcedure, router } from "../_core/trpc";
import { PLAN_FACT_METRICS, backfillPaymentRevenueFromImports, commitWorkbookForDateRangeFast, deleteAuditImport, deleteFactsByDateRange, deleteMetricValue, deletePlanFact, getAuditDashboard, getAuditImportDownload, getImportMaterializationSettings, getImportThresholdBreaches, listAuditImports, listAuditStores, listPlanFacts, listStoreEntries, listStoreMetrics, mergeAuditStores, previewDateRangeDeletion, previewImportThresholdBreaches, previewWorkbook, renameAuditStore, renameMetricValue, setMetricVisibility, setStoreVisibility, updateImportMaterializationSettings, updateMetricValue, upsertPlanFact, withWorkbookCredentials } from "../audit";
import { listChangesPage, recordChange, rollbackMetricChange } from "../localAuth";
import { getAccessibleStoreIds, getCurrentLocalAccount, hasImportAccess, hasStoreAccess } from "../accessControl";
import { createStoreEventNotifications, evaluateMetricAlert } from "../notifications";
import { ensureAlertThresholds, evaluateAlertThresholds, listAlertThresholds, updateAlertThreshold } from "../alertThresholds";
import { createWeeklyExecutiveReport, deleteWeeklyExecutiveReport, getWeeklyReportSchedule, listWeeklyExecutiveReports, updateWeeklyReportSchedule } from "../weeklyReports";
import { getImportCredentialStatus, resolveImportCredentials, updateImportCredentials } from "../importCredentials";
import { buildImportPreviewSummary } from "../importPreviewSummary";

const upload=z.object({fileName:z.string().min(1).max(255),fileBase64:z.string().min(20)});
const importCredentialInput=z.object({workbookPassword:z.string().min(1).max(256).optional(),unprotectPassword:z.string().min(1).max(256).optional()});
const commitWorkbookForDateRange=(buffer:Buffer,fileName:string,resolution:"replace"|"skip"|"preserve_manual",dateRange?:{from:string;to:string},credentials?:{workbookPassword?:string;unprotectPassword?:string})=>withWorkbookCredentials(credentials??{},()=>commitWorkbookForDateRangeFast(buffer,fileName,resolution,dateRange));
const entryDate=z.string().regex(/^20\d{2}-\d{2}-\d{2}$/,"Выберите дату в формате ГГГГ-ММ-ДД");
const dateRange=z.object({from:entryDate,to:entryDate}).refine(value=>value.from<=value.to,{message:"Дата начала не может быть позже даты окончания"});
const planMonth=z.string().regex(/^20\d{2}-(0[1-9]|1[0-2])$/,"Выберите месяц в формате ГГГГ‑ММ");
const planMetric=z.enum(PLAN_FACT_METRICS);
async function requireStorePermission(openId:string|undefined,storeId:number,required:"view"|"edit"){if(!await hasStoreAccess(openId,storeId,required))throw new TRPCError({code:"FORBIDDEN",message:"Нет назначенного доступа к этому магазину"})}
async function requireImportPermission(openId:string|undefined,required:"upload"|"edit"){if(!await hasImportAccess(openId,required))throw new TRPCError({code:"FORBIDDEN",message:required==="edit"?"Нет права изменять или удалять импортированные данные":"Нет права загружать книги Excel"})}
const metricLabels:Record<string,string>={revenue:"Выручка",gross_profit:"Валовая прибыль",net_profit:"Чистая прибыль",purchases:"Закупки",purchase_smoked:"Закупка Коп.",purchase_frozen:"Закупка Мор.",sales_smoked:"Продажи Коп.",sales_frozen:"Продажи Мор.",writeoff_smoked:"Списания К.",writeoff_frozen:"Списания М.",stock_open:"Остаток на начало",stock_close:"Остаток на конец",rent:"Аренда б/нал",bank_fee:"-% банк",household:"Хоз. нужды нал",delivery:"Доставка нал",cleaning:"Уборка нал",bonus:"Премия нал",seniority:"Выслуга нал",supplement:"Доплата нал",driver_cash:"Водитель нал",utilities_cash:"Коммунальные нал",operating_costs:"Расходы нал",cash_operating_costs:"Общие траты нал",personal_income_tax_22:"НДФЛ 22%"};
async function storeContext(storeId:number){const store=(await listAuditStores()).find(item=>item.id===storeId);return {storeId,storeName:store?.name??`Магазин #${storeId}`}}

export const auditRouter=router({
  stores:protectedProcedure.query(async({ctx})=>listAuditStores(await getAccessibleStoreIds(ctx.user.openId))),
  dashboard:protectedProcedure.input(z.object({ranges:z.array(dateRange).min(1).max(2)})).query(async({ctx,input})=>getAuditDashboard(await getAccessibleStoreIds(ctx.user.openId),input.ranges)),
  planFacts:protectedProcedure.input(z.object({range:dateRange})).query(async({ctx,input})=>listPlanFacts(await getAccessibleStoreIds(ctx.user.openId),input.range)),
  upsertPlanFact:adminProcedure.input(z.object({storeId:z.number().int(),monthDate:planMonth,metricCode:planMetric,amount:z.number().finite()})).mutation(async({ctx,input})=>{const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const context={...await storeContext(input.storeId),monthDate:input.monthDate,metricCode:input.metricCode,metricName:metricLabels[input.metricCode]??input.metricCode};const result=await upsertPlanFact(input.storeId,input.monthDate,input.metricCode,input.amount);await recordChange({actorId:actor.id,action:result.created?"plan.create":"plan.update",entityType:"plan_fact",entityId:`${input.storeId}:${input.monthDate}:${input.metricCode}`,beforeState:result.previousAmount===null?null:{...context,amount:result.previousAmount},afterState:{...context,amount:input.amount}});return result}),
  deletePlanFact:adminProcedure.input(z.object({storeId:z.number().int(),monthDate:planMonth,metricCode:planMetric})).mutation(async({ctx,input})=>{const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const context={...await storeContext(input.storeId),monthDate:input.monthDate,metricCode:input.metricCode,metricName:metricLabels[input.metricCode]??input.metricCode};const result=await deletePlanFact(input.storeId,input.monthDate,input.metricCode);await recordChange({actorId:actor.id,action:"plan.delete",entityType:"plan_fact",entityId:`${input.storeId}:${input.monthDate}:${input.metricCode}`,beforeState:{...context,amount:result.amount},afterState:{...context,deleted:true}});return result}),
  alertThresholds:adminProcedure.query(()=>ensureAlertThresholds()),
  updateAlertThreshold:adminProcedure.input(z.object({ruleKey:z.string().min(1).max(64),threshold:z.number().finite().min(0),isEnabled:z.boolean()})).mutation(async({input,ctx})=>{const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const before=(await listAlertThresholds()).find(rule=>rule.ruleKey===input.ruleKey)??null;const after=await updateAlertThreshold(input);await recordChange({actorId:actor.id,action:"alert_threshold.update",entityType:"alert_threshold",entityId:input.ruleKey,beforeState:before,afterState:after});return after}),
  imports:protectedProcedure.query(async({ctx})=>{await requireImportPermission(ctx.user.openId,"upload");return listAuditImports()}),
  downloadImport:protectedProcedure.input(z.object({importId:z.number().int()})).mutation(async({input,ctx})=>{await requireImportPermission(ctx.user.openId,"edit");return getAuditImportDownload(input.importId)}),
  importMaterializationSettings:protectedProcedure.query(async({ctx})=>{await requireImportPermission(ctx.user.openId,"upload");return getImportMaterializationSettings()}),
  updateImportMaterializationSettings:adminProcedure.input(z.object({metricCodes:z.array(z.string().min(1).max(64)).max(32)})).mutation(async({input,ctx})=>{const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const before=await getImportMaterializationSettings();const after=await updateImportMaterializationSettings(input.metricCodes);await recordChange({actorId:actor.id,action:"import.materialization.update",entityType:"import_materialization",entityId:"default",beforeState:{metricCodes:before.metricCodes},afterState:{metricCodes:after.metricCodes}});return after}),
  backfillPaymentRevenue:adminProcedure.mutation(async({ctx})=>{await requireImportPermission(ctx.user.openId,"edit");const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const result=await backfillPaymentRevenueFromImports(await resolveImportCredentials());await recordChange({actorId:actor.id,action:"import.payment_revenue_backfill",entityType:"import",entityId:"payment_revenue",afterState:result});return result;}),
  importCredentialStatus:adminProcedure.query(()=>getImportCredentialStatus()),
  updateImportCredentials:adminProcedure.input(importCredentialInput).mutation(async({input,ctx})=>{const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const status=await updateImportCredentials(input);await recordChange({actorId:actor.id,action:"import.credentials.update",entityType:"import_credentials",entityId:"default",afterState:{workbookPasswordConfigured:status.workbookPasswordConfigured,unprotectPasswordConfigured:status.unprotectPasswordConfigured}});return status}),
  previewImport:protectedProcedure.input(upload).mutation(async({input,ctx})=>{await requireImportPermission(ctx.user.openId,"upload");const preview=await previewWorkbook(Buffer.from(input.fileBase64,"base64"),input.fileName,await resolveImportCredentials());const thresholdBreaches=await previewImportThresholdBreaches(preview.periods);return buildImportPreviewSummary(preview,thresholdBreaches)}),
  commitImport:protectedProcedure.input(upload.extend({resolution:z.enum(["replace","skip","preserve_manual"]),dateRange:dateRange.optional()})).mutation(async({input,ctx})=>{await requireImportPermission(ctx.user.openId,input.resolution==="skip"?"upload":"edit");const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const result=await commitWorkbookForDateRange(Buffer.from(input.fileBase64,"base64"),input.fileName,input.resolution,input.dateRange,await resolveImportCredentials());const thresholdBreaches=await getImportThresholdBreaches(result.importId);await recordChange({actorId:actor.id,action:"import.commit",entityType:"import",entityId:String(result.importId),afterState:{fileName:input.fileName,resolution:input.resolution,dateRange:input.dateRange??"все распознанные даты",thresholdBreaches:thresholdBreaches.length,...result}});if(result.conflicts.length&&input.resolution!=="skip")await createStoreEventNotifications({severity:"warning",title:input.resolution==="preserve_manual"?"Импорт обновил данные, сохранив ручные правки":"Импорт заменил существующие даты",message:input.resolution==="preserve_manual"?`Файл «${input.fileName}» обновил совпадающие даты и сохранил ${result.protectedMetricCount} ручных показателей.`:`Файл «${input.fileName}» заменил ${result.conflicts.length} совпадающих записей. Проверьте журнал изменений.`,entityType:"import",entityId:String(result.importId)});for(const breach of thresholdBreaches)await createStoreEventNotifications({storeIds:[breach.storeId],severity:breach.rule.severity,title:`Порог: ${breach.rule.label}`,message:`${breach.store}, ${breach.entryDate}: ${breach.rule.description} — ${breach.amount.toLocaleString("ru-RU")} ₽ при пороге ${breach.rule.threshold.toLocaleString("ru-RU")} ₽.`,entityType:"threshold",entityId:`${breach.storeId}:${breach.entryDate}:${breach.rule.ruleKey}`});for(const event of result.riskEvents)await createStoreEventNotifications({storeIds:[event.storeId],severity:"critical",title:event.type==="negative_profit"?"Отрицательная чистая прибыль после импорта":"Повышенные списания мороженой продукции",message:`${event.store}, ${event.monthDate}: ${event.type==="negative_profit"?`чистая прибыль ${event.amount.toLocaleString("ru-RU")} ₽`:`списания мороженой продукции ${event.amount.toLocaleString("ru-RU")} ₽`}.`,entityType:"store",entityId:String(event.storeId)});return {...result,thresholdBreaches:thresholdBreaches.length}}),
  previewRangeDelete:protectedProcedure.input(z.object({range:dateRange,storeId:z.number().int().optional()})).query(async({input,ctx})=>{await requireImportPermission(ctx.user.openId,"edit");return previewDateRangeDeletion(input.range,input.storeId)}),
  deleteRange:protectedProcedure.input(z.object({range:dateRange,storeId:z.number().int().optional()})).mutation(async({input,ctx})=>{await requireImportPermission(ctx.user.openId,"edit");const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const result=await deleteFactsByDateRange(input.range,input.storeId);const scope=input.storeId?await storeContext(input.storeId):{scope:"Все магазины"};await recordChange({actorId:actor.id,action:"facts.range_delete",entityType:"period",entityId:`${input.storeId??"all"}:${input.range.from}:${input.range.to}`,beforeState:{scope,range:input.range,periods:result.periods,metrics:result.metrics,stores:result.stores},afterState:{range:input.range,deleted:true,periods:result.periods,metrics:result.metrics,stores:result.stores}});return result}),
  deleteImport:protectedProcedure.input(z.object({importId:z.number().int()})).mutation(async({input,ctx})=>{await requireImportPermission(ctx.user.openId,"edit");const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const previous=(await listAuditImports()).find(item=>item.id===input.importId);const result=await deleteAuditImport(input.importId);await recordChange({actorId:actor.id,action:"import.delete",entityType:"import",entityId:String(input.importId),beforeState:previous?{...previous}:null,afterState:{...result,deleted:true}});return result}),
  mergeStores:adminProcedure.input(z.object({sourceStoreId:z.number().int(),targetStoreId:z.number().int(),resolution:z.enum(["replace","skip"])})).mutation(async({input,ctx})=>{const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const result=await mergeAuditStores(input.sourceStoreId,input.targetStoreId,input.resolution);await recordChange({actorId:actor.id,action:"store.merge",entityType:"store",entityId:String(input.sourceStoreId),afterState:{...input,...result}});return result}),
  setVisibility:adminProcedure.input(z.object({id:z.number().int(),isHidden:z.boolean()})).mutation(async({input,ctx})=>{const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const before=(await listAuditStores()).find(store=>store.id===input.id);const context={storeId:input.id,storeName:before?.name??`Магазин #${input.id}`};const result=await setStoreVisibility(input.id,input.isHidden);await recordChange({actorId:actor.id,action:"store.visibility",entityType:"store",entityId:String(input.id),beforeState:before?{...context,visibility:before.isHidden?"скрыт из аналитики":"виден в аналитике",isHidden:before.isHidden}:null,afterState:{...context,visibility:input.isHidden?"скрыт из аналитики":"виден в аналитике",isHidden:input.isHidden}});return result}),
  renameStore:adminProcedure.input(z.object({id:z.number().int(),name:z.string().trim().min(1).max(128)})).mutation(async({input,ctx})=>{const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const result=await renameAuditStore(input.id,input.name);await recordChange({actorId:actor.id,action:"store.rename",entityType:"store",entityId:String(input.id),beforeState:{storeId:input.id,storeName:result.previousName},afterState:{storeId:input.id,storeName:result.name,unchanged:result.unchanged}});return result}),
  storeEntries:protectedProcedure.input(z.object({storeId:z.number().int()})).query(async({input,ctx})=>{await requireStorePermission(ctx.user.openId,input.storeId,"view");return listStoreEntries(input.storeId)}),
  metrics:protectedProcedure.input(z.object({storeId:z.number().int(),entryDate})).query(async({input,ctx})=>{await requireStorePermission(ctx.user.openId,input.storeId,"view");return listStoreMetrics(input.storeId,input.entryDate)}),
  updateMetric:protectedProcedure.input(z.object({storeId:z.number().int(),entryDate,metricCode:z.string().min(1).max(64),amount:z.number()})).mutation(async({input,ctx})=>{await requireStorePermission(ctx.user.openId,input.storeId,"edit");const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const previous=(await listStoreMetrics(input.storeId,input.entryDate)).find(metric=>metric.metricCode===input.metricCode);const context={...await storeContext(input.storeId),entryDate:input.entryDate,metricCode:input.metricCode,metricName:metricLabels[input.metricCode]??input.metricCode};const before={...context,amount:Number(previous?.amount??0),isHidden:Boolean(previous?.isHidden)};const result=await updateMetricValue(input.storeId,input.entryDate,input.metricCode,input.amount);const after={...context,amount:input.amount,isHidden:Boolean(previous?.isHidden)};await recordChange({actorId:actor.id,action:"metric.update",entityType:"metric",entityId:`${input.storeId}:${input.entryDate}:${input.metricCode}`,beforeState:before,afterState:after});const thresholdHits=evaluateAlertThresholds(input.metricCode,input.amount,await ensureAlertThresholds());for(const threshold of thresholdHits)await createStoreEventNotifications({storeIds:[input.storeId],severity:threshold.severity,title:`Порог: ${threshold.label}`,message:`${context.storeName}, ${input.entryDate}: ${threshold.description} — ${input.amount.toLocaleString("ru-RU")} ₽ при пороге ${threshold.threshold.toLocaleString("ru-RU")} ₽.`,entityType:"threshold",entityId:`${input.storeId}:${input.entryDate}:${threshold.ruleKey}`});const alert=evaluateMetricAlert(input.metricCode,before.amount,input.amount);if(alert&&!thresholdHits.length)await createStoreEventNotifications({storeIds:[input.storeId],severity:alert.severity,title:"Критичное изменение показателя",message:`${input.entryDate}: «${input.metricCode}» изменен с ${before.amount.toLocaleString("ru-RU")} ₽ до ${input.amount.toLocaleString("ru-RU")} ₽. Причина: ${alert.reason}.`,entityType:"metric",entityId:`${input.storeId}:${input.entryDate}:${input.metricCode}`});return result}),
  renameMetric:protectedProcedure.input(z.object({storeId:z.number().int(),entryDate,metricCode:z.string().min(1).max(64),nextMetricCode:z.string().trim().min(1).max(64)})).mutation(async({input,ctx})=>{await requireStorePermission(ctx.user.openId,input.storeId,"edit");const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const previous=(await listStoreMetrics(input.storeId,input.entryDate)).find(metric=>metric.metricCode===input.metricCode);if(!previous)throw new TRPCError({code:"NOT_FOUND",message:"Показатель не найден"});const context={...await storeContext(input.storeId),entryDate:input.entryDate};const result=await renameMetricValue(input.storeId,input.entryDate,input.metricCode,input.nextMetricCode);await recordChange({actorId:actor.id,action:"metric.rename",entityType:"metric",entityId:`${input.storeId}:${input.entryDate}:${input.nextMetricCode}`,beforeState:{...context,metricCode:input.metricCode,metricName:metricLabels[input.metricCode]??input.metricCode,amount:Number(previous.amount),isHidden:previous.isHidden},afterState:{...context,metricCode:input.nextMetricCode,metricName:metricLabels[input.nextMetricCode]??input.nextMetricCode,amount:Number(previous.amount),isHidden:previous.isHidden,unchanged:result.unchanged}});return result}),
  deleteMetric:protectedProcedure.input(z.object({storeId:z.number().int(),entryDate,metricCode:z.string().min(1).max(64)})).mutation(async({input,ctx})=>{await requireStorePermission(ctx.user.openId,input.storeId,"edit");const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const previous=(await listStoreMetrics(input.storeId,input.entryDate)).find(metric=>metric.metricCode===input.metricCode);if(!previous)throw new TRPCError({code:"NOT_FOUND",message:"Показатель не найден"});const context={...await storeContext(input.storeId),entryDate:input.entryDate,metricCode:input.metricCode,metricName:metricLabels[input.metricCode]??input.metricCode};const result=await deleteMetricValue(input.storeId,input.entryDate,input.metricCode);await recordChange({actorId:actor.id,action:"metric.delete",entityType:"metric",entityId:`${input.storeId}:${input.entryDate}:${input.metricCode}`,beforeState:{...context,amount:Number(previous.amount),isHidden:previous.isHidden},afterState:{...context,deleted:true}});return result}),
  setMetricVisibility:protectedProcedure.input(z.object({storeId:z.number().int(),entryDate,metricCode:z.string().min(1).max(64),isHidden:z.boolean()})).mutation(async({input,ctx})=>{await requireStorePermission(ctx.user.openId,input.storeId,"edit");const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const previous=(await listStoreMetrics(input.storeId,input.entryDate)).find(metric=>metric.metricCode===input.metricCode);if(!previous)throw new TRPCError({code:"NOT_FOUND",message:"Показатель не найден"});const context={...await storeContext(input.storeId),entryDate:input.entryDate,metricCode:input.metricCode,metricName:metricLabels[input.metricCode]??input.metricCode,amount:Number(previous.amount)};const result=await setMetricVisibility(input.storeId,input.entryDate,input.metricCode,input.isHidden);await recordChange({actorId:actor.id,action:"metric.visibility",entityType:"metric",entityId:`${input.storeId}:${input.entryDate}:${input.metricCode}`,beforeState:{...context,visibility:previous.isHidden?"скрыт из аналитики":"виден в аналитике",isHidden:previous.isHidden},afterState:{...context,visibility:input.isHidden?"скрыт из аналитики":"виден в аналитике",isHidden:input.isHidden}});return result}),
  changes:adminProcedure.input(z.object({limit:z.number().int().min(1).max(50).optional(),offset:z.number().int().min(0).optional()}).optional()).query(({input})=>listChangesPage(input)),
  rollbackChange:adminProcedure.input(z.object({changeId:z.number().int()})).mutation(async({input,ctx})=>{const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});return rollbackMetricChange(input.changeId,actor.id)}),
  weeklyReports:adminProcedure.input(z.object({limit:z.number().int().min(1).max(24).optional(),offset:z.number().int().min(0).optional()}).optional()).query(({input})=>listWeeklyExecutiveReports(input)),
  deleteWeeklyReport:adminProcedure.input(z.object({reportId:z.number().int().positive()})).mutation(async({input,ctx})=>{const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const deleted=await deleteWeeklyExecutiveReport(input.reportId);await recordChange({actorId:actor.id,action:"weekly_report.delete",entityType:"weekly_report",entityId:String(deleted.id),beforeState:{periodStart:deleted.periodStart,periodEnd:deleted.periodEnd,snapshotMonth:deleted.snapshotMonth},afterState:{deleted:true}});return {id:deleted.id,periodStart:deleted.periodStart,periodEnd:deleted.periodEnd};}),
  generateWeeklyReport:adminProcedure.input(z.object({range:dateRange.optional()}).optional()).mutation(async({input})=>{if(input?.range)return createWeeklyExecutiveReport("custom",{periodStart:input.range.from,periodEnd:input.range.to});const schedule=await getWeeklyReportSchedule();return createWeeklyExecutiveReport(schedule.reportPeriod as "week"|"month")}),
  weeklyReportSchedule:adminProcedure.query(()=>getWeeklyReportSchedule()),
  updateWeeklyReportSchedule:adminProcedure.input(z.object({weekday:z.number().int().min(1).max(7),reportTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),reportPeriod:z.enum(["week","month"]),isEnabled:z.boolean()})).mutation(async({input,ctx})=>{const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const before=await getWeeklyReportSchedule();const after=await updateWeeklyReportSchedule(input);await recordChange({actorId:actor.id,action:"weekly_report.schedule.update",entityType:"weekly_report_schedule",entityId:String(after.id),beforeState:{weekday:before.weekday,reportTime:before.reportTime,reportPeriod:before.reportPeriod,isEnabled:before.isEnabled},afterState:{weekday:after.weekday,reportTime:after.reportTime,reportPeriod:after.reportPeriod,isEnabled:after.isEnabled}});return after}),
});
