import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { adminProcedure, protectedProcedure, router } from "../_core/trpc";
import { commitWorkbook, getAuditDashboard, listAuditStores, listStoreMetrics, previewWorkbook, setStoreVisibility, updateMetricValue } from "../audit";
import { listChanges, recordChange, rollbackMetricChange } from "../localAuth";
import { getAccessibleStoreIds, getCurrentLocalAccount, hasStoreAccess } from "../accessControl";
import { createStoreEventNotifications, evaluateMetricAlert } from "../notifications";
const upload=z.object({fileName:z.string().min(1).max(255),fileBase64:z.string().min(20)});
async function requireStorePermission(openId:string|undefined,storeId:number,required:"view"|"edit"){if(!await hasStoreAccess(openId,storeId,required))throw new TRPCError({code:"FORBIDDEN",message:"Нет назначенного доступа к этому магазину"})}
export const auditRouter=router({
  stores:protectedProcedure.query(async({ctx})=>listAuditStores(await getAccessibleStoreIds(ctx.user.openId))),
  dashboard:protectedProcedure.query(async({ctx})=>getAuditDashboard(await getAccessibleStoreIds(ctx.user.openId))),
  previewImport:adminProcedure.input(upload).mutation(async({input})=>previewWorkbook(Buffer.from(input.fileBase64,"base64"),input.fileName)),
  commitImport:adminProcedure.input(upload.extend({resolution:z.enum(["replace","skip"])})).mutation(async({input,ctx})=>{const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const result=await commitWorkbook(Buffer.from(input.fileBase64,"base64"),input.fileName,input.resolution);await recordChange({actorId:actor.id,action:"import.commit",entityType:"import",entityId:input.fileName,afterState:{resolution:input.resolution,...result}});if(result.conflicts.length&&input.resolution==="replace")await createStoreEventNotifications({severity:"warning",title:"Импорт заменил существующие месяцы",message:`Файл «${input.fileName}» заменил ${result.conflicts.length} совпадающих периодов. Проверьте журнал изменений.`,entityType:"import",entityId:input.fileName});for(const event of result.riskEvents)await createStoreEventNotifications({storeIds:[event.storeId],severity:"critical",title:event.type==="negative_profit"?"Отрицательная чистая прибыль после импорта":"Повышенные списания мороженой продукции",message:`${event.store}, ${event.monthDate}: ${event.type==="negative_profit"?"чистая прибыль "+event.amount.toLocaleString("ru-RU")+" ₽":"списания мороженой продукции "+event.amount.toLocaleString("ru-RU")+" ₽"}.`,entityType:"store",entityId:String(event.storeId)});return result}),
  setVisibility:adminProcedure.input(z.object({id:z.number().int(),isHidden:z.boolean()})).mutation(async({input,ctx})=>{const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const before=(await listAuditStores()).find(store=>store.id===input.id);const result=await setStoreVisibility(input.id,input.isHidden);await recordChange({actorId:actor.id,action:"store.visibility",entityType:"store",entityId:String(input.id),beforeState:before?{isHidden:before.isHidden}:null,afterState:{isHidden:input.isHidden}});return result}),
  metrics:protectedProcedure.input(z.object({storeId:z.number().int(),monthDate:z.string().regex(/^20\d{2}-\d{2}$/)})).query(async({input,ctx})=>{await requireStorePermission(ctx.user.openId,input.storeId,"view");return listStoreMetrics(input.storeId,input.monthDate)}),
  updateMetric:protectedProcedure.input(z.object({storeId:z.number().int(),monthDate:z.string().regex(/^20\d{2}-\d{2}$/),metricCode:z.string().min(1),amount:z.number()})).mutation(async({input,ctx})=>{await requireStorePermission(ctx.user.openId,input.storeId,"edit");const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const previous=(await listStoreMetrics(input.storeId,input.monthDate)).find(metric=>metric.metricCode===input.metricCode);const before={...input,amount:Number(previous?.amount??0)};const result=await updateMetricValue(input.storeId,input.monthDate,input.metricCode,input.amount);await recordChange({actorId:actor.id,action:"metric.update",entityType:"metric",entityId:`${input.storeId}:${input.monthDate}:${input.metricCode}`,beforeState:before,afterState:input});const alert=evaluateMetricAlert(input.metricCode,before.amount,input.amount);if(alert)await createStoreEventNotifications({storeIds:[input.storeId],severity:alert.severity,title:"Критичное изменение показателя",message:`${input.monthDate}: «${input.metricCode}» изменен с ${before.amount.toLocaleString("ru-RU")} ₽ до ${input.amount.toLocaleString("ru-RU")} ₽. Причина: ${alert.reason}.`,entityType:"metric",entityId:`${input.storeId}:${input.monthDate}:${input.metricCode}`});return result}),
  changes:adminProcedure.query(()=>listChanges()),
  rollbackChange:adminProcedure.input(z.object({changeId:z.number().int()})).mutation(async({input,ctx})=>{const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});return rollbackMetricChange(input.changeId,actor.id)}),
});
