import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { adminProcedure, protectedProcedure, router } from "../_core/trpc";
import { commitWorkbook, deleteAuditImport, deleteMetricValue, getAuditDashboard, listAuditImports, listAuditStores, listStoreEntries, listStoreMetrics, mergeAuditStores, previewWorkbook, setMetricVisibility, setStoreVisibility, updateMetricValue } from "../audit";
import { listChanges, recordChange, rollbackMetricChange } from "../localAuth";
import { getAccessibleStoreIds, getCurrentLocalAccount, hasStoreAccess } from "../accessControl";
import { createStoreEventNotifications, evaluateMetricAlert } from "../notifications";
import { createWeeklyExecutiveReport, listWeeklyExecutiveReports } from "../weeklyReports";

const upload=z.object({fileName:z.string().min(1).max(255),fileBase64:z.string().min(20)});
const entryDate=z.string().regex(/^20\d{2}-\d{2}-\d{2}$/,"Выберите дату в формате ГГГГ-ММ-ДД");
async function requireStorePermission(openId:string|undefined,storeId:number,required:"view"|"edit"){if(!await hasStoreAccess(openId,storeId,required))throw new TRPCError({code:"FORBIDDEN",message:"Нет назначенного доступа к этому магазину"})}

export const auditRouter=router({
  stores:protectedProcedure.query(async({ctx})=>listAuditStores(await getAccessibleStoreIds(ctx.user.openId))),
  dashboard:protectedProcedure.query(async({ctx})=>getAuditDashboard(await getAccessibleStoreIds(ctx.user.openId))),
  imports:adminProcedure.query(()=>listAuditImports()),
  previewImport:adminProcedure.input(upload).mutation(async({input})=>previewWorkbook(Buffer.from(input.fileBase64,"base64"),input.fileName)),
  commitImport:adminProcedure.input(upload.extend({resolution:z.enum(["replace","skip"])})).mutation(async({input,ctx})=>{const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const result=await commitWorkbook(Buffer.from(input.fileBase64,"base64"),input.fileName,input.resolution);await recordChange({actorId:actor.id,action:"import.commit",entityType:"import",entityId:String(result.importId),afterState:{fileName:input.fileName,resolution:input.resolution,...result}});if(result.conflicts.length&&input.resolution==="replace")await createStoreEventNotifications({severity:"warning",title:"Импорт заменил существующие даты",message:`Файл «${input.fileName}» заменил ${result.conflicts.length} совпадающих записей. Проверьте журнал изменений.`,entityType:"import",entityId:String(result.importId)});for(const event of result.riskEvents)await createStoreEventNotifications({storeIds:[event.storeId],severity:"critical",title:event.type==="negative_profit"?"Отрицательная чистая прибыль после импорта":"Повышенные списания мороженой продукции",message:`${event.store}, ${event.monthDate}: ${event.type==="negative_profit"?`чистая прибыль ${event.amount.toLocaleString("ru-RU")} ₽`:`списания мороженой продукции ${event.amount.toLocaleString("ru-RU")} ₽`}.`,entityType:"store",entityId:String(event.storeId)});return result}),
  deleteImport:adminProcedure.input(z.object({importId:z.number().int()})).mutation(async({input,ctx})=>{const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const result=await deleteAuditImport(input.importId);await recordChange({actorId:actor.id,action:"import.delete",entityType:"import",entityId:String(input.importId),afterState:result});return result}),
  mergeStores:adminProcedure.input(z.object({sourceStoreId:z.number().int(),targetStoreId:z.number().int(),resolution:z.enum(["replace","skip"])})).mutation(async({input,ctx})=>{const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const result=await mergeAuditStores(input.sourceStoreId,input.targetStoreId,input.resolution);await recordChange({actorId:actor.id,action:"store.merge",entityType:"store",entityId:String(input.sourceStoreId),afterState:{...input,...result}});return result}),
  setVisibility:adminProcedure.input(z.object({id:z.number().int(),isHidden:z.boolean()})).mutation(async({input,ctx})=>{const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const before=(await listAuditStores()).find(store=>store.id===input.id);const result=await setStoreVisibility(input.id,input.isHidden);await recordChange({actorId:actor.id,action:"store.visibility",entityType:"store",entityId:String(input.id),beforeState:before?{isHidden:before.isHidden}:null,afterState:{isHidden:input.isHidden}});return result}),
  storeEntries:protectedProcedure.input(z.object({storeId:z.number().int()})).query(async({input,ctx})=>{await requireStorePermission(ctx.user.openId,input.storeId,"view");return listStoreEntries(input.storeId)}),
  metrics:protectedProcedure.input(z.object({storeId:z.number().int(),entryDate})).query(async({input,ctx})=>{await requireStorePermission(ctx.user.openId,input.storeId,"view");return listStoreMetrics(input.storeId,input.entryDate)}),
  updateMetric:protectedProcedure.input(z.object({storeId:z.number().int(),entryDate,metricCode:z.string().min(1).max(64),amount:z.number()})).mutation(async({input,ctx})=>{await requireStorePermission(ctx.user.openId,input.storeId,"edit");const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const previous=(await listStoreMetrics(input.storeId,input.entryDate)).find(metric=>metric.metricCode===input.metricCode);const before={...input,amount:Number(previous?.amount??0)};const result=await updateMetricValue(input.storeId,input.entryDate,input.metricCode,input.amount);await recordChange({actorId:actor.id,action:"metric.update",entityType:"metric",entityId:`${input.storeId}:${input.entryDate}:${input.metricCode}`,beforeState:before,afterState:input});const alert=evaluateMetricAlert(input.metricCode,before.amount,input.amount);if(alert)await createStoreEventNotifications({storeIds:[input.storeId],severity:alert.severity,title:"Критичное изменение показателя",message:`${input.entryDate}: «${input.metricCode}» изменен с ${before.amount.toLocaleString("ru-RU")} ₽ до ${input.amount.toLocaleString("ru-RU")} ₽. Причина: ${alert.reason}.`,entityType:"metric",entityId:`${input.storeId}:${input.entryDate}:${input.metricCode}`});return result}),
  deleteMetric:protectedProcedure.input(z.object({storeId:z.number().int(),entryDate,metricCode:z.string().min(1).max(64)})).mutation(async({input,ctx})=>{await requireStorePermission(ctx.user.openId,input.storeId,"edit");const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const previous=(await listStoreMetrics(input.storeId,input.entryDate)).find(metric=>metric.metricCode===input.metricCode);if(!previous)throw new TRPCError({code:"NOT_FOUND",message:"Показатель не найден"});const result=await deleteMetricValue(input.storeId,input.entryDate,input.metricCode);await recordChange({actorId:actor.id,action:"metric.delete",entityType:"metric",entityId:`${input.storeId}:${input.entryDate}:${input.metricCode}`,beforeState:{...input,amount:Number(previous.amount)},afterState:null});return result}),
  setMetricVisibility:protectedProcedure.input(z.object({storeId:z.number().int(),entryDate,metricCode:z.string().min(1).max(64),isHidden:z.boolean()})).mutation(async({input,ctx})=>{await requireStorePermission(ctx.user.openId,input.storeId,"edit");const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});const previous=(await listStoreMetrics(input.storeId,input.entryDate)).find(metric=>metric.metricCode===input.metricCode);if(!previous)throw new TRPCError({code:"NOT_FOUND",message:"Показатель не найден"});const result=await setMetricVisibility(input.storeId,input.entryDate,input.metricCode,input.isHidden);await recordChange({actorId:actor.id,action:"metric.visibility",entityType:"metric",entityId:`${input.storeId}:${input.entryDate}:${input.metricCode}`,beforeState:{isHidden:previous.isHidden},afterState:{isHidden:input.isHidden}});return result}),
  changes:adminProcedure.query(()=>listChanges()),
  rollbackChange:adminProcedure.input(z.object({changeId:z.number().int()})).mutation(async({input,ctx})=>{const actor=await getCurrentLocalAccount(ctx.user.openId);if(!actor)throw new TRPCError({code:"UNAUTHORIZED"});return rollbackMetricChange(input.changeId,actor.id)}),
  weeklyReports:adminProcedure.query(()=>listWeeklyExecutiveReports()),
  generateWeeklyReport:adminProcedure.mutation(()=>createWeeklyExecutiveReport()),
});
