import { useMemo } from "react";
import { trpc } from "@/lib/trpc";
import { useAudit, type DateRangeValue } from "@/contexts/AuditContext";
export type ImportedPeriod={storeId:number;store:string;isHidden:boolean;importId:number|null;monthDate:string;entryDate:string;metrics:Record<string,number>;allocationRatio?:number};
const monthLabels=["Янв","Фев","Мар","Апр","Май","Июн","Июл","Авг","Сен","Окт","Ноя","Дек"];
export const monthLabel=(monthDate:string)=>monthLabels[Math.max(0,Math.min(11,Number(monthDate.slice(5,7))-1))]??monthDate;
export const enrich=(period:ImportedPeriod):Record<string,number|string>=>{const revenue=Number(period.metrics.revenue??0),gross=Number(period.metrics.gross_profit??0),net=Number(period.metrics.net_profit??0),purchaseSmoked=Number(period.metrics.purchase_smoked??0),purchaseFrozen=Number(period.metrics.purchase_frozen??0),salesSmoked=Number(period.metrics.sales_smoked??0),salesFrozen=Number(period.metrics.sales_frozen??0);return {...period.metrics,purchase_total:purchaseSmoked+purchaseFrozen,sales_total:salesSmoked+salesFrozen,gross_margin_pct:revenue?gross/revenue*100:0,net_margin_pct:revenue?net/revenue*100:0,smoked_markup_pct:purchaseSmoked?(salesSmoked/purchaseSmoked-1)*100:0,frozen_markup_pct:purchaseFrozen?(salesFrozen/purchaseFrozen-1)*100:0,month:monthLabel(period.monthDate)}};
/** Названия сохраняют привычный выбор точки; значения при этом полностью синтетические и не читают финансовые факты. */
export const demoStoreNames=["ПОРТ","КНИП","Л76","К49","К80","ПЗ1","ПЗ2","МИРА","МАК","ГС1","ГС2","Н95","РОС","С1","С3","ПОЛ","СНЕЖ","ЗАО","ЗАП","НИК","ОЛЕ","МОН","А1","А2","А3","КИР1","КИР2","КИР3","КА2","П.ЗОР","КОВ","УМБА","КОЛА","ЛЕМОН"];
const monthKeys=(ranges:DateRangeValue[])=>Array.from(new Set(ranges.flatMap(range=>{const keys:string[]=[];for(let cursor=new Date(`${range.from.slice(0,7)}-01T12:00:00`),end=new Date(`${range.to.slice(0,7)}-01T12:00:00`);cursor<=end;cursor.setMonth(cursor.getMonth()+1))keys.push(`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,"0")}`);return keys;}))).sort();
const seededUnit=(seed:number,index:number)=>{const value=Math.sin(seed*0.000001+index*12.9898)*43758.5453;return value-Math.floor(value);};
const demoWave=(seed:number,storeIndex:number,monthIndex:number)=>(seededUnit(seed,storeIndex*31+monthIndex)*.16-.08)+Math.cos((monthIndex+1)*.43)*.05;
/** Детеминированный демонстрационный набор: не читает и не записывает финансовые факты пользователя. */
export const buildDemoPeriods=(ranges:DateRangeValue[],seed=20260915):ImportedPeriod[]=>monthKeys(ranges).flatMap((month,monthIndex)=>demoStoreNames.map((store,storeIndex)=>{const random=seededUnit(seed,storeIndex*101+monthIndex*7),wave=demoWave(seed,storeIndex,monthIndex),revenue=Math.round((610_000+storeIndex*71_000+monthIndex*16_000)*(1+wave)),purchaseSmoked=Math.round(revenue*(.255+storeIndex*.004+random*.015)),purchaseFrozen=Math.round(revenue*(.238+(monthIndex%3)*.006+random*.012)),purchases=purchaseSmoked+purchaseFrozen,salesSmoked=Math.round(revenue*(.51+random*.06)),salesFrozen=revenue-salesSmoked,grossProfit=revenue-purchases,expenses=Math.round(revenue*(.17+((storeIndex+monthIndex)%4)*.008+random*.015)),netProfit=grossProfit-expenses,cashRevenue=Math.round(revenue*(.28+random*.18)),cashlessRevenue=revenue-cashRevenue,stockOpen=Math.round(revenue*(.58+storeIndex*.025+random*.09)),stockClose=Math.round(revenue*(.54+((storeIndex+monthIndex)%5)*.035+random*.08)),household=Math.round(expenses*.05),delivery=Math.round(expenses*.035),rent=Math.round(expenses*(.18+random*.06)),salaryCashless=Math.round(expenses*.19),writeoffSmoked=Math.round(revenue*(.006+storeIndex*.0008+random*.002)),writeoffFrozen=Math.round(revenue*(.008+(monthIndex%4)*.0009+random*.002));return {storeId:-(storeIndex+1),store,isHidden:false,importId:null,monthDate:month,entryDate:`${month}-01`,metrics:{revenue,cash_revenue:cashRevenue,cashless_revenue:cashlessRevenue,receipts_total:revenue,gross_profit:grossProfit,net_profit:netProfit,purchases,purchase_smoked:purchaseSmoked,purchase_frozen:purchaseFrozen,sales_smoked:salesSmoked,sales_frozen:salesFrozen,stock_open:stockOpen,stock_close:stockClose,household,delivery,cleaning:Math.round(expenses*.02),bonus:Math.round(expenses*.028),seniority:Math.round(expenses*.022),supplement:Math.round(expenses*.018),driver_cash:Math.round(expenses*.025),utilities_cash:Math.round(expenses*.035),operating_costs:Math.round(expenses*.03),cashless_operating_costs:Math.round(expenses*.04),cash_operating_costs:Math.round(expenses*.08),driver_cashless:Math.round(expenses*.035),utilities_cashless:Math.round(expenses*.045),rent,bank_fee:Math.round(expenses*.025),gross_profit_tax:Math.round(expenses*.04),salary_cashless:salaryCashless,payroll_tax:Math.round(expenses*.07),vacation_cashless:Math.round(expenses*.025),vacation_tax:Math.round(expenses*.016),salary_cash:Math.round(expenses*.065),vacation_cash:Math.round(expenses*.018),personal_income_tax_22:Math.round(expenses*.06),writeoff_smoked:writeoffSmoked,writeoff_frozen:writeoffFrozen,movement:Math.round(revenue*(.006+(storeIndex%3)*.002)),discount:Math.round(revenue*(.003+(monthIndex%3)*.001))},allocationRatio:1};}));
export function useImportedAudit(comparisonRange?:DateRangeValue,includeHidden=false){const {range,demoMode,demoSeed}=useAudit();const input=useMemo(()=>({ranges:comparisonRange?[range,comparisonRange]:[range]}),[comparisonRange?.from,comparisonRange?.to,range.from,range.to]);
  // Demo mode is deliberately synthetic: it neither reads nor renders a cached
  // financial dashboard response from the user's real workbook.
  const query=trpc.audit.dashboard.useQuery(input,{retry:false,enabled:!demoMode});
  const availability=trpc.audit.dashboardAvailability.useQuery(undefined,{retry:false,enabled:!demoMode,staleTime:300_000});
  const periods=useMemo(()=>{const source=demoMode?buildDemoPeriods(input.ranges,demoSeed):query.data?.periods??[];return source.filter(row=>includeHidden||!row.isHidden);},[demoMode,demoSeed,includeHidden,input.ranges,query.data?.periods]);const storeNames=useMemo(()=>Array.from(new Set(periods.map(row=>row.store))).sort(),[periods]);return {available:periods.length>0,hasAnyFinancialFacts:demoMode?true:Boolean(availability.data?.hasAnyFinancialFacts),financialCoverage:demoMode?null:availability.data??null,financialCoverageLoading:!demoMode&&availability.isLoading,periods,storeNames,loading:demoMode?false:query.isLoading,error:demoMode?null:query.error,demoMode}}
