import { ArrowRight, History, RotateCcw, UserRound } from "lucide-react";
import { AuditShell } from "@/components/AuditShell";
import { trpc } from "@/lib/trpc";

type ChangeEntry = { id:number; action:string; entityType:string; entityId:string; beforeState:unknown; afterState:unknown; createdAt:string|Date; actorName?:string|null; actorPhone?:string|null; rollbackOf?:number|null };
type DetailValue = unknown;
type DetailRecord = Record<string, unknown>;

const labels:Record<string,string>={"metric.update":"Изменение показателя","metric.delete":"Удаление показателя","metric.visibility":"Видимость факта","metric.rollback":"Откат показателя","store.visibility":"Видимость магазина","store.merge":"Объединение магазинов","import.commit":"Импорт Excel","import.delete":"Удаление импорта","account.create":"Создание учетной записи","account.update":"Изменение роли или статуса","account.password.change":"Смена пароля","account.login":"Вход в систему","account.logout":"Выход из системы","store_access.replace":"Изменение прав на магазины","weekly_report.schedule.update":"Настройка еженедельного отчета"};
const fieldLabels:Record<string,string>={storeName:"Магазин",storeId:"ID магазина",account:"Учетная запись",accountId:"ID учетной записи",entryDate:"Дата записи",metricName:"Показатель",metricCode:"Код показателя",amount:"Сумма, ₽",isHidden:"Скрыт",visibility:"Видимость",fileName:"Файл",sourceYear:"Год источника",periods:"Периодов",stores:"Магазинов",createdPeriods:"Создано периодов",updatedPeriods:"Заменено периодов",createdStores:"Создано магазинов",deletedPeriods:"Удалено периодов",deletedStores:"Удалено магазинов",source:"Исходный магазин",target:"Целевой магазин",moved:"Перенесено",replaced:"Заменено",skipped:"Пропущено",role:"Роль",isActive:"Активна",deleted:"Статус",grants:"Права магазинов",accessLabel:"Доступ",accessLevel:"Уровень доступа",weekday:"День недели",reportTime:"Время отчета"};
const formatValue=(value:DetailValue):string=>{if(value===null||value===undefined)return "—";if(typeof value==="boolean")return value?"Да":"Нет";if(typeof value==="number")return new Intl.NumberFormat("ru-RU",{maximumFractionDigits:2}).format(value);if(Array.isArray(value))return value.map(item=>{if(item&&typeof item==="object"&&!Array.isArray(item)){const record=item as DetailRecord;return `${String(record.storeName??record.account??record.storeId??"Объект")}: ${String(record.accessLabel??record.accessLevel??"")}`.trim()}return formatValue(item)}).join(" · ")||"Нет назначений";if(typeof value==="object")return Object.entries(value as DetailRecord).map(([key,item])=>`${fieldLabels[key]??key}: ${formatValue(item)}`).join(" · ");return String(value)};
const asRecord=(value:unknown):DetailRecord|null=>value&&typeof value==="object"&&!Array.isArray(value)?value as DetailRecord:null;
const importantKeys=["storeName","account","fileName","source","target","entryDate","metricName","amount","visibility","isHidden","role","isActive","grants","weekday","reportTime","deleted"];
function StateCard({title,state,tone}:{title:string;state:unknown;tone:"before"|"after"}){const data=asRecord(state);if(!data)return <div className={`audit-state ${tone}`}><small>{title}</small><p>{state===null?"Нет предыдущего состояния":formatValue(state as DetailValue)}</p></div>;const keys=Object.keys(data).filter(key=>importantKeys.includes(key));return <div className={`audit-state ${tone}`}><small>{title}</small>{keys.length?keys.map(key=><p key={key}><span>{fieldLabels[key]??key}</span><b>{formatValue(data[key])}</b></p>):<p>{formatValue(data)}</p>}</div>}
function objectLabel(change:ChangeEntry){const after=asRecord(change.afterState);const before=asRecord(change.beforeState);const state=after??before;return String(state?.storeName??state?.fileName??state?.account??state?.target??change.entityId)}

export default function ChangeLog(){const changes=trpc.audit.changes.useQuery(undefined,{retry:false});const entries=(changes.data??[]) as ChangeEntry[];const utils=trpc.useUtils();const rollback=trpc.audit.rollbackChange.useMutation({onSuccess:()=>utils.audit.changes.invalidate()});return <AuditShell kicker="14 / ЖУРНАЛ" title="История изменений и откат"><section className="page-lede"><div><span>АУДИТОРСКИЙ СЛЕД</span><h2>Каждое материальное действие можно проследить.</h2><p>Журнал фиксирует исполнителя, объект действия и изменения до → после. Откат доступен только для показателей и всегда создает новую запись, не удаляя историю.</p></div></section><section className="packet-card audit-log-card"><div className="audit-log-head"><div><span>ПОСЛЕДНИЕ 100 СОБЫТИЙ</span><h3>Кто, что и как изменил</h3></div><History size={20}/></div><div className="change-log detailed">{entries.length?entries.map(change=><article key={change.id} className="audit-entry"><header><div className="audit-entry-title"><strong>{labels[change.action]??change.action}</strong><span>{objectLabel(change)}</span></div><time>{new Date(change.createdAt).toLocaleString("ru-RU")}</time></header><div className="audit-actor"><UserRound size={14}/><b>{change.actorName??"Системное действие"}</b>{change.actorPhone&&<span>{change.actorPhone}</span>}{change.rollbackOf&&<span>Откат записи #{change.rollbackOf}</span>}</div><div className="audit-diff"><StateCard title="ДО" state={change.beforeState} tone="before"/><ArrowRight size={18}/><StateCard title="ПОСЛЕ" state={change.afterState} tone="after"/></div>{change.entityType==="metric"&&Boolean(change.beforeState)&&change.action!=="metric.rollback"&&<button className="subtle-button audit-rollback" disabled={rollback.isPending} onClick={()=>rollback.mutate({changeId:change.id})}><RotateCcw size={14}/>Откатить показатель</button>}</article>):<p>В журнале пока нет записей. Первая запись появится при следующем входе, импорте или изменении данных.</p>}</div></section></AuditShell>}
