import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowDownRight, ArrowUpRight, CalendarRange, ChartNoAxesCombined, CircleGauge, PackageSearch } from "lucide-react";
import { AuditShell } from "@/components/AuditShell";
import { DateRangeControl } from "@/components/DateRangeControl";
import { BenchmarkBars, MetricLineChart, formatK, formatPct } from "@/components/AuditCharts";
import { useAudit, type DateRangeValue } from "@/contexts/AuditContext";
import { useImportedAudit } from "@/hooks/useImportedAudit";
import { prepareDailyFacts } from "@/lib/dailyFacts";

const num=(row:{metrics:Record<string,number>},code:string)=>Number(row.metrics[code]??0);
const total=(rows:{metrics:Record<string,number>}[],code:string)=>rows.reduce((sum,row)=>sum+num(row,code),0);
const monthsIn=(range:DateRangeValue)=>{const result:string[]=[];for(const cursor=new Date(`${range.from.slice(0,7)}-01T12:00:00`),end=new Date(`${range.to.slice(0,7)}-01T12:00:00`);cursor<=end;cursor.setMonth(cursor.getMonth()+1))result.push(`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,"0")}`);return result};
const priorYear=(range:DateRangeValue):DateRangeValue=>({from:`${Number(range.from.slice(0,4))-1}${range.from.slice(4)}`,to:`${Number(range.to.slice(0,4))-1}${range.to.slice(4)}`});
const priorPeriod=(range:DateRangeValue):DateRangeValue=>{const from=new Date(`${range.from}T12:00:00`),to=new Date(`${range.to}T12:00:00`),length=Math.round((to.getTime()-from.getTime())/86400000)+1;const previousEnd=new Date(from);previousEnd.setDate(previousEnd.getDate()-1);const previousStart=new Date(previousEnd);previousStart.setDate(previousStart.getDate()-length+1);return {from:previousStart.toISOString().slice(0,10),to:previousEnd.toISOString().slice(0,10)}};
const shortRange=(range:DateRangeValue)=>`${new Date(`${range.from}T12:00:00`).toLocaleDateString("ru-RU",{day:"2-digit",month:"short",year:"numeric"})} — ${new Date(`${range.to}T12:00:00`).toLocaleDateString("ru-RU",{day:"2-digit",month:"short",year:"numeric"})}`;
const monthLabel=(month:string)=>new Date(`${month}-01T12:00:00`).toLocaleDateString("ru-RU",{month:"short"}).replace(".","");
const money=(value:number)=>formatK(value/1000);

export default function ControlCenter(){
  const {range,selectedStore}=useAudit(); const [comparison,setComparison]=useState<DateRangeValue>(()=>priorYear(range)); const imported=useImportedAudit(comparison); const [linked,setLinked]=useState(true);
  useEffect(()=>{if(linked)setComparison(priorYear(range))},[linked,range]);
  const baseMonths=useMemo(()=>monthsIn(range),[range]); const compareMonths=useMemo(()=>monthsIn(comparison),[comparison]);
  const base=useMemo(()=>prepareDailyFacts(imported.periods,range),[imported.periods,range]);
  const compared=useMemo(()=>prepareDailyFacts(imported.periods,comparison),[comparison,imported.periods]);
  const available=Boolean(base.length&&compared.length); const baseLabel=shortRange(range),compareLabel=shortRange(comparison);
  const byPosition=useMemo(()=>baseMonths.map((month,index)=>{const comparator=compareMonths[index];return {month:monthLabel(month),baseRevenue:total(base.filter(row=>row.monthDate===month),"revenue")/1000,compareRevenue:total(compared.filter(row=>row.monthDate===comparator),"revenue")/1000,baseProfit:total(base.filter(row=>row.monthDate===month),"net_profit")/1000,compareProfit:total(compared.filter(row=>row.monthDate===comparator),"net_profit")/1000}}),[base,baseMonths,compared,compareMonths]);
  const stores=useMemo(()=>{const names=Array.from(new Set([...base,...compared].map(row=>row.store)));return names.map(store=>{const main=base.filter(row=>row.store===store),previous=compared.filter(row=>row.store===store);const revenue=total(main,"revenue"),revenuePrevious=total(previous,"revenue"),profit=total(main,"net_profit"),profitPrevious=total(previous,"net_profit"),latest=[...main].sort((a,b)=>a.monthDate.localeCompare(b.monthDate)).at(-1),stock=latest?num(latest,"stock_close"):0,writeoffs=total(main,"writeoff_frozen");const coverDays=revenue?stock/(revenue/Math.max(main.length,1))*30:0;return {store,revenue,revenuePrevious,profit,profitPrevious,deltaProfit:profit-profitPrevious,margin:revenue?profit/revenue*100:0,coverDays,writeoffRate:revenue?writeoffs/revenue*100:0}}).filter(item=>item.revenue||item.revenuePrevious)},[base,compared]);
  const network={revenue:total(base,"revenue"),revenuePrevious:total(compared,"revenue"),profit:total(base,"net_profit"),profitPrevious:total(compared,"net_profit")};
  const leader=[...stores].sort((a,b)=>b.deltaProfit-a.deltaProfit)[0]; const decline=[...stores].sort((a,b)=>a.deltaProfit-b.deltaProfit)[0];
  const riskStores=[...stores].filter(item=>item.coverDays>20||item.writeoffRate>1.5).sort((a,b)=>b.coverDays-a.coverDays).slice(0,7);
  const rankings=[...stores].sort((a,b)=>b.deltaProfit-a.deltaProfit).map(item=>({store:item.store,value:item.deltaProfit/1000,selected:selectedStore===item.store})); const selectedLabel=selectedStore==="__all__"?"Все магазины":selectedStore;
  const onCompare=(next:DateRangeValue)=>{setLinked(false);setComparison(next)};
  if(imported.loading)return <AuditShell kicker="15 / ДИНАМИКА" title="Сравнение периодов"><section className="empty-state"><h2>Готовим сравнение периодов…</h2></section></AuditShell>;
  return <AuditShell kicker="15 / ДИНАМИКА" title="Динамика и сравнение периодов">
    <section className="page-lede"><div><span>ДОПОЛНИТЕЛЬНЫЙ УПРАВЛЕНЧЕСКИЙ СЛОЙ</span><h2>Рост, качество прибыли и деньги в запасе</h2><p>Выберите любые два периода с данными. Система сопоставляет месяцы по порядку внутри диапазонов, поэтому после загрузки 2027 года можно сравнить его с 2026, 2025 или произвольным отрезком.</p></div></section>
    <section className="comparison-periods"><article><span>ОСНОВНОЙ ПЕРИОД</span><DateRangeControl value={range} title="ОСНОВНОЙ ПЕРИОД" ariaLabel="Изменить основной период"/><small>{baseLabel}</small></article><div className="compare-divider"><CalendarRange size={19}/><b>против</b></div><article><span>СРАВНИТЕЛЬНЫЙ ПЕРИОД</span><DateRangeControl value={comparison} onChange={onCompare} title="СРАВНИТЕЛЬНЫЙ ПЕРИОД" ariaLabel="Изменить сравнительный период"/><small>{compareLabel}</small></article><div className="compare-presets"><button type="button" className={linked?"active":""} onClick={()=>{setLinked(true);setComparison(priorYear(range))}}>Предыдущий год</button><button type="button" onClick={()=>{setLinked(false);setComparison(priorPeriod(range))}}>Предыдущий период</button></div></section>
    {!available?<section className="empty-state"><ChartNoAxesCombined size={30}/><h2>Нет полного набора для сравнения</h2><p>В одном из выбранных диапазонов нет импортированных показателей. Измените основной или сравнительный период — оба календаря независимы.</p></section>:<>
      <section className="kpi-grid control-kpis"><article className="packet-kpi"><span>ВЫРУЧКА · РАЗНИЦА ПЕРИОДОВ</span><strong>{money(network.revenue-network.revenuePrevious)}</strong><small>{network.revenuePrevious?formatPct((network.revenue/network.revenuePrevious-1)*100):"—"} к сравнительному периоду</small></article><article className={network.profit-network.profitPrevious<0?"packet-kpi risk":"packet-kpi"}><span>ЧИСТАЯ ПРИБЫЛЬ · РАЗНИЦА</span><strong>{money(network.profit-network.profitPrevious)}</strong><small>{network.profitPrevious?formatPct((network.profit/network.profitPrevious-1)*100):"—"} к сравнительному периоду</small></article><article className="packet-kpi"><span>ЛУЧШИЙ ПРИРОСТ ПРИБЫЛИ</span><strong>{leader?.store??"—"}</strong><small>{leader?money(leader.deltaProfit):"нет сопоставимой точки"}</small></article><article className="packet-kpi risk"><span>НАИБОЛЬШЕЕ СНИЖЕНИЕ</span><strong>{decline?.store??"—"}</strong><small>{decline?money(decline.deltaProfit):"нет сопоставимой точки"}</small></article></section>
      <section className="two-col"><article className="packet-card"><div className="card-title"><div><span>ТРАЕКТОРИЯ ВЫРУЧКИ</span><h3>{baseLabel}</h3><small>Сопоставление с: {compareLabel}</small></div></div><MetricLineChart data={byPosition} lines={[{key:"baseRevenue",name:"Основной период",color:"#ffb04a"},{key:"compareRevenue",name:"Сравнительный",color:"#7a658a"}]} unit="k"/></article><article className="packet-card"><div className="card-title"><div><span>ТРАЕКТОРИЯ ЧИСТОЙ ПРИБЫЛИ</span><h3>{baseLabel}</h3><small>Месяцы соединены по порядку в каждом периоде</small></div></div><MetricLineChart data={byPosition} lines={[{key:"baseProfit",name:"Основной период",color:"#6fe0c8"},{key:"compareProfit",name:"Сравнительный",color:"#ff7c9b"}]} unit="k"/></article></section>
      <section className="packet-card"><div className="card-title"><div><span>РЕЙТИНГ ИЗМЕНЕНИЯ ПРИБЫЛИ</span><h3>Какие магазины формируют разницу периодов</h3></div><small>Положительное значение — рост чистой прибыли</small></div><BenchmarkBars data={rankings} median={0} mode="amount" selectedLabel={selectedLabel}/></section>
      <section className="packet-card"><div className="card-title"><div><span>ДЕНЬГИ В ЗАПАСЕ</span><h3>Точки для проверки остатка и списаний</h3></div><PackageSearch size={18}/></div><div className="control-watch-list">{riskStores.length?riskStores.map(item=><article key={item.store} className={item.coverDays>30||item.writeoffRate>3?"watch-card risk":"watch-card"}><div><strong>{item.store}</strong><small>Маржа: {formatPct(item.margin)} · разница прибыли: {money(item.deltaProfit)}</small></div><div><span>Покрытие</span><b>{item.coverDays.toFixed(1)} дня</b></div><div><span>Списания М.</span><b>{formatPct(item.writeoffRate)} выручки</b></div>{item.deltaProfit>=0?<ArrowUpRight className="positive" size={19}/>:<ArrowDownRight className="negative" size={19}/>}</article>):<div className="empty-state compact"><CircleGauge size={24}/><h2>Риск-зон нет</h2><p>В основном периоде покрытие и доля списаний не превышают контрольные пороги.</p></div>}</div><p className="packet-note"><AlertTriangle size={14}/> Покрытие выше 20 дней или списания М. выше 1,5% выручки — сигнал для проверки закупок, оборачиваемости и причин уценки, а не автоматическое решение.</p></section>
    </>}
  </AuditShell>;
}
