import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowDownRight, ArrowUpRight, CalendarRange, ChartNoAxesCombined, CircleGauge, PackageSearch } from "lucide-react";
import { AuditShell } from "@/components/AuditShell";
import { DateRangeControl } from "@/components/DateRangeControl";
import { BenchmarkBars, MetricLineChart, formatK, formatPct } from "@/components/AuditCharts";
import { FactsLoader } from "@/components/OceanLoader";
import { useAudit, type DateRangeValue } from "@/contexts/AuditContext";
import { useImportedAudit } from "@/hooks/useImportedAudit";
import { prepareDailyFacts } from "@/lib/dailyFacts";

const num=(row:{metrics:Record<string,number>},code:string)=>Number(row.metrics[code]??0);
const total=(rows:{metrics:Record<string,number>}[],code:string)=>rows.reduce((sum,row)=>sum+num(row,code),0);
const hasMetric=(rows:{metrics:Record<string,number>}[],code:string)=>rows.some(row=>Object.hasOwn(row.metrics,code));
const totalIfAvailable=(rows:{metrics:Record<string,number>}[],code:string)=>hasMetric(rows,code)?total(rows,code):null;
const monthsIn=(range:DateRangeValue)=>{const result:string[]=[];for(const cursor=new Date(`${range.from.slice(0,7)}-01T12:00:00`),end=new Date(`${range.to.slice(0,7)}-01T12:00:00`);cursor<=end;cursor.setMonth(cursor.getMonth()+1))result.push(`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,"0")}`);return result};
const priorYear=(range:DateRangeValue):DateRangeValue=>({from:`${Number(range.from.slice(0,4))-1}${range.from.slice(4)}`,to:`${Number(range.to.slice(0,4))-1}${range.to.slice(4)}`});
const priorPeriod=(range:DateRangeValue):DateRangeValue=>{const from=new Date(`${range.from}T12:00:00`),to=new Date(`${range.to}T12:00:00`),length=Math.round((to.getTime()-from.getTime())/86400000)+1;const previousEnd=new Date(from);previousEnd.setDate(previousEnd.getDate()-1);const previousStart=new Date(previousEnd);previousStart.setDate(previousStart.getDate()-length+1);return {from:previousStart.toISOString().slice(0,10),to:previousEnd.toISOString().slice(0,10)}};
const shortRange=(range:DateRangeValue)=>`${new Date(`${range.from}T12:00:00`).toLocaleDateString("ru-RU",{day:"2-digit",month:"short",year:"numeric"})} — ${new Date(`${range.to}T12:00:00`).toLocaleDateString("ru-RU",{day:"2-digit",month:"short",year:"numeric"})}`;
const monthLabel=(month:string)=>new Date(`${month}-01T12:00:00`).toLocaleDateString("ru-RU",{month:"short"}).replace(".","");
const money=(value:number)=>formatK(value/1000);

export default function ControlCenter(){
  const {range,selectedStore}=useAudit(); const [comparison,setComparison]=useState<DateRangeValue>(()=>priorYear(range)); const imported=useImportedAudit(comparison); const [linked,setLinked]=useState(true);
  useEffect(()=>{if(linked)setComparison(priorYear(range))},[linked,range]);
  const baseMonths=useMemo(()=>monthsIn(range),[range]); const compareMonths=useMemo(()=>monthsIn(comparison),[comparison]);
  const base=useMemo(()=>prepareDailyFacts(imported.periods,range),[imported.periods,range]);
  const compared=useMemo(()=>prepareDailyFacts(imported.periods,comparison),[comparison,imported.periods]);
  const available=Boolean(base.length&&compared.length); const baseLabel=shortRange(range),compareLabel=shortRange(comparison);
  const byPosition=useMemo(()=>Array.from({length:Math.max(baseMonths.length,compareMonths.length)},(_,index)=>{const baseMonth=baseMonths[index]??null,compareMonth=compareMonths[index]??null;const baseRows=baseMonth?base.filter(row=>row.monthDate===baseMonth):[];const compareRows=compareMonth?compared.filter(row=>row.monthDate===compareMonth):[];const baseRevenueRaw=totalIfAvailable(baseRows,"revenue"),compareRevenueRaw=totalIfAvailable(compareRows,"revenue"),baseProfitRaw=totalIfAvailable(baseRows,"net_profit"),compareProfitRaw=totalIfAvailable(compareRows,"net_profit");const baseRevenue=baseRevenueRaw===null?null:baseRevenueRaw/1000,compareRevenue=compareRevenueRaw===null?null:compareRevenueRaw/1000,baseProfit=baseProfitRaw===null?null:baseProfitRaw/1000,compareProfit=compareProfitRaw===null?null:compareProfitRaw/1000;return {month:`${baseMonth?monthLabel(baseMonth):"—"} / ${compareMonth?monthLabel(compareMonth):"—"}`,baseMonth,compareMonth,baseRevenue,compareRevenue,baseProfit,compareProfit}}).filter(row=>row.baseRevenue!==null||row.compareRevenue!==null||row.baseProfit!==null||row.compareProfit!==null),[base,baseMonths,compared,compareMonths]);
  const stores=useMemo(()=>{const names=Array.from(new Set([...base,...compared].map(row=>row.store)));return names.map(store=>{const main=base.filter(row=>row.store===store),previous=compared.filter(row=>row.store===store);const revenue=total(main,"revenue"),revenuePrevious=total(previous,"revenue"),profit=total(main,"net_profit"),profitPrevious=total(previous,"net_profit"),latest=[...main].sort((a,b)=>a.monthDate.localeCompare(b.monthDate)).at(-1),stock=latest?num(latest,"stock_close"):0,writeoffs=total(main,"writeoff_frozen");const coverDays=revenue?stock/(revenue/Math.max(main.length,1))*30:0;return {store,revenue,revenuePrevious,profit,profitPrevious,deltaProfit:profit-profitPrevious,margin:revenue?profit/revenue*100:0,coverDays,writeoffRate:revenue?writeoffs/revenue*100:0}}).filter(item=>item.revenue||item.revenuePrevious)},[base,compared]);
  const comparableMonths=byPosition.filter(row=>row.baseRevenue!==null&&row.compareRevenue!==null&&row.baseProfit!==null&&row.compareProfit!==null);const network=comparableMonths.length?{revenue:comparableMonths.reduce((sum,row)=>sum+(row.baseRevenue??0)*1000,0),revenuePrevious:comparableMonths.reduce((sum,row)=>sum+(row.compareRevenue??0)*1000,0),profit:comparableMonths.reduce((sum,row)=>sum+(row.baseProfit??0)*1000,0),profitPrevious:comparableMonths.reduce((sum,row)=>sum+(row.compareProfit??0)*1000,0)}:null;
  const leader=network?[...stores].sort((a,b)=>b.deltaProfit-a.deltaProfit)[0]:null; const decline=network?[...stores].sort((a,b)=>a.deltaProfit-b.deltaProfit)[0]:null;
  const riskStores=[...stores].filter(item=>item.coverDays>20||item.writeoffRate>1.5).sort((a,b)=>b.coverDays-a.coverDays).slice(0,7);
  const rankings=[...stores].sort((a,b)=>b.deltaProfit-a.deltaProfit).map(item=>({store:item.store,value:item.deltaProfit/1000,selected:selectedStore===item.store})); const selectedLabel=selectedStore==="__all__"?"Все магазины":selectedStore;
  const onCompare=(next:DateRangeValue)=>{setLinked(false);setComparison(next)};
  if(imported.loading)return <AuditShell kicker="15 / ДИНАМИКА" title="Сравнение периодов"><section className="empty-state"><FactsLoader label="Готовим сравнение периодов…"/></section></AuditShell>;
  return <AuditShell kicker="15 / ДИНАМИКА" title="Динамика и сравнение периодов">
    <section className="page-lede"><div><span>ДОПОЛНИТЕЛЬНЫЙ УПРАВЛЕНЧЕСКИЙ СЛОЙ</span><h2>Рост, качество прибыли и деньги в запасе</h2><p>Выберите любые два периода с данными. Система сопоставляет месяцы по порядку внутри диапазонов, поэтому после загрузки 2027 года можно сравнить его с 2026, 2025 или произвольным отрезком.</p></div></section>
    <section className="comparison-periods"><article><span>ОСНОВНОЙ ПЕРИОД</span><DateRangeControl value={range} title="ОСНОВНОЙ ПЕРИОД" ariaLabel="Изменить основной период"/><small>{baseLabel}</small></article><div className="compare-divider"><CalendarRange size={19}/><b>против</b></div><article><span>СРАВНИТЕЛЬНЫЙ ПЕРИОД</span><DateRangeControl value={comparison} onChange={onCompare} title="СРАВНИТЕЛЬНЫЙ ПЕРИОД" ariaLabel="Изменить сравнительный период"/><small>{compareLabel}</small></article></section>
    {!available?<section className="empty-state"><ChartNoAxesCombined size={30}/><h2>Нет полного набора для сравнения</h2><p>В одном из выбранных диапазонов нет импортированных показателей. Измените основной или сравнительный период — оба календаря независимы.</p></section>:<>
      {!network&&<section className="packet-note control-comparison-note"><AlertTriangle size={14}/> Для выбранных периодов нет месяцев, где одновременно есть выручка и чистая прибыль. Графики показывают имеющиеся факты, но разница периодов и рейтинг не рассчитываются из неполной базы.</section>}<section className="kpi-grid control-kpis"><article className="packet-kpi"><span>ВЫРУЧКА · РАЗНИЦА ПЕРИОДОВ</span><strong>{network?money(network.revenue-network.revenuePrevious):"—"}</strong><small>{network?.revenuePrevious?formatPct((network.revenue/network.revenuePrevious-1)*100):"нет сопоставимых месяцев"}</small></article><article className={network&&network.profit-network.profitPrevious<0?"packet-kpi risk":"packet-kpi"}><span>ЧИСТАЯ ПРИБЫЛЬ · РАЗНИЦА</span><strong>{network?money(network.profit-network.profitPrevious):"—"}</strong><small>{network?.profitPrevious?formatPct((network.profit/network.profitPrevious-1)*100):"нет сопоставимых месяцев"}</small></article><article className="packet-kpi"><span>ЛУЧШИЙ ПРИРОСТ ПРИБЫЛИ</span><strong>{leader?.store??"—"}</strong><small>{leader?money(leader.deltaProfit):"нет сопоставимой точки"}</small></article><article className="packet-kpi risk"><span>НАИБОЛЬШЕЕ СНИЖЕНИЕ</span><strong>{decline?.store??"—"}</strong><small>{decline?money(decline.deltaProfit):"нет сопоставимой точки"}</small></article></section>
      <section className="two-col"><article className="packet-card"><div className="card-title"><div><span>ТРАЕКТОРИЯ ВЫРУЧКИ</span><h3>{baseLabel}</h3><small>Сопоставление с: {compareLabel}</small></div></div><MetricLineChart data={byPosition} lines={[{key:"baseRevenue",name:"Основной период",color:"#ffb04a"},{key:"compareRevenue",name:"Сравнительный",color:"#7a658a"}]} unit="k"/></article><article className="packet-card"><div className="card-title"><div><span>ТРАЕКТОРИЯ ЧИСТОЙ ПРИБЫЛИ</span><h3>{baseLabel}</h3><small>Месяцы сопоставлены по порядку; отсутствующий факт не подменяется нулём.</small></div></div><MetricLineChart data={byPosition} lines={[{key:"baseProfit",name:"Основной период",color:"#6fe0c8"},{key:"compareProfit",name:"Сравнительный",color:"#ff7c9b"}]} unit="k"/></article></section>
      <section className="packet-card control-month-table"><div className="card-title"><div><span>ПРОВЕРКА РАСЧЕТА ПО МЕСЯЦАМ</span><h3>Факт обоих периодов и разница без смешения лет</h3></div><small>пустая ячейка означает отсутствие факта, а не нулевое значение</small></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Позиция</th><th>Основной месяц</th><th>Сравнительный месяц</th><th>Выручка · основной</th><th>Выручка · сравнительный</th><th>Δ выручки</th><th>Прибыль · основной</th><th>Прибыль · сравнительный</th><th>Δ прибыли</th></tr></thead><tbody>{byPosition.map((row,index)=>{const revenueDelta=row.baseRevenue!==null&&row.compareRevenue!==null?row.baseRevenue-row.compareRevenue:null;const profitDelta=row.baseProfit!==null&&row.compareProfit!==null?row.baseProfit-row.compareProfit:null;const cell=(amount:number|null)=>amount===null?"—":money(amount*1000);return <tr key={`${row.baseMonth??"none"}-${row.compareMonth??"none"}`}><td>{index+1}</td><td>{row.baseMonth??"—"}</td><td>{row.compareMonth??"—"}</td><td>{cell(row.baseRevenue)}</td><td>{cell(row.compareRevenue)}</td><td className={revenueDelta===null?"":revenueDelta>=0?"positive":"negative"}>{revenueDelta===null?"—":`${revenueDelta>0?"+":""}${money(revenueDelta*1000)}`}</td><td>{cell(row.baseProfit)}</td><td>{cell(row.compareProfit)}</td><td className={profitDelta===null?"":profitDelta>=0?"positive":"negative"}>{profitDelta===null?"—":`${profitDelta>0?"+":""}${money(profitDelta*1000)}`}</td></tr>})}</tbody></table></div></section>
      <section className="packet-card"><div className="card-title"><div><span>РЕЙТИНГ ИЗМЕНЕНИЯ ПРИБЫЛИ</span><h3>Какие магазины формируют разницу периодов</h3></div><small>Положительное значение — рост чистой прибыли</small></div>{network?<BenchmarkBars data={rankings} median={0} mode="amount" selectedLabel={selectedLabel}/>:<div className="empty-state compact"><CircleGauge size={24}/><h2>Рейтинг ожидает сопоставимый факт</h2><p>Выберите два периода с одинаковыми доступными месяцами, чтобы не сравнивать полный период с частичным.</p></div>}</section>
      <section className="packet-card"><div className="card-title"><div><span>ДЕНЬГИ В ЗАПАСЕ</span><h3>Точки для проверки остатка и списаний</h3></div><PackageSearch size={18}/></div><div className="control-watch-list">{riskStores.length?riskStores.map(item=><article key={item.store} className={item.coverDays>30||item.writeoffRate>3?"watch-card risk":"watch-card"}><div><strong>{item.store}</strong><small>Маржа: {formatPct(item.margin)} · разница прибыли: {money(item.deltaProfit)}</small></div><div><span>Покрытие</span><b>{item.coverDays.toFixed(1)} дня</b></div><div><span>Списания М.</span><b>{formatPct(item.writeoffRate)} выручки</b></div>{item.deltaProfit>=0?<ArrowUpRight className="positive" size={19}/>:<ArrowDownRight className="negative" size={19}/>}</article>):<div className="empty-state compact"><CircleGauge size={24}/><h2>Риск-зон нет</h2><p>В основном периоде покрытие и доля списаний не превышают контрольные пороги.</p></div>}</div><p className="packet-note"><AlertTriangle size={14}/> Покрытие выше 20 дней или списания М. выше 1,5% выручки — сигнал для проверки закупок, оборачиваемости и причин уценки, а не автоматическое решение.</p></section>
    </>}
  </AuditShell>;
}
