/**
 * AuditLine design reminder: editorial asymmetric layout; warm paper with forest-green
 * authority; cinnabar encodes risks; jade encodes confirmed improvement.
 */
import { useMemo, useState } from "react";
import { Area, AreaChart, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowDownRight, ArrowUpRight, CheckCircle2, Copy, Download, Menu, Search, ShieldCheck, X } from "lucide-react";
import { actionPlan, auditChecks, costData, inventoryData, monthlyData, network, stores, type StoreProfile } from "@/data/auditData";

const heroImage = "/manus-storage/auditline-hero-2026_94861469.jpg";
const logoImage = "/manus-storage/auditline-logo_846ed825.png";
const fmtMoney = (n: number, digits = 1) => `${n.toLocaleString("ru-RU", { minimumFractionDigits: digits, maximumFractionDigits: digits })} млн ₽`;
const fmtShort = (n: number) => `${n.toLocaleString("ru-RU", { minimumFractionDigits: 1, maximumFractionDigits: 1 })} млн`;
const findStore = (name: string) => stores.find((store) => store.store === name)!;

function Metric({ label, value, hint, risk = false }: { label: string; value: string; hint: string; risk?: boolean }) {
  return <article className={`metric ${risk ? "metric-risk" : ""}`}><p>{label}</p><strong>{value}</strong><span>{hint}</span></article>;
}

function StoreDrawer({ store, onClose }: { store: StoreProfile; onClose: () => void }) {
  const loss = store.netProfit < 0;
  return <div className="drawer-overlay" onClick={onClose} role="presentation"><aside className="store-drawer" onClick={(event) => event.stopPropagation()} aria-label={`Профиль магазина ${store.store}`}>
    <button className="icon-button" onClick={onClose} aria-label="Закрыть профиль"><X size={22} /></button><p className="eyebrow">ПРОФИЛЬ МАГАЗИНА</p><h2>{store.store}</h2>
    <div className={`drawer-outcome ${loss ? "negative" : "positive"}`}><span>Чистая прибыль</span><strong>{fmtMoney(store.netProfit)}</strong><em>{store.netMargin.toFixed(1)}% чистая маржа</em></div>
    <dl className="drawer-list"><div><dt>Выручка</dt><dd>{fmtMoney(store.revenue)}</dd></div><div><dt>Валовая маржа</dt><dd>{store.grossMargin.toFixed(1)}%</dd></div><div><dt>Лучший / худший месяц</dt><dd>{store.bestMonth} / {store.worstMonth}</dd></div><div><dt>Убыточных месяцев</dt><dd>{store.lossMonths}</dd></div><div><dt>Главный резерв</dt><dd>{store.reserve}</dd></div><div><dt>Резерв к медиане</dt><dd>{store.reserveAmount ? fmtMoney(store.reserveAmount) : "Не выявлен"}</dd></div><div><dt>Изменение остатка</dt><dd className={store.inventoryEffect < 0 ? "money-negative" : "money-positive"}>{fmtMoney(store.inventoryEffect, 2)}</dd></div></dl>
    <div className="drawer-callout"><ShieldCheck size={20} /><p>{store.narrative}</p></div>
  </aside></div>;
}

export default function Home() {
  const [filter, setFilter] = useState<"all" | "leaders" | "losses" | "at-risk">("all");
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState<StoreProfile | null>(null); const [copied, setCopied] = useState(false); const [menuOpen, setMenuOpen] = useState(false);
  const filteredStores = useMemo(() => stores.filter((store) => {
    const match = store.store.toLowerCase().includes(query.toLowerCase());
    const group = filter === "all" || (filter === "leaders" && store.netMargin >= network.netMargin) || (filter === "losses" && store.netProfit < 0) || (filter === "at-risk" && store.netProfit >= 0 && store.netMargin < 2);
    return match && group;
  }).sort((a, b) => b.netProfit - a.netProfit), [filter, query]);
  const revenueTraps = stores.filter((store) => store.revenue >= 16 && store.netMargin < 2).slice(0, 3);
  const heroes = stores.filter((store) => store.revenue < 17 && store.netMargin >= 4.2 && store.netProfit > 0).slice(0, 3);
  const share = async () => { await navigator.clipboard?.writeText(window.location.href); setCopied(true); window.setTimeout(() => setCopied(false), 1700); };

  return <main className="audit-page">
    <header className="topbar"><a className="brand" href="#top"><img src={logoImage} alt="" /><span>AuditLine</span></a><nav className={menuOpen ? "nav nav-open" : "nav"}><a href="#dynamics" onClick={() => setMenuOpen(false)}>Динамика</a><a href="#portfolio" onClick={() => setMenuOpen(false)}>Портфель</a><a href="#plan" onClick={() => setMenuOpen(false)}>Действия</a></nav><div className="topbar-actions"><button className="share-button" onClick={share}><Copy size={15} />{copied ? "Ссылка скопирована" : "Поделиться"}</button><button className="print-button" onClick={() => window.print()}><Download size={15} />Сохранить</button><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Открыть меню"><Menu size={20} /></button></div></header>
    <aside className="report-spine" aria-label="Корешок отчета"><a href="#top" className="spine-mark"><img src={logoImage} alt="" /><span>AL</span></a><div className="spine-rule"/><nav className="spine-nav"><a href="#top"><b>00</b><span>Сводка</span></a><a href="#dynamics"><b>01</b><span>Динамика</span></a><a href="#portfolio"><b>03</b><span>Портфель</span></a><a href="#plan"><b>05</b><span>Действия</span></a></nav><div className="spine-period"><span>ПЕРИОД</span><strong>2026</strong><small>ЯНВ–АВГ</small></div></aside>
    <section id="top" className="hero"><img className="hero-photo" src={heroImage} alt="Аналитические материалы и график"/><div className="hero-content"><p className="eyebrow">РИТЕЙЛ-СЕТЬ · АУДИТ P&amp;L · ЯНВ–АВГ 2026</p><h1>Прибыль есть.<br/><em>Устойчивость — под вопросом.</em></h1><p className="hero-lede">Очищенная сеть заработала <strong>{fmtMoney(network.netProfit)}</strong> при выручке <strong>{fmtMoney(network.revenue)}</strong>. При этом {network.lossCount} убыточных точек уже сформировали {fmtMoney(network.losses)} потерь.</p><a className="hero-link" href="#portfolio">Открыть портфель <ArrowDownRight size={18}/></a></div><div className="hero-note"><span>Период</span><strong>Январь–август 2026</strong><small>Без КА1, АЛА, МОЛ и РЕЗ*</small></div></section>
    <section className="metrics-strip"><Metric label="Выручка" value={fmtMoney(network.revenue)} hint="январь–август 2026"/><Metric label="Валовая прибыль" value={fmtMoney(network.grossProfit)} hint="маржа 25,6%"/><Metric label="Чистая прибыль" value={fmtMoney(network.netProfit)} hint={`маржа ${network.netMargin.toFixed(1)}%`}/><Metric label="Убыточные точки" value={`${network.lossCount} из ${network.storeCount}`} hint={`потери ${fmtMoney(network.losses)}`} risk/></section>
    <section className="section feature-grid traced" id="dynamics"><div className="audit-trail"><span>ФАКТ</span><i/><span>РИСК</span><i/><span>ДЕЙСТВИЕ</span></div><div className="section-intro"><p className="eyebrow">01 / ДИНАМИКА СЕТИ</p><h2>Продажи не гарантируют прибыль.</h2><p>В марте сеть заработала {fmtMoney(network.peak.net_profit / 1_000_000)} при марже {(network.peak.net_margin * 100).toFixed(1)}%. В июле прибыль снизилась до {fmtMoney(network.trough.net_profit / 1_000_000)} и маржи {(network.trough.net_margin * 100).toFixed(1)}%.</p><div className="signal-list"><div><ArrowDownRight/><span>Провал: <strong>июль · 0,87 млн ₽</strong><small>чистая маржа 1,1%</small></span></div><div><ArrowUpRight/><span>Пик: <strong>март · 6,93 млн ₽</strong><small>чистая маржа 7,2%</small></span></div></div></div><div className="chart-panel trend-panel"><div className="panel-heading"><div><span className="tiny-label">ФАКТ ПО МЕСЯЦАМ</span><h3>Выручка и чистая прибыль</h3></div><span>млн ₽</span></div><ResponsiveContainer width="100%" height={310}><AreaChart data={monthlyData} margin={{top:16,right:6,left:-20,bottom:0}}><defs><linearGradient id="profitFill" x1="0" x2="0" y1="0" y2="1"><stop offset="5%" stopColor="#b6453d" stopOpacity={0.32}/><stop offset="95%" stopColor="#b6453d" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fill:"#6b6964",fontSize:12}}/><YAxis yAxisId="left" axisLine={false} tickLine={false} tick={{fill:"#6b6964",fontSize:11}}/><YAxis yAxisId="right" orientation="right" axisLine={false} tickLine={false} tick={{fill:"#aa4439",fontSize:11}}/><Tooltip cursor={{stroke:"#c8bfaf"}} contentStyle={{border:"1px solid #d8d0c0",borderRadius:0,background:"#fbf7ef"}} formatter={(value:number,name:string)=>[`${value.toLocaleString("ru-RU")} млн ₽`,name]}/><Area yAxisId="left" type="monotone" dataKey="revenue" name="Выручка" stroke="#145b44" strokeWidth={2.5} fill="none"/><Area yAxisId="right" type="monotone" dataKey="profit" name="Чистая прибыль" stroke="#b6453d" strokeWidth={3} fill="url(#profitFill)"/></AreaChart></ResponsiveContainer><p className="chart-footnote">Июль — минимальный месяц: валовая маржа 23,9% против 26,6% в марте. Приоритет — закупки, уценка, ассортимент и ФОТ.</p></div></section>
    <section className="section cost-section traced"><div className="audit-trail"><span>ФАКТ</span><i/><span>ОСТАТОК</span><i/><span>РЫЧАГ</span></div><div className="cost-header"><p className="eyebrow">02 / ЗАТРАТЫ И ОСТАТОК</p><h2>После закупок главный рычаг — ФОТ.</h2></div><div className="cost-layout"><div className="chart-panel donut-panel"><ResponsiveContainer width="100%" height={305}><PieChart><Pie data={costData} dataKey="value" nameKey="name" cx="50%" cy="48%" innerRadius={70} outerRadius={112} stroke="none" paddingAngle={2}>{costData.map((item)=><Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip formatter={(value:number)=>`${value.toLocaleString("ru-RU")} млн ₽`} contentStyle={{border:"1px solid #d8d0c0",borderRadius:0,background:"#fbf7ef"}}/><Legend verticalAlign="bottom" iconType="circle" wrapperStyle={{fontSize:12}}/></PieChart></ResponsiveContainer><div className="donut-core"><span>ФОТ + налоги</span><strong>60,7</strong><small>млн ₽ · 9,1% выручки</small></div></div><div className="cost-ledger">{costData.map((item,index)=><div className={index===1?"cost-row highlighted":"cost-row"} key={item.name}><span><i style={{background:item.color}}/>{item.name}</span><strong>{fmtShort(item.value)}</strong><em>{((item.value/network.revenue)*100).toFixed(1)}%</em></div>)}<p>Чистый эффект перемещений, уценок и переоценок на остаток: <strong className="money-negative">−0,19 млн ₽</strong>. Эти движения не включены в чистую прибыль, если отсутствуют в формуле AQ.</p></div></div></section>
    <section className="section portfolio-section traced" id="portfolio"><div className="audit-trail"><span>СЕТЬ</span><i/><span>ТОЧКА</span><i/><span>РЕЗЕРВ</span></div><div className="portfolio-heading"><div><p className="eyebrow">03 / ПОРТФЕЛЬ МАГАЗИНОВ</p><h2>Сильные точки финансируют слабые.</h2></div><p>Три лидера — ПОРТ, А2 и КИР1 — создают <strong>{network.topShare.toFixed(1)}%</strong> чистой прибыли очищенной сети. Нажмите строку, чтобы открыть профиль точки.</p></div><div className="rankings"><div className="ranking-card leader-card"><div className="card-top"><span>ЛИДЕРЫ ПО ПРИБЫЛИ</span><strong className="positive">18,2 млн ₽</strong></div>{network.top3.map((item,index)=>{const s=findStore(item.store);return <button key={s.store} onClick={()=>setSelected(s)}><b>0{index+1}</b><span>{s.store}</span><em>{fmtMoney(s.netProfit)}</em><i>{s.netMargin.toFixed(1)}%</i></button>})}</div><div className="ranking-card risk-card"><div className="card-top"><span>САМЫЕ ГЛУБОКИЕ УБЫТКИ</span><strong className="negative">(2,5 млн ₽)</strong></div>{network.bottom3.map((item,index)=>{const s=findStore(item.store);return <button key={s.store} onClick={()=>setSelected(s)}><b>0{index+1}</b><span>{s.store}</span><em>{fmtMoney(s.netProfit)}</em><i>{s.netMargin.toFixed(1)}%</i></button>})}</div></div><div className="explorer"><div className="explorer-top"><div><span className="tiny-label">ИНТЕРАКТИВНЫЙ РЕЕСТР</span><h3>{network.storeCount} включенные точки</h3></div><div className="explorer-controls"><label className="search"><Search size={16}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Найти магазин"/></label><div className="filter-group">{([['all','Все'],['leaders','Выше сети'],['losses','Убыточные'],['at-risk','Риск']] as const).map(([value,label])=><button className={filter===value?"active":""} onClick={()=>setFilter(value)} key={value}>{label}</button>)}</div></div></div><div className="store-table-wrap"><table><thead><tr><th>Магазин</th><th>Выручка</th><th>Чистая прибыль</th><th>Маржа</th><th>Пик / провал</th><th>Главный резерв</th><th/></tr></thead><tbody>{filteredStores.map((store)=><tr key={store.store} onClick={()=>setSelected(store)} tabIndex={0} onKeyDown={(event)=>event.key==='Enter'&&setSelected(store)}><td><strong>{store.store}</strong>{store.lossMonths>0&&<small>{store.lossMonths} убыточн. мес.</small>}</td><td>{fmtMoney(store.revenue)}</td><td className={store.netProfit<0?"money-negative":"money-positive"}>{fmtMoney(store.netProfit)}</td><td><span className={store.netMargin<0?"margin-tag negative-tag":store.netMargin>=network.netMargin?"margin-tag positive-tag":"margin-tag"}>{store.netMargin.toFixed(1)}%</span></td><td>{store.bestMonth} / {store.worstMonth}</td><td><span className="reserve-name">{store.reserve}{store.reserveAmount>0&&<small>{fmtMoney(store.reserveAmount)}</small>}</span></td><td><ArrowDownRight size={17}/></td></tr>)}</tbody></table></div></div></section>
    <section className="section anomaly-section traced"><div className="audit-trail"><span>СИГНАЛ</span><i/><span>ПРИЧИНА</span><i/><span>ОТВЕТ</span></div><div className="anomaly-header"><p className="eyebrow">04 / АНОМАЛИИ</p><h2>Ловушки выручки и скрытые герои.</h2></div><div className="anomaly-grid">{revenueTraps.map((store)=><article className="anomaly-card danger" key={store.store}><span className="tiny-label">ЛОВУШКА ВЫРУЧКИ</span><h3>{store.store}</h3><div className="anomaly-kpis"><strong>{fmtMoney(store.revenue)}<small>выручка</small></strong><strong>{fmtMoney(store.netProfit)}<small>прибыль</small></strong><strong>{store.netMargin.toFixed(1)}%<small>маржа</small></strong></div><p>{store.reserve} выше медианной доли выручки на <b>{fmtMoney(store.reserveAmount)}</b>. {store.narrative}</p></article>)}{heroes.slice(0,1).map((store)=><article className="anomaly-card hero-card" key={store.store}><span className="tiny-label">СКРЫТЫЙ ГЕРОЙ</span><h3>{store.store}</h3><div className="anomaly-kpis"><strong>{fmtMoney(store.revenue)}<small>выручка</small></strong><strong>{fmtMoney(store.netProfit)}<small>прибыль</small></strong><strong>{store.netMargin.toFixed(1)}%<small>маржа</small></strong></div><p>Выручка ниже медианы, но точка держит чистую маржу в верхней трети. Разобрать SKU-матрицу, смены и закупочные условия для переноса практики.</p></article>)}</div></section>
    <section id="plan" className="section plan-section traced"><div className="audit-trail"><span>РЕШЕНИЕ</span><i/><span>РЕЗЕРВ</span><i/><span>СРОК</span></div><div className="plan-lead"><p className="eyebrow">05 / ACTION PLAN</p><h2>Решения в первые 45 дней.</h2><p>Программа задает денежную развилку для каждой убыточной точки: владелец подтверждает эффект в рублях через weekly P&amp;L, иначе инициируется релокация или закрытие.</p><div className="audit-checks">{auditChecks.map(([label,value])=><div key={label}><CheckCircle2 size={16}/><span>{label}</span><strong>{value}</strong></div>)}</div></div><div className="action-list">{actionPlan.slice(0,8).map((item,index)=><article key={item.point}><span>0{index+1}</span><div><h3>{item.point}</h3><p>{item.action}</p></div><em>{item.reserve}</em><b>{item.target}<small>резерв {item.reserveAmount}</small></b></article>)}</div></section>
    <section className="source-section"><div><p className="eyebrow">ПРОВЕРЕННЫЙ ИСТОЧНИК</p><h2>Формулы корректны.<br/>Риск — в экономике точек.</h2></div><p>Проверено 264 P&amp;L-блока за январь–август и 310 723 формульные ячейки полного файла. Ошибки и расхождения после независимого пересчета выше 0,15 ₽ не выявлены. Источник — исправленный 2026.xlsx.</p><a href="#top">Наверх <ArrowUpRight size={18}/></a></section>
    <footer><span>AuditLine · Супер-отчет по прибыли магазинов</span><span>Источник: 2026.xlsx · Январь–август 2026 · без КА1, АЛА, МОЛ и РЕЗ*</span></footer>{selected&&<StoreDrawer store={selected} onClose={()=>setSelected(null)}/>}</main>;
}
