/** AuditLine design: warm-paper investment memorandum; spruce for profit, cinnabar for risk. */
import { useMemo, useState } from "react";
import { Area, AreaChart, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowDownRight, ArrowUpRight, CheckCircle2, Copy, Download, Menu, Search, ShieldCheck, X } from "lucide-react";
import { actionPlan, auditChecks, costData, inventoryData, monthlyData, network, stores, type StoreProfile } from "@/data/auditData";

const heroImage = "/manus-storage/auditline-hero-2026_94861469.jpg";
const logoImage = "/manus-storage/auditline-logo_846ed825.png";
const money = (n: number, d = 1) => `${n.toLocaleString("ru-RU", { minimumFractionDigits: d, maximumFractionDigits: d })} млн ₽`;
const selectedStore = (name: string) => stores.find((item) => item.store === name)!;

function Drawer({ item, close }: { item: StoreProfile; close: () => void }) {
  const bad = item.netProfit < 0;
  return <div className="drawer-overlay" onClick={close} role="presentation"><aside className="store-drawer" onClick={(event) => event.stopPropagation()} aria-label={`Профиль магазина ${item.store}`}>
    <button className="icon-button" onClick={close} aria-label="Закрыть"><X size={22}/></button>
    <p className="eyebrow">ИНДИВИДУАЛЬНЫЙ ПРОФИЛЬ · РАНГ {item.profitRank} ИЗ {network.storeCount}</p><h2>{item.store}</h2>
    <div className={`drawer-outcome ${bad ? "negative" : "positive"}`}><span>Чистая прибыль</span><strong>{money(item.netProfit)}</strong><em>{item.netMargin.toFixed(1)}% чистая маржа · сеть {network.netMargin.toFixed(1)}%</em></div>
    <div style={{borderTop:"1px solid #d8d0c0",borderBottom:"1px solid #d8d0c0",margin:"18px 0",padding:"14px 0"}}><span className="tiny-label">ДИНАМИКА ЧИСТОЙ ПРИБЫЛИ · МЛН ₽</span><ResponsiveContainer width="100%" height={155}><LineChart data={item.monthlyProfit} margin={{top:14,right:8,left:-25,bottom:0}}><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fill:"#6b6964",fontSize:10}}/><YAxis axisLine={false} tickLine={false} tick={{fill:"#6b6964",fontSize:10}}/><Tooltip contentStyle={{border:"1px solid #d8d0c0",borderRadius:0,background:"#fbf7ef"}} formatter={(v:number)=>[money(v,2),"Прибыль"]}/><Line type="monotone" dataKey="profit" stroke={bad ? "#b6453d" : "#145b44"} strokeWidth={2.6} dot={{r:3}}/></LineChart></ResponsiveContainer></div>
    <dl className="drawer-list"><div><dt>Выручка</dt><dd>{money(item.revenue)}</dd></div><div><dt>Валовая маржа</dt><dd>{item.grossMargin.toFixed(1)}%</dd></div><div><dt>Лучший / худший месяц</dt><dd>{item.bestMonth} / {item.worstMonth}</dd></div><div><dt>Убыточных месяцев</dt><dd>{item.lossMonths}</dd></div><div><dt>Главный резерв</dt><dd>{item.reserve}</dd></div><div><dt>Резерв к медиане</dt><dd>{item.reserveAmount ? money(item.reserveAmount) : "Не выявлен"}</dd></div><div><dt>Эффект на остаток</dt><dd className={item.inventoryEffect < 0 ? "money-negative" : "money-positive"}>{money(item.inventoryEffect,2)}</dd></div></dl>
    <div className="drawer-callout"><ShieldCheck size={20}/><p>{item.narrative}</p></div>
  </aside></div>;
}

export default function Home() {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState<"all"|"above"|"loss"|"risk">("all");
  const [focus, setFocus] = useState<StoreProfile|null>(null); const [menuOpen, setMenuOpen] = useState(false); const [copied, setCopied] = useState(false);
  const rows = useMemo(() => stores.filter((item) => item.store.toLowerCase().includes(query.toLowerCase()) && (filter === "all" || filter === "above" && item.netMargin >= network.netMargin || filter === "loss" && item.netProfit < 0 || filter === "risk" && item.netProfit >= 0 && item.netMargin < 2)).sort((a,b) => b.netProfit-a.netProfit),[query,filter]);
  const traps = stores.filter((item) => item.revenue >= 16 && item.netMargin < 2).slice(0,3); const heroes = stores.filter((item) => item.revenue < 17 && item.netMargin >= 5 && item.netProfit > 0).slice(0,2);
  const share = async () => { await navigator.clipboard?.writeText(window.location.href); setCopied(true); setTimeout(() => setCopied(false), 1600); };
  return <main className="audit-page">
    <header className="topbar"><a className="brand" href="#top"><img src={logoImage} alt=""/><span>AuditLine</span></a><nav className={menuOpen?"nav nav-open":"nav"}><a href="#dynamics">Динамика</a><a href="#portfolio">Портфель</a><a href="#plan">Действия</a></nav><div className="topbar-actions"><button className="share-button" onClick={share}><Copy size={15}/>{copied?"Ссылка скопирована":"Поделиться"}</button><button className="print-button" onClick={()=>window.print()}><Download size={15}/>Сохранить</button><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)}><Menu size={20}/></button></div></header>
    <aside className="report-spine"><a href="#top" className="spine-mark"><img src={logoImage} alt=""/><span>AL</span></a><div className="spine-rule"/><nav className="spine-nav"><a href="#top"><b>00</b><span>Сводка</span></a><a href="#dynamics"><b>01</b><span>Динамика</span></a><a href="#portfolio"><b>03</b><span>Портфель</span></a><a href="#plan"><b>05</b><span>Действия</span></a></nav><div className="spine-period"><span>ПЕРИОД</span><strong>2026</strong><small>ЯНВ–АВГ</small></div></aside>
    <section id="top" className="hero"><img className="hero-photo" src={heroImage} alt="Аналитические материалы и график"/><div className="hero-content"><p className="eyebrow">РИТЕЙЛ-СЕТЬ · РАСШИРЕННЫЙ АУДИТ · ЯНВ–АВГ 2026</p><h1>Прибыль есть.<br/><em>Устойчивость — под вопросом.</em></h1><p className="hero-lede">Очищенная сеть заработала <strong>{money(network.netProfit)}</strong> при выручке <strong>{money(network.revenue)}</strong>. В этом отчете — отдельный графический профиль каждой из {network.storeCount} точек.</p><a className="hero-link" href="#portfolio">Открыть портфель <ArrowDownRight size={18}/></a></div><div className="hero-note"><span>Период</span><strong>Январь–август 2026</strong><small>Без КА1, АЛА, МОЛ, С2 и РЕЗ*</small></div></section>
    <section className="metrics-strip"><article className="metric"><p>Выручка</p><strong>{money(network.revenue)}</strong><span>включенная база</span></article><article className="metric"><p>Валовая прибыль</p><strong>{money(network.grossProfit)}</strong><span>маржа {(network.grossProfit/network.revenue*100).toFixed(1)}%</span></article><article className="metric"><p>Чистая прибыль</p><strong>{money(network.netProfit)}</strong><span>маржа {network.netMargin.toFixed(1)}%</span></article><article className="metric metric-risk"><p>Убыточные точки</p><strong>{network.lossCount} из {network.storeCount}</strong><span>потери {money(network.losses)}</span></article></section>
    <section id="dynamics" className="section feature-grid traced"><div className="audit-trail"><span>ФАКТ</span><i/><span>РИСК</span><i/><span>ДЕЙСТВИЕ</span></div><div className="section-intro"><p className="eyebrow">01 / ДИНАМИКА СЕТИ</p><h2>Продажи не гарантируют прибыль.</h2><p>Максимум прибыли пришелся на {network.peak.month}: {money(network.peak.net_profit/1_000_000)}. Минимум — {network.trough.month}: {money(network.trough.net_profit/1_000_000)}. Падение маржи в мае–июле требует контроля закупок, уценки и ФОТ.</p><div className="signal-list"><div><ArrowDownRight/><span>Провал <strong>{network.trough.month}</strong><small>{(network.trough.net_margin*100).toFixed(1)}% чистая маржа</small></span></div><div><ArrowUpRight/><span>Пик <strong>{network.peak.month}</strong><small>{(network.peak.net_margin*100).toFixed(1)}% чистая маржа</small></span></div></div></div><div className="chart-panel trend-panel"><div className="panel-heading"><div><span className="tiny-label">ФАКТ ПО МЕСЯЦАМ</span><h3>Выручка и чистая прибыль</h3></div><span>млн ₽</span></div><ResponsiveContainer width="100%" height={310}><AreaChart data={monthlyData} margin={{top:16,right:6,left:-20,bottom:0}}><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis yAxisId="a" axisLine={false} tickLine={false}/><YAxis yAxisId="b" orientation="right" axisLine={false} tickLine={false}/><Tooltip/><Area yAxisId="a" type="monotone" dataKey="revenue" name="Выручка" stroke="#145b44" strokeWidth={2.5} fill="none"/><Area yAxisId="b" type="monotone" dataKey="profit" name="Чистая прибыль" stroke="#b6453d" strokeWidth={3} fill="#b6453d33"/></AreaChart></ResponsiveContainer></div></section>
    <section className="section cost-section traced"><div className="audit-trail"><span>ФАКТ</span><i/><span>ОСТАТОК</span><i/><span>РЫЧАГ</span></div><div className="cost-header"><p className="eyebrow">02 / СТРУКТУРА И РИСК</p><h2>После закупок главный рычаг — ФОТ.</h2></div><div className="cost-layout"><div className="chart-panel donut-panel"><ResponsiveContainer width="100%" height={305}><PieChart><Pie data={costData} dataKey="value" nameKey="name" cx="50%" cy="48%" innerRadius={70} outerRadius={112} stroke="none" paddingAngle={2}>{costData.map((item)=><Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip/><Legend verticalAlign="bottom" iconType="circle" wrapperStyle={{fontSize:12}}/></PieChart></ResponsiveContainer></div><div className="cost-ledger">{costData.map((item)=><div className="cost-row" key={item.name}><span><i style={{background:item.color}}/>{item.name}</span><strong>{money(item.value)}</strong><em>{(item.value/network.revenue*100).toFixed(1)}%</em></div>)}<p><strong>Товарный остаток:</strong> {inventoryData.map((item)=>`${item.name} ${item.value.toFixed(2)} млн`).join(" · ")}</p></div></div></section>
    <section id="portfolio" className="section portfolio-section traced"><div className="audit-trail"><span>СЕТЬ</span><i/><span>ТОЧКА</span><i/><span>РЕЗЕРВ</span></div><div className="portfolio-heading"><div><p className="eyebrow">03 / ПОРТФЕЛЬ МАГАЗИНОВ</p><h2>Открывайте графический профиль каждой точки.</h2></div><p>Топ-3 — ПОРТ, А2 и КИР1 — создают <strong>{network.topShare.toFixed(1)}%</strong> прибыли сети. В строке доступны P&amp;L, рейтинг, резерв, остаток и график прибыли за 8 месяцев.</p></div><div className="rankings"><div className="ranking-card leader-card"><div className="card-top"><span>ЛИДЕРЫ</span><strong className="positive">{money(network.top3.reduce((s,x)=>s+x.net_profit,0)/1_000_000)}</strong></div>{network.top3.map((x,i)=>{const s=selectedStore(x.store);return <button key={s.store} onClick={()=>setFocus(s)}><b>0{i+1}</b><span>{s.store}</span><em>{money(s.netProfit)}</em><i>{s.netMargin.toFixed(1)}%</i></button>})}</div><div className="ranking-card risk-card"><div className="card-top"><span>АНТИРЕЙТИНГ</span><strong className="negative">{money(network.bottom3.reduce((s,x)=>s+x.net_profit,0)/1_000_000)}</strong></div>{network.bottom3.map((x,i)=>{const s=selectedStore(x.store);return <button key={s.store} onClick={()=>setFocus(s)}><b>0{i+1}</b><span>{s.store}</span><em>{money(s.netProfit)}</em><i>{s.netMargin.toFixed(1)}%</i></button>})}</div></div><div className="explorer"><div className="explorer-top"><div><span className="tiny-label">ИНТЕРАКТИВНЫЙ РЕЕСТР</span><h3>{network.storeCount} профиля магазинов</h3></div><div className="explorer-controls"><label className="search"><Search size={16}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Найти магазин"/></label><div className="filter-group">{([['all','Все'],['above','Выше сети'],['loss','Убыточные'],['risk','Риск']] as const).map(([key,label])=><button key={key} className={filter===key?"active":""} onClick={()=>setFilter(key)}>{label}</button>)}</div></div></div><p style={{fontSize:"0.85rem",color:"#6b6964",margin:"0.8rem 0"}}>Нажмите на строку — откроется самостоятельная аналитическая карточка с помесячным графиком и сравнением с сетью.</p><div className="store-table-wrap"><table><thead><tr><th>Магазин</th><th>Ранг</th><th>Выручка</th><th>Чистая прибыль</th><th>Маржа</th><th>Пик / провал</th><th>Резерв</th></tr></thead><tbody>{rows.map((s)=><tr key={s.store} onClick={()=>setFocus(s)} tabIndex={0}><td><strong>{s.store}</strong>{s.lossMonths>0&&<small>{s.lossMonths} убыточн. мес.</small>}</td><td>#{s.profitRank}</td><td>{money(s.revenue)}</td><td className={s.netProfit<0?"money-negative":"money-positive"}>{money(s.netProfit)}</td><td><span className={s.netMargin<0?"margin-tag negative-tag":s.netMargin>=network.netMargin?"margin-tag positive-tag":"margin-tag"}>{s.netMargin.toFixed(1)}%</span></td><td>{s.bestMonth}/{s.worstMonth}</td><td>{s.reserve}<small>{money(s.reserveAmount)}</small></td></tr>)}</tbody></table></div></div></section>
    <section className="section anomaly-section traced"><div className="audit-trail"><span>СИГНАЛ</span><i/><span>ПРИЧИНА</span><i/><span>ОТВЕТ</span></div><div className="anomaly-header"><p className="eyebrow">04 / АНОМАЛИИ</p><h2>Ловушки выручки и скрытые герои.</h2></div><div className="anomaly-grid">{traps.map((s)=><article className="anomaly-card danger" key={s.store}><span className="tiny-label">ЛОВУШКА ВЫРУЧКИ</span><h3>{s.store}</h3><div className="anomaly-kpis"><strong>{money(s.revenue)}<small>выручка</small></strong><strong>{money(s.netProfit)}<small>прибыль</small></strong><strong>{s.netMargin.toFixed(1)}%<small>маржа</small></strong></div><p>{s.reserve} выше медианной доли на <b>{money(s.reserveAmount)}</b>.</p></article>)}{heroes.slice(0,1).map((s)=><article className="anomaly-card hero-card" key={s.store}><span className="tiny-label">СКРЫТЫЙ ГЕРОЙ</span><h3>{s.store}</h3><div className="anomaly-kpis"><strong>{money(s.revenue)}<small>выручка</small></strong><strong>{money(s.netProfit)}<small>прибыль</small></strong><strong>{s.netMargin.toFixed(1)}%<small>маржа</small></strong></div><p>Результат выше сети при выручке ниже медианы: использовать как источник ассортимента и сменной модели.</p></article>)}</div></section>
    <section id="plan" className="section plan-section traced"><div className="audit-trail"><span>РЕШЕНИЕ</span><i/><span>РЕЗЕРВ</span><i/><span>СРОК</span></div><div className="plan-lead"><p className="eyebrow">05 / ACTION PLAN</p><h2>Решения в первые 45 дней.</h2><div className="audit-checks">{auditChecks.map(([l,v])=><div key={l}><CheckCircle2 size={16}/><span>{l}</span><strong>{v}</strong></div>)}</div></div><div className="action-list">{actionPlan.slice(0,8).map((x,i)=><article key={x.point}><span>0{i+1}</span><div><h3>{x.point}</h3><p>{x.action}</p></div><em>{x.reserve}</em><b>{x.target}<small>резерв {x.reserveAmount}</small></b></article>)}</div></section>
    <footer><span>AuditLine · Расширенный аудит прибыли</span><span>2026.xlsx · Январь–август · без КА1, АЛА, МОЛ, С2 и РЕЗ*</span></footer>{focus&&<Drawer item={focus} close={()=>setFocus(null)}/>}</main>;
}
