import { useEffect, useState } from "react";
import { Fingerprint, LockKeyhole } from "lucide-react";
import { browserSupportsPasskeys, startAuthentication } from "@simplewebauthn/browser";
import { toast } from "sonner";
import { PhoneInput } from "@/components/PhoneInput";
import { trpc } from "@/lib/trpc";
import { normalizeRussianPhone } from "@/lib/phone";

export default function Login(){const [phone,setPhone]=useState("");const [password,setPassword]=useState("");const [passkeySupported,setPasskeySupported]=useState(false);const utils=trpc.useUtils();const login=trpc.localAuth.login.useMutation({onSuccess:result=>{sessionStorage.removeItem(`audit-critical-signals-${result.id}`);utils.localAuth.me.invalidate()}});const beginPasskey=trpc.localAuth.beginPasskeyLogin.useMutation();const finishPasskey=trpc.localAuth.finishPasskeyLogin.useMutation({onSuccess:result=>{sessionStorage.removeItem(`audit-critical-signals-${result.id}`);utils.localAuth.me.invalidate()}});useEffect(()=>{browserSupportsPasskeys().then(setPasskeySupported).catch(()=>setPasskeySupported(false))},[]);const submit=(event:React.FormEvent)=>{event.preventDefault();login.mutate({username:normalizeRussianPhone(phone),password})};const fastLogin=async()=>{try{const normalized=normalizeRussianPhone(phone);const {options}=await beginPasskey.mutateAsync({phone:normalized});const response=await startAuthentication({optionsJSON:options});await finishPasskey.mutateAsync({phone:normalized,response});toast.success("Вход подтвержден") }catch(error){const message=error instanceof Error?error.message:"Не удалось подтвердить быстрый вход";if(message!=="The operation either timed out or was not allowed.")toast.error(message)}};const passkeyBusy=beginPasskey.isPending||finishPasskey.isPending;return <main className="login-gate"><section className="login-panel"><div className="login-mark"><img src="/manus-storage/profit_contour_logo_1c7249cd.png" alt="Контур Прибыли"/><span>Контур Прибыли</span></div><h1>Вход в управленческий контур</h1><p>Введите номер телефона и пароль. Доступ к показателям сети предоставляется только для назначенных магазинов и действий вашей роли.</p><form onSubmit={submit}><label>Номер телефона<PhoneInput value={phone} onValueChange={setPhone} required/></label><label>Пароль<input type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} required/></label>{login.error&&<div className="login-error">{login.error.message==="Требуется локальный вход"?"Сессия истекла. Введите номер телефона и пароль повторно.":login.error.message}</div>}<button className="login-submit" disabled={login.isPending}><LockKeyhole size={16}/>{login.isPending?"Проверяем доступ…":"Войти"}</button>{passkeySupported&&<button type="button" className="login-passkey" onClick={fastLogin} disabled={passkeyBusy||!phone}><Fingerprint size={17}/>{passkeyBusy?"Подтвердите на устройстве…":"Войти по Face ID / биометрии"}</button>}</form><small>{passkeySupported?"Быстрый вход доступен после его включения в профиле и использует Face ID, биометрию или PIN устройства.":"Можно начать ввод с 9, 7 или 8 — система приведет номер к виду +7 (900) 000-00-00. Скобки и дефисы не блокируют удаление цифр."}</small></section></main>}
