/** Universal month-by-month comparison of all P&L, product, expense and inventory metrics. */
import { useMemo, useState } from "react";
import { AuditShell } from "@/components/AuditShell";
import { MetricLineChart, formatK, formatPct } from "@/components/AuditCharts";
import { monthlyByStore, monthlyMetricDefinitions, monthlyNetwork } from "@/data/monthlyComparisonData";

const groups = { pnl:"P&L", product:"Товарный поток", pricing:"Наценка", expense:"Расходы", inventory:"Остатки и списания" } as const;
type Row = Record<string, string | number>;

export default function MonthlyComparison(){
  const [store,setStore]=useState<string>(Object.keys(monthlyByStore)[0]); const [metric,setMetric]=useState<string>("revenue");
  const definition=monthlyMetricDefinitions.find((item)=>item.field===metric) ?? monthlyMetricDefinitions[0]; const percent=definition.unit==="percent";
  const storeRows=(monthlyByStore[store as keyof typeof monthlyByStore] as unknown as Row[]); const networkRows=monthlyNetwork as unknown as Row[];
  const chart=useMemo(()=>storeRows.map((row,index)=>{const networkRow=networkRows[index];return {month:String(row.month),"Магазин":Number(row[metric]??0),"Медиана":Number(networkRow[`${metric}Median`]??0),"Сеть":Number(networkRow[metric]??0)}}),[storeRows,networkRows,metric]);
  return <AuditShell kicker="01 / УНИВЕРСАЛЬНОЕ СРАВНЕНИЕ" title="Месяцы: сеть и магазин"><section className="page-lede"><div><h2>Любая статья — по каждому месяцу.</h2><p>Выберите точку и показатель: P&L, закупки/продажи Коп. и Мор., наценка, любая расходная статья, остаток или списания. Детальные значения — <b>тыс. ₽</b>; проценты — для маржи и наценки.</p></div><div className="page-controls"><label>Магазин<select value={store} onChange={e=>setStore(e.target.value)}>{Object.keys(monthlyByStore).map(name=><option key={name}>{name}</option>)}</select></label><label>Показатель<select value={metric} onChange={e=>setMetric(e.target.value)}>{Object.entries(groups).map(([id,label])=><optgroup key={id} label={label}>{monthlyMetricDefinitions.filter(item=>item.group===id).map(item=><option key={item.field} value={item.field}>{item.label}</option>)}</optgroup>)}</select></label></div></section><section className="packet-split"><article className="packet-card wide"><div className="card-title"><div><span>{definition.group.toUpperCase()} · {definition.label}</span><h3>{store}: динамика против месячной медианы</h3></div><small>{percent?"%":"тыс. ₽"}</small></div><MetricLineChart data={chart} percent={percent} lines={[{key:"Магазин",name:store,color:"#155b45"},{key:"Медиана",name:"Медиана 32 точек",color:"#b74835"}]}/></article><article className="packet-card"><div className="card-title"><div><span>СЕТЬ</span><h3>Совокупная динамика</h3></div><small>{percent?"%":"тыс. ₽"}</small></div><MetricLineChart data={chart} percent={percent} lines={[{key:"Сеть",name:"Сеть",color:"#344a41"}]}/><p className="packet-note">Сеть — сумма показателя по 32 точкам; для % используется взвешенный результат сети. Медиана — типичная точка данного месяца.</p></article></section><section className="packet-card"><div className="card-title"><div><span>ТАБЛИЦА СРАВНЕНИЯ</span><h3>{definition.label}: все восемь месяцев</h3></div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Месяц</th><th>{store}</th><th>Медиана точки</th><th>Отклонение</th><th>Сеть</th></tr></thead><tbody>{chart.map(row=>{const delta=row["Магазин"]-row["Медиана"];const display=(v:number)=>percent?formatPct(v):formatK(v);return <tr key={row.month}><td>{row.month}</td><td>{display(row["Магазин"])}</td><td>{display(row["Медиана"])}</td><td className={delta>0?"positive":"negative"}>{delta>0?"+":""}{display(delta)}</td><td>{display(row["Сеть"])}</td></tr>})}</tbody></table></div></section></AuditShell>
}
