import { useEffect, useState } from "react";
import { CartesianGrid, Cell, LabelList, ReferenceLine, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from "recharts";
import { FileSpreadsheet, Maximize2 } from "lucide-react";
import { AuditShell } from "@/components/AuditShell";
import { ChartPanZoomSurface, formatK, formatPct, type ChartViewport, viewportChartDomain, windowChartRows } from "@/components/AuditCharts";
import { FactsLoader } from "@/components/OceanLoader";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useAudit } from "@/contexts/AuditContext";
import { useAuditFacts } from "@/hooks/useAuditFacts";

type CoverageRange = "all" | "low" | "normal" | "high";
type ChartKind = "revenue" | "cover" | "stock" | "writeoffs";
type PortfolioPoint = { store: string; revenue: number; netMargin: number; netProfit: number; cover: number; stock: number; writeoffSmoked: number; writeoffFrozen: number; writeoffs: number; label?: string };
type PriorityThresholds = { margin: number; lowCover: number; highCover: number };
type ScatterEventState = { activePayload?: Array<{ payload?: PortfolioPoint }> };
type ScatterMarkProps = { cx?: number; cy?: number; payload?: PortfolioPoint; fill?: string; stroke?: string; strokeWidth?: number; fillOpacity?: number };
const priorityThresholdStorageKey = "audit-portfolio-priority-thresholds";
const defaultPriorityThresholds: PriorityThresholds = { margin: 0, lowCover: 7, highCover: 20 };
const readPriorityThresholds = (): PriorityThresholds => { try { const stored = JSON.parse(localStorage.getItem(priorityThresholdStorageKey) ?? "null") as Partial<PriorityThresholds> | null; const margin = Number(stored?.margin); const lowCover = Number(stored?.lowCover); const highCover = Number(stored?.highCover); const normalizedLow = Number.isFinite(lowCover) ? Math.max(0, lowCover) : defaultPriorityThresholds.lowCover; return { margin: Number.isFinite(margin) ? margin : defaultPriorityThresholds.margin, lowCover: normalizedLow, highCover: Number.isFinite(highCover) ? Math.max(normalizedLow + 1, highCover) : defaultPriorityThresholds.highCover }; } catch { return defaultPriorityThresholds; } };

const money = (amount: number) => formatK(amount / 1000);
const median = (values: number[]) => { const sorted = [...values].sort((a, b) => a - b); const middle = Math.floor(sorted.length / 2); return sorted.length ? (sorted.length % 2 ? sorted[middle] : (sorted[middle - 1] + sorted[middle]) / 2) : 0; };
const isRiskPoint = (item: PortfolioPoint, thresholds: PriorityThresholds) => item.netMargin < thresholds.margin || item.cover < thresholds.lowCover || item.cover > thresholds.highCover;
const priorityScore = (item: PortfolioPoint, thresholds: PriorityThresholds) => (item.netMargin < thresholds.margin ? 100 + Math.max(0, thresholds.margin - item.netMargin) * 100 : 0) + (item.cover > thresholds.highCover ? 50 + item.cover - thresholds.highCover : 0) + (item.cover < thresholds.lowCover ? 45 + (thresholds.lowCover - item.cover) : 0);
const priorityReason = (item: PortfolioPoint, thresholds: PriorityThresholds) => { const reasons: string[] = []; if (item.netMargin < thresholds.margin) reasons.push(`маржа ниже ${formatPct(thresholds.margin)}`); if (item.cover > thresholds.highCover) reasons.push("избыток запаса"); if (item.cover < thresholds.lowCover) reasons.push("дефицит запаса"); return reasons.length ? reasons.join(" · ") : "контроль динамики"; };
const signal = (item: PortfolioPoint, thresholds: PriorityThresholds) => item.cover > thresholds.highCover ? "Сократить закупку, проверить уценку и списания" : item.cover < thresholds.lowCover ? "Проверить наличие ходовых SKU и страховой запас" : item.netMargin < thresholds.margin ? "Разобрать закупку, ФОТ и аренду до решения по точке" : "Контролировать динамику и не ухудшать запас";
const chartTitle = (kind: ChartKind) => kind === "revenue" ? "Выручка и чистая маржа" : kind === "cover" ? "Покрытие и прибыльность" : kind === "stock" ? "Остаток и чистая маржа" : "Списания и чистая маржа";
const chartKicker = (kind: ChartKind) => kind === "revenue" ? "МАСШТАБ × МАРЖА" : kind === "cover" ? "ЗАПАС × МАРЖА" : kind === "stock" ? "ОСТАТОК × МАРЖА" : "СПИСАНИЯ × МАРЖА";

function PortfolioTooltip({ active, payload, thresholds }: { active?: boolean; payload?: Array<{ payload: PortfolioPoint }>; thresholds: PriorityThresholds }) { if (!active || !payload?.[0]) return null; const point = payload[0].payload; return <div className="tiny-tooltip portfolio-tooltip"><b>{point.store}</b><span>Выручка: <strong>{money(point.revenue)}</strong></span><span>Покрытие: <strong>{point.cover.toFixed(1)} дн.</strong></span><span>Маржа: <strong>{formatPct(point.netMargin)}</strong></span><span>Фокус: <strong>{priorityReason(point, thresholds)}</strong></span></div>; }

export default function Portfolio() {
  const facts = useAuditFacts();
  const { rangeLabel, theme } = useAudit();
  const [coverageRange, setCoverageRange] = useState<CoverageRange>("all");
  const [focusedStore, setFocusedStore] = useState("");
  const [hoveredStore, setHoveredStore] = useState("");
  const [expandedChart, setExpandedChart] = useState<ChartKind | null>(null);
  const [priorityThresholds, setPriorityThresholds] = useState<PriorityThresholds>(readPriorityThresholds);
  const palette = theme === "light" ? { grid: "#d8e0ea", axis: "#61718a", reference: "#0a84ff", negative: "#d70036", high: "#b86712", low: "#08745d", normal: "#6978d5", focus: "#0a63c8", label: "#33435a" } : { grid: "#3a2031", axis: "#b490a2", reference: "#ffcf7b", negative: "#ff8ba4", high: "#ffcf7b", low: "#61d9b5", normal: "#a8b2ff", focus: "#ff947f", label: "#ffdce5" };
  const map: PortfolioPoint[] = facts.summaries.map(summary => ({ store: summary.store, revenue: summary.revenue, netMargin: summary.netMargin, netProfit: summary.netProfit, cover: summary.coverDays, stock: summary.stockClose, writeoffSmoked: summary.writeoffSmoked, writeoffFrozen: summary.writeoffFrozen, writeoffs: summary.writeoffFrozen + summary.writeoffSmoked }));
  const medianRevenue = median(map.map(item => item.revenue)); const medianCover = median(map.map(item => item.cover)); const medianStock = median(map.map(item => item.stock)); const medianWriteoffs = median(map.map(item => item.writeoffs));
  const mediansByChart: Record<ChartKind, number> = { revenue: medianRevenue, cover: medianCover, stock: medianStock, writeoffs: medianWriteoffs };
  useEffect(() => { localStorage.setItem(priorityThresholdStorageKey, JSON.stringify(priorityThresholds)); }, [priorityThresholds]);
  const visible = map.filter(item => coverageRange === "all" || (coverageRange === "low" ? item.cover < priorityThresholds.lowCover : coverageRange === "normal" ? item.cover >= priorityThresholds.lowCover && item.cover <= priorityThresholds.highCover : item.cover > priorityThresholds.highCover));
  const low = map.filter(item => item.cover < priorityThresholds.lowCover); const high = map.filter(item => item.cover > priorityThresholds.highCover); const risk = map.filter(item => isRiskPoint(item, priorityThresholds)); const priority = [...visible].filter(item => isRiskPoint(item, priorityThresholds)).sort((a, b) => priorityScore(b, priorityThresholds) - priorityScore(a, priorityThresholds));
  const selectedFocus = visible.some(item => item.store === focusedStore) ? focusedStore : ""; const focus = visible.find(item => item.store === selectedFocus) ?? priority[0] ?? visible[0];
  const labelledStores = new Set(priority.slice(0, 6).map(item => item.store)); if (focus) labelledStores.add(focus.store);
  const scatterData = visible.map(item => ({ ...item, label: labelledStores.has(item.store) ? item.store : "" })); const priorityPoints = (priority.length ? priority : [...visible].sort((a, b) => b.revenue - a.revenue)).slice(0, 6);
  const pointColor = (item: PortfolioPoint) => item.netMargin < priorityThresholds.margin ? palette.negative : item.cover > priorityThresholds.highCover ? palette.high : item.cover < priorityThresholds.lowCover ? palette.low : palette.normal;
  const marginWidth = (margin: number) => Math.max(4, Math.min(100, 50 + margin * 250)); const coverWidth = (cover: number) => Math.max(4, Math.min(100, cover * 2.5));
  const adjustPriorityThreshold = (field: keyof PriorityThresholds, delta: number) => setPriorityThresholds(current => { if (field === "lowCover") return { ...current, lowCover: Math.max(0, Math.min(current.lowCover + delta, current.highCover - 1)) }; if (field === "highCover") return { ...current, highCover: Math.max(current.lowCover + 1, current.highCover + delta) }; return { ...current, margin: Math.round((current.margin + delta) * 10) / 10 }; });
  const selectScatterPoint = (state: unknown) => { const point = (state as ScatterEventState).activePayload?.[0]?.payload; if (point?.store) setFocusedStore(point.store); };
  const scatter = (kind: ChartKind, height = 510, viewport?: ChartViewport) => { const allPoints = scatterData; const xDomain = viewportChartDomain(allPoints.map(item => Number(item[kind])), viewport, "x", false); const yDomain = viewportChartDomain(allPoints.map(item => item.netMargin), viewport, "y", false); const chartData = allPoints.filter(item => { const x = Number(item[kind]); return x >= xDomain[0] && x <= xDomain[1] && item.netMargin >= yDomain[0] && item.netMargin <= yDomain[1]; }); return <ResponsiveContainer width="100%" height={height}><ScatterChart margin={{ top: 42, right: 28, bottom: 18, left: 14 }}><CartesianGrid stroke={palette.grid} strokeDasharray="3 3"/><XAxis type="number" dataKey={kind} domain={xDomain} allowDataOverflow tickCount={6} tickFormatter={value => kind === "cover" ? `${value} дн.` : money(value).replace(" ₽", "")} stroke={palette.axis} tick={{ fill: palette.axis, fontSize: 11 }}/><YAxis type="number" dataKey="netMargin" domain={yDomain} allowDataOverflow tickCount={5} tickFormatter={value => formatPct(value)} width={60} stroke={palette.axis} tick={{ fill: palette.axis, fontSize: 11 }}/><ReferenceLine x={mediansByChart[kind]} stroke={palette.reference} strokeDasharray="4 4"/><Tooltip content={<PortfolioTooltip thresholds={priorityThresholds}/>} cursor={false}/><Scatter data={chartData} isAnimationActive={false} shape={(props: ScatterMarkProps) => { const selected = props.payload?.store === focus?.store; const hovered = props.payload?.store === hoveredStore; const focusPoint = (event: React.MouseEvent<SVGGElement>) => { event.stopPropagation(); if (props.payload) setFocusedStore(props.payload.store); }; return <g data-chart-point="true" className="portfolio-scatter-point" onClick={focusPoint} onPointerEnter={() => props.payload && setHoveredStore(props.payload.store)} onPointerLeave={() => setHoveredStore("")}>{(selected || hovered) && <circle className={selected ? "portfolio-scatter-focus" : "portfolio-scatter-hover"} cx={props.cx} cy={props.cy} r={selected ? 12 : 9} fill="none" stroke={palette.focus} strokeWidth={1.5} strokeDasharray="3 3" pointerEvents="none"/>}<circle cx={props.cx} cy={props.cy} r={selected ? 7.5 : 5.5} fill={props.fill} fillOpacity={props.fillOpacity} stroke="none" strokeWidth={0}/></g>; }}>{chartData.map(item => <Cell key={`${kind}-${item.store}`} fill={pointColor(item)} fillOpacity={focus?.store && focus.store !== item.store ? .26 : 1} stroke="none" strokeWidth={0}/>) }<LabelList dataKey="label" position="top" fill={palette.label} fontSize={10} style={{pointerEvents:"none"}}/></Scatter></ScatterChart></ResponsiveContainer>; };

  return <AuditShell kicker="07 / ПОРТФЕЛЬ И РИСКИ" title="Портфель: прибыль, остаток, риск">{facts.loading ? <FactsLoader/> : !facts.available ? <section className="empty-state live-empty"><FileSpreadsheet size={30}/><h2>Нет данных для карты портфеля</h2><p>Карта будет построена из импортированных магазинов, периодов и остатков после первого импорта Excel.</p></section> : <>
    <section className="page-lede"><div><h2>Не рейтинг. Карта того, где деньги зарабатывают или застревают.</h2><p><b>Покрытие запаса</b> — дни обычных продаж, на которые хватит конечного остатка:<br/><b>конечный остаток ÷ средние продажи в день.</b><br/>Медиана <b>{medianCover.toFixed(1)} дня</b> — типичный уровень сети, а не плановый норматив.<br/>Срез: <b>{rangeLabel}</b>.</p></div><div className="page-controls"><label>Диапазон покрытия<select value={coverageRange} onChange={event => setCoverageRange(event.target.value as CoverageRange)}><option value="all">Все магазины</option><option value="low">Ниже {priorityThresholds.lowCover} дней</option><option value="normal">От {priorityThresholds.lowCover} до {priorityThresholds.highCover} дней</option><option value="high">Выше {priorityThresholds.highCover} дней</option></select></label></div></section>
    <section className="zone-grid"><article><span>Низкий запас</span><strong>&lt; {priorityThresholds.lowCover} дней</strong><p>{low.length} точек. Проверить риск отсутствия ходового товара.</p></article><article><span>Медиана сети</span><strong>{medianCover.toFixed(1)} дня</strong><p>Половина точек ниже, половина выше этого фактического уровня.</p></article><article><span>Высокий запас</span><strong>&gt; {priorityThresholds.highCover} дней</strong><p>{high.length} точек. Деньги в товаре: сверить закупку, уценку и списания.</p></article></section>
    <section className="packet-kpis equal"><article className="packet-kpi"><span>Медиана выручки</span><strong>{money(medianRevenue)}</strong><small>типичный масштаб точки</small></article><article className="packet-kpi"><span>Медиана покрытия</span><strong>{medianCover.toFixed(1)} дн.</strong><small>середина распределения</small></article><article className="packet-kpi"><span>Точек в зоне риска</span><strong>{risk.length}</strong><small>отрицательная маржа или запас вне 7—20 дней</small></article><article className="packet-kpi"><span>В выбранном диапазоне</span><strong>{visible.length}</strong><small>из {map.length} магазинов</small></article></section>
    <section className="packet-card portfolio-thresholds"><div className="card-title"><div><span>КРИТЕРИИ КАРТЫ ПРИОРИТЕТОВ</span><h3>Что попадет в первоочередный контроль</h3></div><small>сохраняются на этом устройстве</small></div><p className="portfolio-mobile-intro">Карта поднимает точки с маржой ниже порога и запасом вне заданного диапазона. Это правила подсветки и очередности проверки: финансовые факты и расчеты не меняются.</p><div className="portfolio-threshold-context"><span>Типичное покрытие сети</span><b>{medianCover.toFixed(1)} дн.</b><span>Точек в фокусе</span><b>{risk.length}</b></div><div className="portfolio-threshold-fields"><div className="threshold-stepper"><span>Маржа ниже</span><div><button type="button" aria-label="Уменьшить порог маржи" onClick={() => adjustPriorityThreshold("margin", -.5)}>−</button><b>{formatPct(priorityThresholds.margin)}</b><button type="button" aria-label="Увеличить порог маржи" onClick={() => adjustPriorityThreshold("margin", .5)}>+</button></div></div><div className="threshold-stepper"><span>Низкое покрытие</span><div><button type="button" aria-label="Уменьшить нижнюю границу покрытия" onClick={() => adjustPriorityThreshold("lowCover", -1)}>−</button><b>{priorityThresholds.lowCover} дн.</b><button type="button" aria-label="Увеличить нижнюю границу покрытия" onClick={() => adjustPriorityThreshold("lowCover", 1)}>+</button></div></div><div className="threshold-stepper"><span>Высокое покрытие</span><div><button type="button" aria-label="Уменьшить верхнюю границу покрытия" onClick={() => adjustPriorityThreshold("highCover", -1)}>−</button><b>{priorityThresholds.highCover} дн.</b><button type="button" aria-label="Увеличить верхнюю границу покрытия" onClick={() => adjustPriorityThreshold("highCover", 1)}>+</button></div></div></div></section>
    <section className="packet-card portfolio-focus-card"><div className="portfolio-focus-copy"><span>ФОКУС КАРТЫ</span><h3>{focus?.store ?? "Нет точек в выбранном диапазоне"}</h3><p>{focus ? `${priorityReason(focus, priorityThresholds)} · ${signal(focus, priorityThresholds)}` : "Измените диапазон покрытия, чтобы выбрать точку для анализа."}</p></div>{focus && <div className="portfolio-focus-metrics"><div><span>Выручка</span><b>{money(focus.revenue)}</b></div><div><span>Чистая маржа</span><b className={focus.netMargin < priorityThresholds.margin ? "negative" : "positive"}>{formatPct(focus.netMargin)}</b></div><div><span>Покрытие</span><b>{focus.cover.toFixed(1)} дн.</b></div><div><span>Списания К.+М.</span><b>{money(focus.writeoffs)}</b></div></div>}</section>
    <section className="portfolio-map-legend" aria-label="Легенда карт портфеля"><label className="portfolio-focus-select portfolio-focus-select-inline">Точка на графике<select value={selectedFocus} onChange={event => setFocusedStore(event.target.value)}><option value="">Авто: первая точка риска</option>{visible.map(item => <option value={item.store} key={item.store}>{item.store}</option>)}</select></label><div className="portfolio-map-legend-items"><span><i style={{background:palette.negative}}/>Маржа ниже {formatPct(priorityThresholds.margin)}</span><span><i style={{background:palette.high}}/>Запас выше {priorityThresholds.highCover} дней</span><span><i style={{background:palette.low}}/>Запас ниже {priorityThresholds.lowCover} дней</span><span><i style={{background:palette.normal}}/>Обычная точка: условий риска нет</span><span><i className="portfolio-focus-ring" style={{borderColor:palette.focus}}/>Фокус точки</span></div></section>
    <section className="packet-split portfolio-plot-grid">{(["revenue","cover","stock","writeoffs"] as const).map(kind => <article className="packet-card portfolio-scatter-card" key={kind}><div className="card-title"><div><span>{chartKicker(kind)}</span><h3>{chartTitle(kind)}</h3></div><div className="portfolio-chart-actions"><small>Медиана: {kind === "cover" ? `${mediansByChart[kind].toFixed(1)} дн.` : money(mediansByChart[kind])}</small><button type="button" className="chart-expand-button" onClick={() => setExpandedChart(kind)}><Maximize2 size={14}/><span>Увеличить</span></button></div></div><div className="portfolio-desktop-chart"><ChartPanZoomSurface compact invertX>{viewport=>scatter(kind,510,viewport)}</ChartPanZoomSurface></div></article>)}</section>
    <section className="packet-card portfolio-mobile-map"><div className="card-title"><div><span>КАРТА ПРИОРИТЕТОВ</span><h3>Точки, где действие требуется раньше</h3></div><small>до 6 точек</small></div><p className="portfolio-mobile-intro">Шесть точек с наивысшим приоритетом по заданным порогам маржи и покрытия запаса.</p><div className="portfolio-mobile-priority-list">{priorityPoints.map(item => <button type="button" key={item.store} className={focus?.store === item.store ? "portfolio-mobile-priority active" : "portfolio-mobile-priority"} onClick={() => setFocusedStore(item.store)}><div><b>{item.store}</b><span>{priorityReason(item, priorityThresholds)}</span></div><div className="portfolio-meter"><span>Маржа<i style={{width:`${marginWidth(item.netMargin)}%`,background:pointColor(item)}}/></span><span>Покрытие<i style={{width:`${coverWidth(item.cover)}%`,background:pointColor(item)}}/></span></div><div className="portfolio-mobile-values"><span className={item.netMargin < priorityThresholds.margin ? "negative" : "positive"}>{formatPct(item.netMargin)}</span><span>{item.cover.toFixed(1)} дн.</span><span>{money(item.revenue)}</span></div></button>)}</div></section>
    <section className="packet-card"><div className="card-title"><div><span>ВСЕ МАГАЗИНЫ · ЗАПАС И ЭКОНОМИКА</span><h3>Полный список: где смотреть в первую очередь</h3></div><small>фильтр: {visible.length} точек</small></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Магазин</th><th>Выручка</th><th>Чистая прибыль</th><th>Маржа</th><th>Остаток</th><th>Покрытие</th><th>Списания К.</th><th>Списания М.</th><th>Списания К.+М.</th><th>Действие</th></tr></thead><tbody>{[...visible].sort((a,b) => priorityScore(b, priorityThresholds)-priorityScore(a, priorityThresholds)||b.revenue-a.revenue).map(item => <tr key={item.store}><td>{item.store}</td><td>{money(item.revenue)}</td><td className={item.netProfit < 0 ? "negative" : "positive"}>{money(item.netProfit)}</td><td>{formatPct(item.netMargin)}</td><td>{money(item.stock)}</td><td>{item.cover.toFixed(1)} дн.</td><td>{money(item.writeoffSmoked)}</td><td>{money(item.writeoffFrozen)}</td><td>{money(item.writeoffs)}</td><td>{signal(item, priorityThresholds)}</td></tr>)}</tbody></table></div></section>
    <Dialog open={expandedChart!==null} onOpenChange={open => { if (!open) setExpandedChart(null); }}><DialogContent className="chart-expand-dialog portfolio-chart-dialog"><DialogHeader><DialogTitle>{expandedChart ? chartTitle(expandedChart) : "График"}</DialogTitle></DialogHeader>{expandedChart && <ChartPanZoomSurface invertX>{viewport => <div className="chart-expand-canvas">{scatter(expandedChart,620,viewport)}</div>}</ChartPanZoomSurface>}</DialogContent></Dialog>
  </>}</AuditShell>;
}
