/** Pricing control: two categories plus total commercial mix, with readable all-store benchmark. */
import { useMemo, useState } from "react";
import { AuditShell } from "@/components/AuditShell";
import { BenchmarkBars, MetricLineChart, formatK, formatPct } from "@/components/AuditCharts";
import { monthlyByStore } from "@/data/monthlyComparisonData";

type Category="smoked"|"frozen"|"all"; type Row=Record<string,string|number>;
const info:Record<Category,{title:string;sales:string;purchase:string;color:string}>={smoked:{title:"Копченая",sales:"sales_smoked",purchase:"purchase_smoked",color:"#ff6d8c"},frozen:{title:"Мороженая",sales:"sales_frozen",purchase:"purchase_frozen",color:"#b694ff"},all:{title:"Коп. + Мор.",sales:"sales_total",purchase:"purchase_total",color:"#ffcf7b"}};
const rowsFor=(store:string)=>monthlyByStore[store as keyof typeof monthlyByStore] as unknown as Row[] ?? [];
const value=(row:Row,field:string)=>field==="sales_total"?Number(row.sales_smoked??0)+Number(row.sales_frozen??0):field==="purchase_total"?Number(row.purchase_smoked??0)+Number(row.purchase_frozen??0):Number(row[field]??0);
const totals=(rows:Row[],category:Category):{sales:number;purchase:number}=>rows.reduce<{sales:number;purchase:number}>((memo,row)=>({sales:memo.sales+value(row,info[category].sales),purchase:memo.purchase+value(row,info[category].purchase)}),{sales:0,purchase:0});
const markup=(pair:{sales:number;purchase:number})=>pair.purchase?((pair.sales/pair.purchase)-1)*100:0;

export default function Pricing(){
 const names=Object.keys(monthlyByStore); const [store,setStore]=useState(names[0]); const [category,setCategory]=useState<Category>("all"); const source=rowsFor(store); const all=names.flatMap(rowsFor); const selected=totals(source,category); const network=totals(all,category); const market=useMemo(()=>names.map(name=>{const pair=totals(rowsFor(name),category);return {store:name,value:markup(pair),selected:name===store}}).sort((a,b)=>b.value-a.value),[store,category,names.join("|")]); const median=market[Math.floor(market.length/2)]?.value??0; const monthly=source.map(row=>({month:String(row.month),"Копченая":markup({sales:value(row,"sales_smoked"),purchase:value(row,"purchase_smoked")}),"Мороженая":markup({sales:value(row,"sales_frozen"),purchase:value(row,"purchase_frozen")}),"Всего":markup({sales:value(row,"sales_total"),purchase:value(row,"purchase_total")})}));
 return <AuditShell kicker="02 / ЦЕНОВОЙ АУДИТ" title="Цены: категории и общий товарный поток"><section className="page-lede"><div><h2>Смотрите наценку вместе с объемом и списаниями.</h2><p>Выберите категорию или общий поток <b>Коп. + Мор.</b>. Экран показывает, где ценовой коридор магазина отличается от типичной точки сети; это основание для проверки и пилота, а не автоматического изменения цены.</p></div><div className="page-controls"><label>Магазин<select value={store} onChange={e=>setStore(e.target.value)}>{names.map(name=><option key={name} value={name}>{name}</option>)}</select></label><label>Категория<select value={category} onChange={e=>setCategory(e.target.value as Category)}><option value="all">Коп. + Мор. (всего)</option><option value="smoked">Копченая</option><option value="frozen">Мороженая</option></select></label></div></section><section className="packet-kpis equal"><article className="packet-kpi"><span>Продажи · {store}</span><strong>{formatK(selected.sales)}</strong><small>сеть: {formatK(network.sales)}</small></article><article className="packet-kpi"><span>Закупки · {store}</span><strong>{formatK(selected.purchase)}</strong><small>сеть: {formatK(network.purchase)}</small></article><article className="packet-kpi"><span>Наценка · {store}</span><strong>{formatPct(markup(selected))}</strong><small>медиана сети: {formatPct(median)}</small></article><article className={(markup(selected)-median)<0?"packet-kpi risk":"packet-kpi"}><span>Отклонение от медианы</span><strong>{markup(selected)-median>0?"+":""}{formatPct(markup(selected)-median)}</strong><small>выбранный товарный поток</small></article></section><section className="packet-split"><article className="packet-card wide"><div className="card-title"><div><span>ЦЕНОВОЙ КОРИДОР · {info[category].title.toUpperCase()}</span><h3>Все 32 магазина по наценке</h3></div><small>%</small></div><BenchmarkBars data={market} median={median} selectedLabel={store}/></article><article className="packet-card"><div className="card-title"><div><span>ДИНАМИКА · {store}</span><h3>Наценка по месяцам</h3></div><small>%</small></div><MetricLineChart data={monthly} percent lines={[{key:"Копченая",name:"Копченая",color:"#ff6d8c"},{key:"Мороженая",name:"Мороженая",color:"#b694ff"},{key:"Всего",name:"Коп. + Мор.",color:"#ffcf7b"}]}/></article></section></AuditShell>
}
