import { BellRing, BellOff, Download, Share, Smartphone } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { AuditShell } from "@/components/AuditShell";
import { currentPushSubscription, pushSupported, subscribeToPush } from "@/lib/push";
import { trpc } from "@/lib/trpc";

type InstallPromptEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:"accepted"|"dismissed"}>};

export default function Profile(){
  const me=trpc.localAuth.me.useQuery();
  const push=trpc.localAuth.pushStatus.useQuery(undefined,{retry:false});
  const utils=trpc.useUtils();
  const [currentPassword,setCurrentPassword]=useState("");
  const [nextPassword,setNextPassword]=useState("");
  const [installPrompt,setInstallPrompt]=useState<InstallPromptEvent|null>(null);
  const standalone=typeof window!=="undefined"&&window.matchMedia("(display-mode: standalone)").matches;
  useEffect(()=>{const capture=(event:Event)=>{event.preventDefault();setInstallPrompt(event as InstallPromptEvent)};window.addEventListener("beforeinstallprompt",capture);return()=>window.removeEventListener("beforeinstallprompt",capture)},[]);
  const change=trpc.localAuth.changePassword.useMutation({onSuccess:()=>{setCurrentPassword("");setNextPassword("");toast.success("Пароль изменен")},onError:error=>toast.error(error.message)});
  const logout=trpc.localAuth.logout.useMutation({onSuccess:()=>window.location.reload()});
  const subscribe=trpc.localAuth.subscribePush.useMutation({onSuccess:()=>utils.localAuth.pushStatus.invalidate(),onError:error=>toast.error(error.message)});
  const unsubscribe=trpc.localAuth.unsubscribePush.useMutation({onSuccess:()=>utils.localAuth.pushStatus.invalidate(),onError:error=>toast.error(error.message)});
  const account=me.data; const isAdmin=account?.role==="admin";
  const enablePush=async()=>{try{if(!push.data?.configured||!push.data.publicKey){toast.info("Телефонные уведомления еще настраиваются на сервере");return}const subscription=await subscribeToPush(push.data.publicKey);await subscribe.mutateAsync(subscription.toJSON() as {endpoint:string;keys:{p256dh:string;auth:string}});toast.success("Телефонные уведомления включены") }catch(error){toast.error(error instanceof Error?error.message:"Не удалось включить уведомления")}};
  const disablePush=async()=>{try{const subscription=await currentPushSubscription();await unsubscribe.mutateAsync({endpoint:subscription?.endpoint});await subscription?.unsubscribe();toast.success("Телефонные уведомления отключены") }catch(error){toast.error(error instanceof Error?error.message:"Не удалось отключить уведомления")}};
  const install=async()=>{if(!installPrompt){toast.info("На iPhone: Поделиться → На экран «Домой». На Android откройте меню браузера и выберите «Установить приложение».");return}await installPrompt.prompt();const choice=await installPrompt.userChoice;if(choice.outcome==="accepted")toast.success("Приложение добавлено на экран");setInstallPrompt(null)};
  return <AuditShell kicker="14 / ПРОФИЛЬ" title="Профиль и безопасность"><section className="page-lede"><div><span>ЛОКАЛЬНАЯ УЧЕТНАЯ ЗАПИСЬ</span><h2>Профиль доступа</h2><p>Здесь можно изменить пароль, настроить телефонные уведомления и завершить текущую сессию. Администратор управляет системой целиком; аналитик видит только назначенные ему магазины.</p></div></section><section className="access-grid"><article className="packet-card"><span className="card-eyebrow">ТЕКУЩАЯ РОЛЬ</span><h3>{isAdmin?"Администратор":"Аналитик"}</h3><p>Номер телефона: <strong>{account?.phone??"—"}</strong></p><p className="packet-note">{isAdmin?"Доступ ко всем магазинам, импорту, базе, журналу и настройке пользователей.":"Доступ к каждому магазину задается отдельно: «Просмотр» или «Редактирование»."}</p><button className="subtle-button" onClick={()=>logout.mutate()}>Выйти из системы</button></article><article className="packet-card"><span className="card-eyebrow">СМЕНА ПАРОЛЯ</span><form className="stack-form" onSubmit={event=>{event.preventDefault();change.mutate({currentPassword,nextPassword})}}><label>Текущий пароль<input type="password" value={currentPassword} onChange={event=>setCurrentPassword(event.target.value)} required/></label><label>Новый пароль<input type="password" value={nextPassword} onChange={event=>setNextPassword(event.target.value)} minLength={10} required/></label>{change.error&&<p className="inline-error">{change.error.message}</p>}<button className="packet-link compact" disabled={change.isPending}>Сохранить пароль</button></form></article></section><section className="packet-card push-settings"><div><span className="card-eyebrow">ПРИЛОЖЕНИЕ И УВЕДОМЛЕНИЯ</span><h3>На экране телефона</h3><p>Установите «Аналитику Магазинов» как приложение, затем по желанию включите критичные сигналы и новые управленческие отчеты.</p></div><div className="push-settings-action"><button className="subtle-button" onClick={install} disabled={standalone}>{standalone?<Smartphone size={16}/>:installPrompt?<Download size={16}/>:<Share size={16}/>} {standalone?"Уже установлено":installPrompt?"Установить приложение":"Как добавить на экран"}</button>{!pushSupported()?<small>Этот браузер не поддерживает Web Push.</small>:push.data?.enabled?<><span><BellRing size={17}/> Включены на этом устройстве</span><button className="subtle-button" onClick={disablePush} disabled={unsubscribe.isPending}><BellOff size={16}/>Отключить</button></>:<><span><Smartphone size={17}/>{push.data?.configured?"Разрешение еще не выдано":"Серверная настройка ожидается"}</span><button className="packet-link compact" onClick={enablePush} disabled={!push.data?.configured||subscribe.isPending}><BellRing size={16}/>Включить</button></>}</div></section></AuditShell>;
}
