import * as XLSX from "xlsx";
import { and, eq, inArray } from "drizzle-orm";
import { imports, metrics, periods, stores } from "../drizzle/schema";
import { getDb } from "./db";
import { storagePut } from "./storage";

const MONTHS=["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"];
const MONTH_NUM=Object.fromEntries(MONTHS.map((m,index)=>[m,index+1]));
const columns:Record<string,string>={purchases:"G",revenue:"H",gross_profit:"L",cash_revenue:"M",cashless_revenue:"N",receipts_total:"O",writeoff_smoked:"P",writeoff_frozen:"Q",movement:"R",discount:"S",revaluation:"T",cash_operating_costs:"AD",driver_cash:"AE",utilities_cash:"AF",rent:"AG",bank_fee:"AH",gross_profit_tax:"AI",salary_cashless:"AJ",payroll_tax:"AK",vacation_cashless:"AL",vacation_tax:"AM",salary_cash:"AN",vacation_cash:"AO",personal_income_tax_22:"AP"};
type MetricRow={code:string;amount:number}; export type ParsedPeriod={store:string;monthDate:string;metrics:MetricRow[]};
const value=(sheet:XLSX.WorkSheet,address:string)=>{const raw=sheet[address]?.v;return typeof raw==="number"&&Number.isFinite(raw)?raw:0};
const cell=(column:string,row:number)=>`${column}${row}`;
const sourceYear=(name:string)=>Number((name.match(/(20\d{2})/)??[])[1]??new Date().getFullYear());
export function parseWorkbook(buffer:Buffer,fileName:string){const workbook=XLSX.read(buffer,{type:"buffer",cellFormula:true});const year=sourceYear(fileName);const parsed:ParsedPeriod[]=[];for(const store of workbook.SheetNames.slice(3)){const sheet=workbook.Sheets[store];if(!sheet||!sheet["!ref"])continue;const range=XLSX.utils.decode_range(sheet["!ref"]);const headers:number[]=[];for(let row=1;row<=range.e.r+1;row++){if(MONTHS.includes(String(sheet[cell("A",row)]?.v??"")))headers.push(row)}for(let index=0;index<headers.length;index++){const start=headers[index],end=headers[index+1]??range.e.r+2,month=String(sheet[cell("A",start)]?.v??"");let total=0,firstData=0,lastData=0;for(let row=start+1;row<end;row++){const label=sheet[cell("A",row)]?.v;if(label==="Итого"){total=row;break}if(typeof label==="number"){if(!firstData)firstData=row;lastData=row}}if(!total||!firstData)continue;const metricRows:MetricRow[]=Object.entries(columns).map(([code,column])=>({code,amount:value(sheet,cell(column,total))}));metricRows.push({code:"net_profit",amount:value(sheet,cell("AQ",firstData))},{code:"stock_open",amount:value(sheet,cell("B",firstData))},{code:"stock_close",amount:value(sheet,cell("B",lastData))});parsed.push({store,monthDate:`${year}-${String(MONTH_NUM[month]??1).padStart(2,"0")}`,metrics:metricRows})}}return {year,stores:Array.from(new Set(parsed.map(row=>row.store))),periods:parsed};}
export async function previewWorkbook(buffer:Buffer,fileName:string){const result=parseWorkbook(buffer,fileName);const db=await getDb();if(!db)return {...result,conflicts:[],existingStores:[]};const names=result.stores;const existing=names.length?await db.select().from(stores).where(inArray(stores.name,names)):[];const ids=existing.map(row=>row.id);const current=ids.length?await db.select().from(periods).where(inArray(periods.storeId,ids)):[];const byId=new Map(existing.map(row=>[row.id,row.name]));const conflicts=current.filter(row=>result.periods.some(item=>item.store===byId.get(row.storeId)&&item.monthDate===row.monthDate)).map(row=>({store:byId.get(row.storeId)??"",monthDate:row.monthDate}));return {...result,conflicts,existingStores:existing.map(row=>row.name)};}
export async function commitWorkbook(buffer:Buffer,fileName:string,resolution:"replace"|"skip"){const preview=await previewWorkbook(buffer,fileName);const db=await getDb();if(!db)throw new Error("База данных недоступна");const stored=await storagePut(`audit-imports/${Date.now()}-${fileName}`,buffer,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");const [importRow]=await db.insert(imports).values({fileName,fileKey:stored.key,sourceYear:preview.year,status:"preview"}).$returningId();let createdStores=0,createdPeriods=0,updatedPeriods=0;for(const record of preview.periods){let [store]=await db.select().from(stores).where(eq(stores.name,record.store)).limit(1);if(!store){const inserted=await db.insert(stores).values({name:record.store}).$returningId();store={id:inserted[0].id,name:record.store,isHidden:false,createdAt:new Date(),updatedAt:new Date()} as typeof stores.$inferSelect;createdStores++}let [period]=await db.select().from(periods).where(and(eq(periods.storeId,store.id),eq(periods.monthDate,record.monthDate))).limit(1);if(period&&resolution==="skip")continue;if(!period){const inserted=await db.insert(periods).values({storeId:store.id,importId:importRow.id,monthDate:record.monthDate}).$returningId();period={id:inserted[0].id} as typeof periods.$inferSelect;createdPeriods++}else{updatedPeriods++;await db.delete(metrics).where(eq(metrics.periodId,period.id));await db.update(periods).set({importId:importRow.id}).where(eq(periods.id,period.id))}if(record.metrics.length)await db.insert(metrics).values(record.metrics.map(metric=>({periodId:period.id,metricCode:metric.code,amount:String(metric.amount)})));}await db.update(imports).set({status:"completed"}).where(eq(imports.id,importRow.id));return {createdStores,createdPeriods,updatedPeriods,fileUrl:stored.url,conflicts:preview.conflicts};}
export async function listAuditStores(){const db=await getDb();if(!db)return [];return db.select().from(stores)}
export async function getAuditDashboard(){const db=await getDb();if(!db)return {stores:[],periods:[]};const storeRows=await db.select().from(stores);const periodRows=await db.select().from(periods);const metricRows=await db.select().from(metrics);const byPeriod=new Map<number,Record<string,number>>();metricRows.forEach(row=>{const current=byPeriod.get(row.periodId)??{};current[row.metricCode]=Number(row.amount);byPeriod.set(row.periodId,current)});const byStore=new Map(storeRows.map(row=>[row.id,row]));return {stores:storeRows.map(row=>({id:row.id,name:row.name,isHidden:row.isHidden})),periods:periodRows.map(row=>({storeId:row.storeId,store:byStore.get(row.storeId)?.name??"",isHidden:byStore.get(row.storeId)?.isHidden??true,monthDate:row.monthDate,metrics:byPeriod.get(row.id)??{}}))};}
export async function setStoreVisibility(id:number,isHidden:boolean){const db=await getDb();if(!db)throw new Error("База данных недоступна");await db.update(stores).set({isHidden}).where(eq(stores.id,id));return {success:true};}
export async function listStoreMetrics(storeId:number,monthDate:string){const db=await getDb();if(!db)return [];const [period]=await db.select().from(periods).where(and(eq(periods.storeId,storeId),eq(periods.monthDate,monthDate))).limit(1);if(!period)return [];return db.select().from(metrics).where(eq(metrics.periodId,period.id));}
export async function updateMetricValue(storeId:number,monthDate:string,metricCode:string,amount:number){const db=await getDb();if(!db)throw new Error("База данных недоступна");let [period]=await db.select().from(periods).where(and(eq(periods.storeId,storeId),eq(periods.monthDate,monthDate))).limit(1);if(!period){const created=await db.insert(periods).values({storeId,monthDate}).$returningId();period={id:created[0].id} as typeof periods.$inferSelect}await db.insert(metrics).values({periodId:period.id,metricCode,amount:String(amount)}).onDuplicateKeyUpdate({set:{amount:String(amount)}});return {success:true,createdPeriod:!period};}
