import { describe, expect, it } from "vitest";
import * as XLSX from "xlsx";
import { parseWorkbook } from "./audit";

const workbookWithSheet=(header:string[],total:number[])=>{const workbook=XLSX.utils.book_new();["tech-1","tech-2","tech-3"].forEach(name=>XLSX.utils.book_append_sheet(workbook,XLSX.utils.aoa_to_sheet([[name]]),name));const sheet=XLSX.utils.aoa_to_sheet([["Январь"],header,[1,...total],["Итого",...total]]);sheet["AQ3"]={t:"n",v:17};sheet["!ref"]="A1:AQ4";XLSX.utils.book_append_sheet(workbook,sheet,"Новый магазин");return XLSX.write(workbook,{type:"buffer",bookType:"xlsx"}) as Buffer};

describe("parseWorkbook",()=>{
  it("пропускает первые три листа и нормализует месячный блок с заголовками 2026",()=>{const header=["Дата","Остаток","З. Коп","З. Мор","П. Коп","П. Мор","Закупка","Продажа","% коп","% мор","% общий","Грязная","Выр нал","Б/нал","Общая","Списания К.","Списания М.","Перемещение","Уценка","Переоценка","Хоз. Нужды","Доставка","Уборка","Премия","Выслуга","Доплата","Водитель","Ком. Плат.","Расходы","Траты нал","Вод. Б/нал","Ком. Б/нал","Аренда","-% банк","Налоги","Зарпл. Б/нал","Налоги з/п","Отпускные","Налоги отпуск.","Зарпл. Нал","Отпуск. Нал","НДФЛ 22%","Итог"];const total=header.slice(1).map((_,index)=>index+10);const result=parseWorkbook(workbookWithSheet(header,total),"операционный_2026.xlsx");expect(result.year).toBe(2026);expect(result.stores).toEqual(["Новый магазин"]);expect(result.periods).toHaveLength(1);expect(result.periods[0]?.monthDate).toBe("2026-01");expect(result.periods[0]?.entryDate).toBe("2026-01-01");expect(result.periods[0]?.metrics).toEqual(expect.arrayContaining([{code:"revenue",amount:16},{code:"net_profit",amount:17},{code:"stock_open",amount:10}]));});
  it("сохраняет отличающуюся вторую колонку «Расходы» из книги 2025 отдельным кодом",()=>{const header=["Дата","Остаток","З. Коп","З. Мор","П. Коп","П. Мор","Закупка","Продажа","% коп","% мор","% общий","Грязная","Выр нал","б/нал","Общая","Списания К.","Списания М.","Перемещение","Уценка","Переоценка","Хоз. Нужды","Доставка","Уборка","Примия","Выслуга","Доплата","Водитель","Ком. Плат.","Расходы","Траты нал","Расходы","Ком. Б/нал","Аренда","-% банк","Налоги","Зарпл. б/нал","Зарпл. нал","НДФЛ 22%","Итог"];const total=header.slice(1).map((_,index)=>index+10);const result=parseWorkbook(workbookWithSheet(header,total),"учет_2025.xlsx");expect(result.year).toBe(2025);expect(result.periods[0]?.metrics).toEqual(expect.arrayContaining([{code:"bonus",amount:32},{code:"cashless_operating_costs",amount:39},{code:"personal_income_tax_22",amount:46}]));});
});
