import * as XLSX from "xlsx";
import { and, desc, eq, inArray } from "drizzle-orm";
import { imports, metrics, periods, storeAccess, stores } from "../drizzle/schema";
import { getDb } from "./db";
import { storagePut } from "./storage";

const MONTHS=["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"];
const MONTH_NUM=Object.fromEntries(MONTHS.map((month,index)=>[month,index+1]));
type MetricRow={code:string;amount:number};
export type ParsedPeriod={store:string;monthDate:string;entryDate:string;metrics:MetricRow[]};
const cell=(column:string,row:number)=>`${column}${row}`;
const value=(sheet:XLSX.WorkSheet,address:string)=>{const raw=sheet[address]?.v;return typeof raw==="number"&&Number.isFinite(raw)?raw:0};
const sourceYear=(name:string)=>Number((name.match(/(20\d{2})/)??[])[1]??new Date().getFullYear());
const storageFilename=(fileName:string)=>{const safe=fileName.normalize("NFKD").replace(/[^A-Za-z0-9._-]/g,"_").replace(/_+/g,"_").replace(/^_+|_+$/g,"");return safe||`workbook-${Date.now()}.xlsx`};
const cleanHeader=(value:unknown)=>String(value??"").toLowerCase().trim().replace(/ё/g,"е").replace(/\./g,"").replace(/\s+/g," ");
const headerCodes:Record<string,string>={"з коп":"purchase_smoked","з мор":"purchase_frozen","п коп":"sales_smoked","п мор":"sales_frozen",закупка:"purchases",продажа:"revenue",грязная:"gross_profit","выр нал":"cash_revenue","б/нал":"cashless_revenue",общая:"receipts_total","списания к":"writeoff_smoked","списания м":"writeoff_frozen",перемещение:"movement",уценка:"discount",переоценка:"revaluation","хоз нужды":"household",доставка:"delivery",уборка:"cleaning",премия:"bonus",примия:"bonus",выслуга:"seniority",доплата:"supplement",водитель:"driver_cash","ком плат":"utilities_cash","траты нал":"cash_operating_costs","вод б/нал":"driver_cashless","ком б/нал":"utilities_cashless",аренда:"rent","-% банк":"bank_fee",налоги:"gross_profit_tax","зарпл б/нал":"salary_cashless","налоги з/п":"payroll_tax",отпускные:"vacation_cashless","налоги отпуск":"vacation_tax","зарпл нал":"salary_cash","отпуск нал":"vacation_cash","ндфл 22%":"personal_income_tax_22",итог:"net_profit"};

function metricColumns(sheet:XLSX.WorkSheet,headerRow:number){const result=new Map<string,string>();let expenseSeen=0;for(let index=0;index<60;index+=1){const label=cleanHeader(sheet[cell(XLSX.utils.encode_col(index),headerRow)]?.v);if(!label)continue;if(label==="расходы"){result.set(expenseSeen===0?"operating_costs":"cashless_operating_costs",XLSX.utils.encode_col(index));expenseSeen+=1;continue}const code=headerCodes[label];if(code&&!result.has(code))result.set(code,XLSX.utils.encode_col(index))}return result}

export function parseWorkbook(buffer:Buffer,fileName:string){const workbook=XLSX.read(buffer,{type:"buffer",cellFormula:true});const year=sourceYear(fileName);const parsed:ParsedPeriod[]=[];for(const store of workbook.SheetNames.slice(3)){const sheet=workbook.Sheets[store];if(!sheet?.["!ref"])continue;const range=XLSX.utils.decode_range(sheet["!ref"]);const headers:number[]=[];for(let row=1;row<=range.e.r+1;row+=1)if(MONTHS.includes(String(sheet[cell("A",row)]?.v??"")))headers.push(row);for(let index=0;index<headers.length;index+=1){const start=headers[index],end=headers[index+1]??range.e.r+2,month=String(sheet[cell("A",start)]?.v??"");let total=0,firstData=0,lastData=0;for(let row=start+1;row<end;row+=1){const label=sheet[cell("A",row)]?.v;if(label==="Итого"){total=row;break}if(typeof label==="number"){if(!firstData)firstData=row;lastData=row}}if(!total||!firstData)continue;const metricRows=Array.from(metricColumns(sheet,start+1)).map(([code,column])=>({code,amount:value(sheet,cell(column,code==="net_profit"?firstData:total))}));metricRows.push({code:"stock_open",amount:value(sheet,cell("B",firstData))},{code:"stock_close",amount:value(sheet,cell("B",lastData))});const monthDate=`${year}-${String(MONTH_NUM[month]??1).padStart(2,"0")}`;parsed.push({store,monthDate,entryDate:`${monthDate}-01`,metrics:metricRows})}}return {year,stores:Array.from(new Set(parsed.map(row=>row.store))),periods:parsed};}

export async function previewWorkbook(buffer:Buffer,fileName:string){const result=parseWorkbook(buffer,fileName);const db=await getDb();if(!db)return {...result,conflicts:[],existingStores:[]};const existing=result.stores.length?await db.select().from(stores).where(inArray(stores.name,result.stores)):[];const ids=existing.map(row=>row.id);const current=ids.length?await db.select().from(periods).where(inArray(periods.storeId,ids)):[];const namesById=new Map(existing.map(row=>[row.id,row.name]));const incoming=new Set(result.periods.map(row=>`${row.store}:${row.entryDate}`));const conflicts=current.filter(row=>incoming.has(`${namesById.get(row.storeId)}:${row.entryDate}`)).map(row=>({store:namesById.get(row.storeId)??"",monthDate:row.monthDate,entryDate:row.entryDate}));return {...result,conflicts,existingStores:existing.map(row=>row.name)};}

export async function commitWorkbook(buffer:Buffer,fileName:string,resolution:"replace"|"skip"){const preview=await previewWorkbook(buffer,fileName);const db=await getDb();if(!db)throw new Error("База данных недоступна");const contentType=/\.xlsm$/i.test(fileName)?"application/vnd.ms-excel.sheet.macroEnabled.12":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";const stored=await storagePut(`audit-imports/${Date.now()}-${storageFilename(fileName)}`,buffer,contentType);const [importRow]=await db.insert(imports).values({fileName,fileKey:stored.key,sourceYear:preview.year,status:"preview"}).$returningId();let createdStores=0,createdPeriods=0,updatedPeriods=0;const riskEvents:Array<{storeId:number;store:string;monthDate:string;type:"negative_profit"|"frozen_writeoff";amount:number}>=[];for(const record of preview.periods){let [store]=await db.select().from(stores).where(eq(stores.name,record.store)).limit(1);if(!store){const inserted=await db.insert(stores).values({name:record.store}).$returningId();store={id:inserted[0].id,name:record.store,isHidden:false,createdAt:new Date(),updatedAt:new Date()} as typeof stores.$inferSelect;createdStores+=1}let [period]=await db.select().from(periods).where(and(eq(periods.storeId,store.id),eq(periods.entryDate,record.entryDate))).limit(1);if(period&&resolution==="skip")continue;if(!period){const inserted=await db.insert(periods).values({storeId:store.id,importId:importRow.id,monthDate:record.monthDate,entryDate:record.entryDate}).$returningId();period={id:inserted[0].id} as typeof periods.$inferSelect;createdPeriods+=1}else{updatedPeriods+=1;await db.delete(metrics).where(eq(metrics.periodId,period.id));await db.update(periods).set({importId:importRow.id,monthDate:record.monthDate}).where(eq(periods.id,period.id))}if(record.metrics.length)await db.insert(metrics).values(record.metrics.map(metric=>({periodId:period!.id,metricCode:metric.code,amount:String(metric.amount)})));const profit=Number(record.metrics.find(metric=>metric.code==="net_profit")?.amount??0);const frozenWriteoff=Number(record.metrics.find(metric=>metric.code==="writeoff_frozen")?.amount??0);if(profit<0)riskEvents.push({storeId:store.id,store:store.name,monthDate:record.monthDate,type:"negative_profit",amount:profit});if(frozenWriteoff>=50000)riskEvents.push({storeId:store.id,store:store.name,monthDate:record.monthDate,type:"frozen_writeoff",amount:frozenWriteoff});}await db.update(imports).set({status:"completed"}).where(eq(imports.id,importRow.id));return {importId:importRow.id,createdStores,createdPeriods,updatedPeriods,fileUrl:stored.url,conflicts:preview.conflicts,riskEvents};}

export async function listAuditImports(){const db=await getDb();if(!db)return [];const [importRows,periodRows]=await Promise.all([db.select().from(imports).orderBy(desc(imports.createdAt)),db.select().from(periods)]);return importRows.map(row=>({id:row.id,fileName:row.fileName,sourceYear:row.sourceYear,status:row.status,createdAt:row.createdAt,periods:periodRows.filter(period=>period.importId===row.id).length,stores:new Set(periodRows.filter(period=>period.importId===row.id).map(period=>period.storeId)).size}));}

export async function deleteAuditImport(importId:number){const db=await getDb();if(!db)throw new Error("База данных недоступна");const [importRow]=await db.select().from(imports).where(eq(imports.id,importId)).limit(1);if(!importRow)throw new Error("Импорт не найден");const affected=await db.select().from(periods).where(eq(periods.importId,importId));const ids=affected.map(period=>period.id);const affectedStoreIds=Array.from(new Set(affected.map(period=>period.storeId)));if(ids.length)await db.delete(metrics).where(inArray(metrics.periodId,ids));if(ids.length)await db.delete(periods).where(inArray(periods.id,ids));await db.delete(imports).where(eq(imports.id,importId));let deletedStores=0;for(const storeId of affectedStoreIds){const left=await db.select({id:periods.id}).from(periods).where(eq(periods.storeId,storeId)).limit(1);if(!left.length){await db.delete(storeAccess).where(eq(storeAccess.storeId,storeId));await db.delete(stores).where(eq(stores.id,storeId));deletedStores+=1}}return {success:true,fileName:importRow.fileName,deletedPeriods:ids.length,deletedStores};}

export async function mergeAuditStores(sourceStoreId:number,targetStoreId:number,resolution:"replace"|"skip"){if(sourceStoreId===targetStoreId)throw new Error("Выберите разные магазины");const db=await getDb();if(!db)throw new Error("База данных недоступна");const [source,target]=await Promise.all([db.select().from(stores).where(eq(stores.id,sourceStoreId)).limit(1),db.select().from(stores).where(eq(stores.id,targetStoreId)).limit(1)]);if(!source[0]||!target[0])throw new Error("Магазин не найден");const [sourcePeriods,targetPeriods]=await Promise.all([db.select().from(periods).where(eq(periods.storeId,sourceStoreId)),db.select().from(periods).where(eq(periods.storeId,targetStoreId))]);const targetByDate=new Map(targetPeriods.map(period=>[period.entryDate,period]));let moved=0,replaced=0,skipped=0;for(const period of sourcePeriods){const duplicate=targetByDate.get(period.entryDate);if(duplicate){if(resolution==="replace"){await db.delete(metrics).where(eq(metrics.periodId,duplicate.id));await db.delete(periods).where(eq(periods.id,duplicate.id));await db.update(periods).set({storeId:targetStoreId}).where(eq(periods.id,period.id));replaced+=1}else{await db.delete(metrics).where(eq(metrics.periodId,period.id));await db.delete(periods).where(eq(periods.id,period.id));skipped+=1}}else{await db.update(periods).set({storeId:targetStoreId}).where(eq(periods.id,period.id));moved+=1}}const accessRows=await db.select().from(storeAccess).where(inArray(storeAccess.storeId,[sourceStoreId,targetStoreId]));const merged=new Map<number,"view"|"edit">();accessRows.forEach(row=>merged.set(row.accountId,row.accessLevel==="edit"||merged.get(row.accountId)==="edit"?"edit":"view"));await db.delete(storeAccess).where(inArray(storeAccess.storeId,[sourceStoreId,targetStoreId]));if(merged.size)await db.insert(storeAccess).values(Array.from(merged.entries()).map(([accountId,accessLevel])=>({accountId,storeId:targetStoreId,accessLevel})));await db.delete(stores).where(eq(stores.id,sourceStoreId));return {success:true,source:source[0].name,target:target[0].name,moved,replaced,skipped};}

export async function listAuditStores(allowedStoreIds:number[]|null=null){const db=await getDb();if(!db||(Array.isArray(allowedStoreIds)&&allowedStoreIds.length===0))return [];return allowedStoreIds===null?db.select().from(stores):db.select().from(stores).where(inArray(stores.id,allowedStoreIds));}
export async function getAuditDashboard(allowedStoreIds:number[]|null=null){const db=await getDb();if(!db||(Array.isArray(allowedStoreIds)&&allowedStoreIds.length===0))return {stores:[],periods:[]};const storeRows=allowedStoreIds===null?await db.select().from(stores):await db.select().from(stores).where(inArray(stores.id,allowedStoreIds));const storeIds=storeRows.map(store=>store.id);if(!storeIds.length)return {stores:[],periods:[]};const periodRows=await db.select().from(periods).where(inArray(periods.storeId,storeIds));const periodIds=periodRows.map(period=>period.id);const metricRows=periodIds.length?await db.select().from(metrics).where(inArray(metrics.periodId,periodIds)):[];const byPeriod=new Map<number,Record<string,number>>();metricRows.forEach(row=>{const current=byPeriod.get(row.periodId)??{};current[row.metricCode]=Number(row.amount);byPeriod.set(row.periodId,current)});const byStore=new Map(storeRows.map(row=>[row.id,row]));return {stores:storeRows.map(row=>({id:row.id,name:row.name,isHidden:row.isHidden})),periods:periodRows.map(row=>({storeId:row.storeId,store:byStore.get(row.storeId)?.name??"",isHidden:byStore.get(row.storeId)?.isHidden??true,monthDate:row.monthDate,entryDate:row.entryDate,metrics:byPeriod.get(row.id)??{}}))};}
export async function setStoreVisibility(id:number,isHidden:boolean){const db=await getDb();if(!db)throw new Error("База данных недоступна");await db.update(stores).set({isHidden}).where(eq(stores.id,id));return {success:true};}
export async function listStoreEntries(storeId:number){const db=await getDb();if(!db)return [];return db.select({entryDate:periods.entryDate,monthDate:periods.monthDate,importId:periods.importId}).from(periods).where(eq(periods.storeId,storeId)).orderBy(desc(periods.entryDate));}
export async function listStoreMetrics(storeId:number,entryDate:string){const db=await getDb();if(!db)return [];const [period]=await db.select().from(periods).where(and(eq(periods.storeId,storeId),eq(periods.entryDate,entryDate))).limit(1);if(!period)return [];return db.select().from(metrics).where(eq(metrics.periodId,period.id));}
export async function updateMetricValue(storeId:number,entryDate:string,metricCode:string,amount:number){const db=await getDb();if(!db)throw new Error("База данных недоступна");let [period]=await db.select().from(periods).where(and(eq(periods.storeId,storeId),eq(periods.entryDate,entryDate))).limit(1);const createdPeriod=!period;if(!period){const created=await db.insert(periods).values({storeId,monthDate:entryDate.slice(0,7),entryDate}).$returningId();period={id:created[0].id} as typeof periods.$inferSelect}await db.insert(metrics).values({periodId:period.id,metricCode,amount:String(amount)}).onDuplicateKeyUpdate({set:{amount:String(amount)}});return {success:true,createdPeriod};}
export async function deleteMetricValue(storeId:number,entryDate:string,metricCode:string){const db=await getDb();if(!db)throw new Error("База данных недоступна");const [period]=await db.select().from(periods).where(and(eq(periods.storeId,storeId),eq(periods.entryDate,entryDate))).limit(1);if(!period)throw new Error("Запись не найдена");await db.delete(metrics).where(and(eq(metrics.periodId,period.id),eq(metrics.metricCode,metricCode)));const left=await db.select({id:metrics.id}).from(metrics).where(eq(metrics.periodId,period.id)).limit(1);if(!left.length)await db.delete(periods).where(eq(periods.id,period.id));return {success:true,deletedPeriod:!left.length};}
