import { createHash, randomBytes, scryptSync, timingSafeEqual } from "crypto";
import { and, desc, eq, gt, sql } from "drizzle-orm";
import { parse as parseCookie } from "cookie";
import { auditChangeLog, localAccounts, localSessions, users } from "../drizzle/schema";
import { getDb } from "./db";
import { updateMetricValue } from "./audit";

const BOOTSTRAP_USERNAME = "79537573636";
const LEGACY_BOOTSTRAP_USERNAME = "Apolexis";
const LOCAL_PREFIX = "local:";
export const LOCAL_SESSION_COOKIE = "audit_local_session";
const SESSION_MS = 1000 * 60 * 60 * 24 * 30;
type LocalRole = "admin" | "analyst";
type ChangeInput = { actorId?: number | null; action: string; entityType: string; entityId: string; beforeState?: unknown; afterState?: unknown; rollbackOf?: number };

export const normalizeRussianPhone=(value:string)=>{const digits=value.replace(/\D/g,"");const normalized=digits.length===10&&digits.startsWith("9")?`7${digits}`:digits.length===11&&digits.startsWith("8")?`7${digits.slice(1)}`:digits;if(!/^79\d{9}$/.test(normalized))throw new Error("Введите российский мобильный номер: +7 (900) 000-00-00");return normalized};
export const formatRussianPhone=(value:string)=>{const number=normalizeRussianPhone(value);return `+7 (${number.slice(1,4)}) ${number.slice(4,7)}-${number.slice(7,9)}-${number.slice(9,11)}`};
const localOpenId=(username:string)=>`${LOCAL_PREFIX}${username.toLowerCase()}`;
const hashToken=(token:string)=>createHash("sha256").update(token).digest("hex");
function hashPassword(password:string){const salt=randomBytes(16).toString("hex");return `${salt}:${scryptSync(password,salt,64).toString("hex")}`}
function passwordMatches(password:string,stored:string){const [salt,digest]=stored.split(":");if(!salt||!digest)return false;const candidate=scryptSync(password,salt,64).toString("hex");return timingSafeEqual(Buffer.from(candidate,"hex"),Buffer.from(digest,"hex"))}
const coreRole=(role:LocalRole)=>(role==="admin"?"admin":"user") as "admin"|"user";

async function ensureCoreUser(username:string,displayName:string,role:LocalRole){const db=await getDb();if(!db)throw new Error("База данных недоступна");const openId=localOpenId(username);await db.insert(users).values({openId,name:displayName,loginMethod:"local-password",role:coreRole(role),lastSignedIn:new Date()}).onDuplicateKeyUpdate({set:{name:displayName,loginMethod:"local-password",role:coreRole(role),lastSignedIn:new Date()}});return openId}

export async function ensureBootstrapAccount(){const db=await getDb();if(!db)throw new Error("База данных недоступна");const [existing]=await db.select().from(localAccounts).where(eq(localAccounts.username,BOOTSTRAP_USERNAME)).limit(1);if(existing){await ensureCoreUser(existing.username,existing.displayName,existing.role);return existing}const [legacy]=await db.select().from(localAccounts).where(eq(localAccounts.username,LEGACY_BOOTSTRAP_USERNAME)).limit(1);if(legacy&&legacy.role==="admin"){await db.update(localAccounts).set({username:BOOTSTRAP_USERNAME,displayName:formatRussianPhone(BOOTSTRAP_USERNAME)}).where(eq(localAccounts.id,legacy.id));const [migrated]=await db.select().from(localAccounts).where(eq(localAccounts.id,legacy.id)).limit(1);await ensureCoreUser(migrated!.username,migrated!.displayName,migrated!.role);return migrated!}const password=process.env.INITIAL_ADMIN_PASSWORD;if(!password)throw new Error("Не задан начальный пароль администратора");const [inserted]=await db.insert(localAccounts).values({username:BOOTSTRAP_USERNAME,displayName:formatRussianPhone(BOOTSTRAP_USERNAME),passwordHash:hashPassword(password),role:"admin",isActive:true}).$returningId();await ensureCoreUser(BOOTSTRAP_USERNAME,formatRussianPhone(BOOTSTRAP_USERNAME),"admin");const [created]=await db.select().from(localAccounts).where(eq(localAccounts.id,inserted.id)).limit(1);return created!}
export function verifyBootstrapPassword(candidate:string){return Boolean(process.env.INITIAL_ADMIN_PASSWORD)&&candidate===process.env.INITIAL_ADMIN_PASSWORD}

export async function authenticateLocalAccount(username:string,password:string){await ensureBootstrapAccount();const db=await getDb();if(!db)throw new Error("База данных недоступна");let normalized:string;try{normalized=normalizeRussianPhone(username)}catch{return null}const [account]=await db.select().from(localAccounts).where(eq(localAccounts.username,normalized)).limit(1);if(!account||!account.isActive||!passwordMatches(password,account.passwordHash))return null;await db.update(localAccounts).set({lastLoginAt:new Date()}).where(eq(localAccounts.id,account.id));await ensureCoreUser(account.username,account.displayName,account.role);await recordChange({actorId:account.id,action:"account.login",entityType:"account",entityId:String(account.id)});return account}
export async function createLocalSession(accountId:number){const db=await getDb();if(!db)throw new Error("База данных недоступна");const token=randomBytes(32).toString("base64url");const expiresAt=new Date(Date.now()+SESSION_MS);await db.insert(localSessions).values({accountId,tokenHash:hashToken(token),expiresAt});return {token,expiresAt}}
export async function getLocalSessionFromCookie(cookieHeader?:string){const token=parseCookie(cookieHeader??"")[LOCAL_SESSION_COOKIE];if(!token)return null;const db=await getDb();if(!db)return null;const [session]=await db.select().from(localSessions).where(and(eq(localSessions.tokenHash,hashToken(token)),gt(localSessions.expiresAt,new Date()))).limit(1);if(!session)return null;const [account]=await db.select().from(localAccounts).where(eq(localAccounts.id,session.accountId)).limit(1);return account?.isActive?{account,openId:localOpenId(account.username)}:null}
export async function deleteLocalSessionFromCookie(cookieHeader?:string){const token=parseCookie(cookieHeader??"")[LOCAL_SESSION_COOKIE];if(!token)return;const db=await getDb();if(db)await db.delete(localSessions).where(eq(localSessions.tokenHash,hashToken(token)))}
export async function getLocalAccountByOpenId(openId?:string|null){if(!openId?.startsWith(LOCAL_PREFIX))return null;const db=await getDb();if(!db)return null;const [account]=await db.select().from(localAccounts).where(eq(localAccounts.username,openId.slice(LOCAL_PREFIX.length))).limit(1);return account?.isActive?account:null}

export async function listLocalAccounts(){await ensureBootstrapAccount();const db=await getDb();if(!db)return [];return db.select({id:localAccounts.id,username:localAccounts.username,displayName:localAccounts.displayName,role:localAccounts.role,isActive:localAccounts.isActive,createdAt:localAccounts.createdAt,lastLoginAt:localAccounts.lastLoginAt}).from(localAccounts).orderBy(localAccounts.username)}
export async function createLocalAccount(input:{username:string;password:string;role:LocalRole},actorId:number){const db=await getDb();if(!db)throw new Error("База данных недоступна");const username=normalizeRussianPhone(input.username);const displayName=formatRussianPhone(username);const [inserted]=await db.insert(localAccounts).values({username,displayName,passwordHash:hashPassword(input.password),role:input.role,isActive:true}).$returningId();await ensureCoreUser(username,displayName,input.role);await recordChange({actorId,action:"account.create",entityType:"account",entityId:String(inserted.id),afterState:{username,displayName,role:input.role}});return inserted.id}
export async function updateLocalAccount(input:{id:number;role?:LocalRole;isActive?:boolean},actorId:number){const db=await getDb();if(!db)throw new Error("База данных недоступна");const [before]=await db.select().from(localAccounts).where(eq(localAccounts.id,input.id)).limit(1);if(!before)throw new Error("Учетная запись не найдена");if(before.role==="admin"&&(input.role==="analyst"||input.isActive===false)){const admins=await db.select({id:localAccounts.id}).from(localAccounts).where(and(eq(localAccounts.role,"admin"),eq(localAccounts.isActive,true)));if(admins.length<=1)throw new Error("Нельзя отключить или понизить последнего активного администратора")}const patch={...(input.role!==undefined?{role:input.role}:{}),...(input.isActive!==undefined?{isActive:input.isActive}:{})};await db.update(localAccounts).set(patch).where(eq(localAccounts.id,input.id));const [after]=await db.select().from(localAccounts).where(eq(localAccounts.id,input.id)).limit(1);await ensureCoreUser(after!.username,after!.displayName,after!.role);await recordChange({actorId,action:"account.update",entityType:"account",entityId:String(input.id),beforeState:{role:before.role,isActive:before.isActive},afterState:{role:after!.role,isActive:after!.isActive}});return after}
export async function changeLocalPassword(accountId:number,currentPassword:string,nextPassword:string,actorId:number){const db=await getDb();if(!db)throw new Error("База данных недоступна");const [account]=await db.select().from(localAccounts).where(eq(localAccounts.id,accountId)).limit(1);if(!account||!passwordMatches(currentPassword,account.passwordHash))throw new Error("Текущий пароль неверен");await db.update(localAccounts).set({passwordHash:hashPassword(nextPassword)}).where(eq(localAccounts.id,accountId));await recordChange({actorId,action:"account.password.change",entityType:"account",entityId:String(accountId)});return {success:true}}
export async function recordChange(input:ChangeInput){const db=await getDb();if(!db)return;await db.insert(auditChangeLog).values({actorId:input.actorId??null,action:input.action,entityType:input.entityType,entityId:input.entityId,beforeState:input.beforeState??null,afterState:input.afterState??null,rollbackOf:input.rollbackOf??null})}
export async function listChanges(){const db=await getDb();if(!db)return [];return db.select().from(auditChangeLog).orderBy(desc(auditChangeLog.createdAt)).limit(100)}
export async function rollbackMetricChange(changeId:number,actorId:number){const db=await getDb();if(!db)throw new Error("База данных недоступна");const [change]=await db.select().from(auditChangeLog).where(eq(auditChangeLog.id,changeId)).limit(1);if(!change||change.entityType!=="metric"||!change.beforeState)throw new Error("Эта операция не поддерживает откат");const previous=change.beforeState as {storeId:number;monthDate:string;metricCode:string;amount:number};await updateMetricValue(previous.storeId,previous.monthDate,previous.metricCode,Number(previous.amount));await recordChange({actorId,action:"metric.rollback",entityType:"metric",entityId:`${previous.storeId}:${previous.monthDate}:${previous.metricCode}`,beforeState:change.afterState,afterState:previous,rollbackOf:change.id});return {success:true,restored:previous}}
