/** Shared store selection, period and theme. Periods are ISO dates and remain year-aware. */
import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { useLocation } from "wouter";

export type DateRangeValue={from:string;to:string};
const defaultRange={from:"2026-01-01",to:"2026-12-31"};
const pretty=(date:string)=>date.split("-").reverse().join(".");
const normalizeRange=(value:DateRangeValue):DateRangeValue=>value.from<=value.to?value:{from:value.to,to:value.from};
const themeIcon={dark:"/manus-storage/rybny_circle_dark_transparent_v8_03811f3b.png?v=8",light:"/manus-storage/rybny_circle_light_transparent_v8_bb483d15.png?v=8"} as const;
const themeManifest={dark:"/manifest-dark.webmanifest?v=8",light:"/manifest-light.webmanifest?v=8"} as const;
const storedTheme=()=>localStorage.getItem("audit-theme") as "dark"|"light"|null;
const systemTheme=()=>window.matchMedia?.("(prefers-color-scheme: light)").matches?"light":"dark";
type AuditState={selectedStore:string;setSelectedStore:(value:string)=>void;range:DateRangeValue;setRange:(value:DateRangeValue)=>void;theme:"dark"|"light";toggleTheme:()=>void;rangeLabel:string;months:string[];includesMonth:(value:string)=>boolean};
const AuditContext=createContext<AuditState|null>(null);
export function AuditProvider({children}:{children:ReactNode}){const [selectedStore,setSelectedStore]=useState(()=>localStorage.getItem("audit-store")??"__all__");const [range,setRangeState]=useState<DateRangeValue>(()=>{try{const stored=JSON.parse(localStorage.getItem("audit-range")??"null") as DateRangeValue|null;if(!stored?.from||!stored?.to)return defaultRange;return normalizeRange(stored)}catch{return defaultRange}});const [theme,setTheme]=useState<"dark"|"light">(()=>storedTheme()??systemTheme());const [location]=useLocation();const setRange=(value:DateRangeValue)=>setRangeState(normalizeRange(value));useEffect(()=>{localStorage.setItem("audit-store",selectedStore)},[selectedStore]);useEffect(()=>{localStorage.setItem("audit-range",JSON.stringify(range))},[range]);useEffect(()=>{const color=theme==="dark"?"#0c0b12":"#f2f2f7";localStorage.setItem("audit-theme",theme);document.documentElement.dataset.auditTheme=theme;document.documentElement.style.backgroundColor=color;document.body.style.backgroundColor=color;document.querySelector<HTMLMetaElement>('meta[name="theme-color"]')?.setAttribute("content",color);document.querySelector<HTMLMetaElement>('meta[name="apple-mobile-web-app-status-bar-style"]')?.setAttribute("content",theme==="dark"?"black-translucent":"default");document.getElementById("app-favicon")?.setAttribute("href",themeIcon[theme]);document.getElementById("app-apple-touch-icon")?.setAttribute("href",themeIcon[theme]);document.getElementById("app-manifest")?.setAttribute("href",themeManifest[theme])},[theme]);useEffect(()=>{window.scrollTo({top:0,left:0,behavior:"auto"})},[location]);const value=useMemo(()=>{const start=new Date(`${range.from.slice(0,7)}-01T00:00:00`),end=new Date(`${range.to.slice(0,7)}-01T00:00:00`),months:string[]=[];for(const cursor=new Date(start);cursor<=end;cursor.setMonth(cursor.getMonth()+1))months.push(`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,"0")}`);return {selectedStore,setSelectedStore,range,setRange,theme,toggleTheme:()=>setTheme(current=>current==="dark"?"light":"dark"),rangeLabel:`${pretty(range.from)} — ${pretty(range.to)}`,months,includesMonth:(value:string)=>{const normalized=value.length===7?value:value.slice(0,7);return normalized>=range.from.slice(0,7)&&normalized<=range.to.slice(0,7)}}},[selectedStore,range,theme]);return <AuditContext.Provider value={value}>{children}</AuditContext.Provider>}
export function useAudit(){const context=useContext(AuditContext);if(!context)throw new Error("useAudit must be inside AuditProvider");return context}
