/** Shared store selection, period and theme. Periods are ISO dates and remain year-aware. */
import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { useLocation } from "wouter";

export type DateRangeValue={from:string;to:string};
const monthLong=["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"];
const defaultRange={from:"2026-01-01",to:"2026-12-31"};
const pretty=(date:string)=>`${monthLong[Math.max(0,Math.min(11,Number(date.slice(5,7))-1))]??date} ${date.slice(0,4)}`;
const normalizeRange=(value:DateRangeValue):DateRangeValue=>value.from<=value.to?value:{from:value.to,to:value.from};
type AuditState={selectedStore:string;setSelectedStore:(value:string)=>void;range:DateRangeValue;setRange:(value:DateRangeValue)=>void;theme:"dark"|"light";toggleTheme:()=>void;rangeLabel:string;months:string[];includesMonth:(value:string)=>boolean};
const AuditContext=createContext<AuditState|null>(null);
export function AuditProvider({children}:{children:ReactNode}){const [selectedStore,setSelectedStore]=useState(()=>localStorage.getItem("audit-store")??"__all__");const [range,setRangeState]=useState<DateRangeValue>(()=>{try{const stored=JSON.parse(localStorage.getItem("audit-range")??"null") as DateRangeValue|null;if(!stored?.from||!stored?.to)return defaultRange;const normalized=normalizeRange(stored);return normalized.from==="2026-01-01"&&normalized.to==="2026-08-31"?defaultRange:normalized}catch{return defaultRange}});const [theme,setTheme]=useState<"dark"|"light">(()=>(localStorage.getItem("audit-theme") as "dark"|"light")??"dark");const [location]=useLocation();const setRange=(value:DateRangeValue)=>setRangeState(normalizeRange(value));useEffect(()=>{localStorage.setItem("audit-store",selectedStore)},[selectedStore]);useEffect(()=>{localStorage.setItem("audit-range",JSON.stringify(range))},[range]);useEffect(()=>{localStorage.setItem("audit-theme",theme);document.documentElement.dataset.auditTheme=theme},[theme]);useEffect(()=>{window.scrollTo({top:0,left:0,behavior:"auto"})},[location]);const value=useMemo(()=>{const start=new Date(`${range.from.slice(0,7)}-01T00:00:00`),end=new Date(`${range.to.slice(0,7)}-01T00:00:00`),months:string[]=[];for(const cursor=new Date(start);cursor<=end;cursor.setMonth(cursor.getMonth()+1))months.push(`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,"0")}`);return {selectedStore,setSelectedStore,range,setRange,theme,toggleTheme:()=>setTheme(current=>current==="dark"?"light":"dark"),rangeLabel:`${pretty(range.from)} — ${pretty(range.to)}`,months,includesMonth:(value:string)=>{const normalized=value.length===7?value:value.slice(0,7);return normalized>=range.from.slice(0,7)&&normalized<=range.to.slice(0,7)}}},[selectedStore,range,theme]);return <AuditContext.Provider value={value}>{children}</AuditContext.Provider>}
export function useAudit(){const context=useContext(AuditContext);if(!context)throw new Error("useAudit must be inside AuditProvider");return context}
