import json
from pathlib import Path

ROOT=Path('/home/ubuntu/retail_profit_audit_2026'); DATA=json.loads((ROOT/'audit_2026'/'audit_august_clean_excl_s2'/'analysis_data.json').read_text()); OUT=ROOT/'deliverables'/'retail_audit_august_expanded'
ids={'ПОРТ':'store_port','А2':'store_a2','КИР1':'store_kir1','ОЛЕ':'store_ole','А1':'store_a1','ПОЛ':'store_pol','КОВ':'store_kov','КИР3':'store_kir3','КА2':'store_ka2','ЗАП':'store_zap','КНИП':'store_knip','ГС2':'store_gs2','С1':'store_s1','К49':'store_k49','Л76':'store_l76','А3':'store_a3','СНЕЖ':'store_snezh','ГС1':'store_gs1','К80':'store_k80','ЗАО':'store_zao','ПЗ2':'store_pz2','КИР2':'store_kir2','РОС':'store_ros','ПЗ1':'store_pz1','МОН':'store_mon','МИРА':'store_mira','П.ЗОР':'store_pzor','УМБА':'store_umba','МАК':'store_mak','С3':'store_s3','НИК':'store_nik','Н95':'store_n95'}
profiles=DATA['store_profiles']; margin=DATA['network_dashboard']['net_margin']; ranks={x['store']:i+1 for i,x in enumerate(sorted(profiles,key=lambda v:v['net_profit'],reverse=True))}
def m(v): return f'{v/1e6:.2f}'.replace('.',',')
for page,p in enumerate(profiles,start=4):
  sid=ids[p['store']]
  if sid in {'store_port','store_a2','store_kir1'}: continue
  c='cinnabar' if p['net_profit']<0 else 'spruce'; sign='+' if p['net_margin']>=margin else ''
  xml=f'''<slide id="{sid}"><background color="paper"/><shape id="top" type="line" x="40" y="64" width="1200" height="0" stroke="spruce" stroke-width="2"/><text id="title" x="40" y="104" width="1100" height="42" font="heading" size="33" color="ink">{p['store']} — отдельный сравнительный профиль</text><text id="sub" x="40" y="156" width="1000" height="24" font="body" size="17" color="muted">Ранг по чистой прибыли: {ranks[p['store']]} из 32 · январь–август 2026</text><table id="pnl" x="40" y="205" width="1200" height="82" columns="3,3,3,3" rows="34,48" font="body" size="16" color="ink" padding="8 10" header-fill="mist" border-h="1 solid grid" border-v="1 solid grid"><tr><td>Выручка</td><td>Расходы</td><td>Чистая прибыль</td><td>Чистая маржа</td></tr><tr><td><strong>{m(p['revenue'])} млн</strong></td><td>{m(p['expenses'])} млн</td><td><strong color="{c}">{m(p['net_profit'])} млн</strong></td><td><strong color="{c}">{p['net_margin']*100:.1f}%</strong></td></tr></table><chart id="margin" type="column" x="40" y="350" width="555" height="205" font="caption" categories="{p['store']},Сеть" color="{c},#1A1A1A" legend="none" y-format="percent" y-min="-0.1" y-max="0.12" gridlines="h" gridline-color="grid" data-labels="true"><series values="{p['net_margin']:.4f},{margin:.4f}" label-expr="{{value:.1%}}"/></chart><table id="audit" x="635" y="350" width="605" height="205" columns="4,6" rows="41,41,41,41,41" font="body" size="15" color="ink" padding="7 10" header-fill="mist" border-h="1 solid grid" border-v="1 solid grid"><tr><td>Сеть</td><td><strong color="{c}">{sign}{(p['net_margin']-margin)*100:.1f} п.п. чистой маржи</strong></td></tr><tr><td>Лучший / худший</td><td>{p['best_month']} {m(p['best_month_profit'])} млн / {p['worst_month']} {m(p['worst_month_profit'])} млн</td></tr><tr><td>Драйвер</td><td>{p['primary_cost_driver']}: {m(p['primary_cost_driver_amount'])} млн</td></tr><tr><td>Резерв к медиане</td><td>{p['excess_cost_driver']}: {m(p['excess_cost_amount'])} млн</td></tr><tr><td>Товарный остаток</td><td>Эффект {m(p['inventory_net_effect'])} млн; перемещения {m(p['movement'])}; уценка {m(p['discount'])}</td></tr></table><text id="conclusion" x="40" y="585" width="1160" height="30" font="body" size="17" color="ink">{p['narrative']}</text><shape id="bottom" type="line" x="40" y="652" width="1200" height="0" stroke="grid" stroke-width="1"/><text id="source" x="40" y="672" width="400" height="18" font="caption" size="12" color="muted">ИСТОЧНИК: 2026.xlsx / ВКЛЮЧЕННАЯ БАЗА</text><text id="page" x="1190" y="672" width="50" height="18" font="caption" size="12" color="spruce" align="right">{page:02d}</text></slide>'''
  (OUT/f'{sid}.xml').write_text(xml,encoding='utf-8')
print('generated',len(profiles)-3,'profiles')
