import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent, type ReactNode } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Maximize2 } from "lucide-react";
import { useAudit } from "@/contexts/AuditContext";
import { chartPalette } from "@/lib/chartPalette";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";

export const formatK = (value:number,digits?:number) => { const absolute=Math.abs(value); if(absolute<.01)return "0 ₽"; if(absolute>=1000)return `${(value/1000).toLocaleString("ru-RU",{minimumFractionDigits:1,maximumFractionDigits:1})} млн ₽`; const precision=digits??(absolute<100?1:0); return `${value.toLocaleString("ru-RU",{minimumFractionDigits:precision,maximumFractionDigits:precision})} тыс. ₽`; };
export const formatM = (value:number,digits=1) => `${value.toLocaleString("ru-RU",{minimumFractionDigits:digits,maximumFractionDigits:digits})} млн ₽`;
export const formatPct = (value:number,digits=1) => `${value.toFixed(digits)}%`;

export type MetricChartTooltipMode="amount"|"million"|"percent"|"number";
export type MetricChartView="line"|"bar"|"overlay";
type MetricLine={key:string;name:string;color:string};
const iosPalette=["#5E5CE6","#00A3A3","#34C759","#FF9F0A","#FF375F","#64D2FF"];
const chartTick=(value:number,mode:MetricChartTooltipMode)=>mode==="percent"?`${value.toFixed(1)}%`:mode==="million"?`${value.toLocaleString("ru-RU",{maximumFractionDigits:1})} млн`:mode==="number"?value.toLocaleString("ru-RU",{maximumFractionDigits:1}):formatK(value).replace(" ₽","");

export const sortTooltipPayload=<T extends {value:number}>(payload:T[])=>[...payload].sort((a,b)=>b.value-a.value);
export const nonZeroLines=(data:readonly Record<string,unknown>[],lines:MetricLine[])=>lines.filter(line=>data.some(row=>{const value=row[line.key];return typeof value==="number"?value!==0:Number(value??0)!==0;}));
export const resolveMetricChartView=(pointCount:number,requested:MetricChartView):MetricChartView=>pointCount<=1?"bar":requested;
export const resolveMetricChartLayout=(pointCount:number,seriesCount:number)=>pointCount<=1&&seriesCount>1?"single-period-comparison":pointCount<=1?"single-value":"timeline";
export const resolveOverlayBarGeometry=(x:number,width:number,index:number,seriesCount:number)=>({x:x-index*width,width:width*seriesCount});
export const normalizeOverlayBarRect=(y:number,height:number)=>height>=0?{y,height}:{y:y+height,height:-height};
export const zeroAwareTicks=(values:readonly number[])=>{const finite=values.filter(Number.isFinite);const minimum=Math.min(0,...(finite.length?finite:[0]));const maximum=Math.max(0,...(finite.length?finite:[0]));if(minimum===maximum)return[0];if(minimum>=0)return[0,maximum/4,maximum/2,maximum*.75,maximum];if(maximum<=0)return[minimum,minimum*.75,minimum/2,minimum/4,0];return[minimum,minimum/2,0,maximum/2,maximum];};
export const clampChartZoom=(value:number)=>Math.min(3,Math.max(1,value));
export const chartPanSpeedForZoom=(zoom:number)=>2.35/Math.pow(clampChartZoom(zoom),1.75);
export type ChartPanAxis="x"|"y"|null;
export const resolveChartPanAxis=(deltaX:number,deltaY:number,threshold=4):ChartPanAxis=>Math.hypot(deltaX,deltaY)<threshold?null:Math.abs(deltaX)>=Math.abs(deltaY)?"x":"y";
export type ChartViewport={zoom:number;pan:{x:number;y:number}};
const clampUnit=(value:number)=>Math.min(2.4,Math.max(-2.4,value));
export const windowChartRows=<T,>(data:readonly T[],viewport?:ChartViewport,axis:"x"|"y"="x")=>{if(!viewport||viewport.zoom<=1||data.length<=1)return [...data];const size=Math.max(1,Math.floor(data.length/viewport.zoom));const maxStart=data.length-size;const start=Math.round(Math.min(1,Math.max(0,(clampUnit(viewport.pan[axis])+1)/2))*maxStart);return data.slice(start,start+size);};
export const panChartRows=<T,>(data:readonly T[],viewport?:ChartViewport,axis:"x"|"y"="x")=>windowChartRows(data,viewport,axis);
export const viewportChartDomain=(values:readonly number[],viewport?:ChartViewport,axis:"x"|"y"="y",includeZero=true)=>{const finite=values.filter(Number.isFinite);let minimum=Math.min(...(finite.length?finite:[0]),...(includeZero?[0]:[]));let maximum=Math.max(...(finite.length?finite:[0]),...(includeZero?[0]:[]));if(minimum===maximum){minimum-=1;maximum+=1;}const zoom=viewport?.zoom??1;const fullSpan=maximum-minimum;const span=fullSpan/zoom;const allowance=(fullSpan-span)/2+fullSpan*.75;const pan=axis==="x"?viewport?.pan.x??0:viewport?.pan.y??0;const renderPan=pan;const center=(minimum+maximum)/2+renderPan*allowance;return [center-span/2,center+span/2];};

export function TinyTooltip({active,payload,label,mode="amount"}:{active?:boolean;payload?:Array<{name:string;value:number;color:string}>;label?:string;mode?:MetricChartTooltipMode}){if(!active||!payload?.length)return null;return <div className="tiny-tooltip"><b>{label}</b>{sortTooltipPayload(payload).map(item=><span key={item.name}><i style={{background:item.color}}/>{item.name}: <strong>{typeof item.value==="number"?chartTick(item.value,mode):item.value}</strong></span>)}</div>;}

function ChartViewControls({view,onChange}:{view:MetricChartView;onChange:(view:MetricChartView)=>void}){return <div className="chart-view-control" aria-label="Вид графика"><button type="button" className={view==="line"?"chart-view-button active":"chart-view-button"} aria-pressed={view==="line"} onClick={()=>onChange("line")}>Волна</button><button type="button" className={view==="bar"?"chart-view-button active":"chart-view-button"} aria-pressed={view==="bar"} onClick={()=>onChange("bar")}>Столбцы</button><button type="button" className={view==="overlay"?"chart-view-button active":"chart-view-button"} aria-pressed={view==="overlay"} onClick={()=>onChange("overlay")}>Наложение</button></div>;}

function useSmallChartViewport(){const [small,setSmall]=useState(false);useEffect(()=>{const media=window.matchMedia("(max-width: 560px)");const update=()=>setSmall(media.matches);update();media.addEventListener("change",update);return()=>media.removeEventListener("change",update);},[]);return small;}

export function ChartPanZoomSurface({children,compact=false}:{children:ReactNode|((viewport:ChartViewport)=>ReactNode);compact?:boolean}){
  const [zoom,setZoom]=useState(1);const [pan,setPan]=useState({x:0,y:0});const [dragging,setDragging]=useState(false);const surfaceRef=useRef<HTMLDivElement>(null);const pointers=useRef(new Map<number,{x:number;y:number}>());const zoomRef=useRef(1);const panFrame=useRef<number|undefined>(undefined);const pendingPan=useRef({x:0,y:0});const gesture=useRef({startZoom:1,startDistance:0,startPoint:undefined as {x:number;y:number}|undefined,lastPoint:undefined as {x:number;y:number}|undefined,panning:false,axis:null as ChartPanAxis});
  const reset=()=>{zoomRef.current=1;setZoom(1);setPan({x:0,y:0});};const limit=(value:{x:number;y:number})=>({x:clampUnit(value.x),y:clampUnit(value.y)});const point=(event:ReactPointerEvent<HTMLDivElement>)=>({x:event.clientX,y:event.clientY});const distance=(left:{x:number;y:number},right:{x:number;y:number})=>Math.hypot(left.x-right.x,left.y-right.y);const commitZoom=(propose:(current:number)=>number)=>setZoom(current=>{const next=clampChartZoom(propose(current));zoomRef.current=next;setPan(value=>limit(value));return next;});const queuePan=(delta:{x:number;y:number})=>{pendingPan.current={x:pendingPan.current.x+delta.x,y:pendingPan.current.y+delta.y};if(panFrame.current!==undefined)return;panFrame.current=window.requestAnimationFrame(()=>{const next=pendingPan.current;pendingPan.current={x:0,y:0};panFrame.current=undefined;setPan(current=>limit({x:current.x+next.x,y:current.y+next.y}));});};
  const changeZoom=(deltaY:number)=>commitZoom(current=>current+(deltaY<0?.16:-.16));
  useEffect(()=>{const surface=surfaceRef.current;if(!surface)return;const wheel=(event:WheelEvent)=>{if(event.cancelable)event.preventDefault();event.stopPropagation();changeZoom(event.deltaY);};surface.addEventListener("wheel",wheel,{passive:false});return()=>surface.removeEventListener("wheel",wheel);},[]);
  const move=(event:ReactPointerEvent<HTMLDivElement>)=>{if(event.pointerType==="touch"||!pointers.current.has(event.pointerId))return;const next=point(event);pointers.current.set(event.pointerId,next);const active=Array.from(pointers.current.values());if(active.length>1){gesture.current.panning=true;event.preventDefault();event.stopPropagation();const nextZoom=clampChartZoom(gesture.current.startZoom*(distance(active[0],active[1])/Math.max(gesture.current.startDistance,1)));commitZoom(()=>nextZoom);return;}const previous=gesture.current.lastPoint;if(!previous)return;const start=gesture.current.startPoint??previous;let deltaX=next.x-previous.x,deltaY=next.y-previous.y;if(!gesture.current.axis){gesture.current.axis=resolveChartPanAxis(next.x-start.x,next.y-start.y);if(!gesture.current.axis){gesture.current.lastPoint=next;return;}deltaX=next.x-start.x;deltaY=next.y-start.y;}gesture.current.lastPoint=next;gesture.current.panning=true;event.preventDefault();event.stopPropagation();setDragging(true);const bounds=event.currentTarget.getBoundingClientRect();const speed=chartPanSpeedForZoom(zoomRef.current);queuePan({x:gesture.current.axis==="x"?-deltaX*speed/Math.max(bounds.width,1):0,y:gesture.current.axis==="y"?deltaY*speed/Math.max(bounds.height,1):0});};
  const clearGesture=()=>{pointers.current.clear();gesture.current.startPoint=undefined;gesture.current.lastPoint=undefined;gesture.current.startDistance=0;gesture.current.panning=false;gesture.current.axis=null;setDragging(false);};
  const finish=(event:ReactPointerEvent<HTMLDivElement>)=>{if(event.pointerType==="touch")return;clearGesture();if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);};
  const cancel=(event:ReactPointerEvent<HTMLDivElement>)=>{if(event.pointerType!=="touch")clearGesture();};
  const down=(event:ReactPointerEvent<HTMLDivElement>)=>{if(event.pointerType==="touch"||(event.target as Element).closest("button,[data-chart-point='true']"))return;event.preventDefault();const next=point(event);pointers.current.set(event.pointerId,next);event.currentTarget.setPointerCapture(event.pointerId);const active=Array.from(pointers.current.values());gesture.current.startPoint=next;gesture.current.lastPoint=next;gesture.current.panning=false;gesture.current.axis=null;gesture.current.startZoom=zoomRef.current;if(active.length>1)gesture.current.startDistance=distance(active[0],active[1]);};
  useEffect(()=>{const surface=surfaceRef.current;if(!surface)return;const isControl=(target:EventTarget|null)=>target instanceof Element&&Boolean(target.closest("button,[data-chart-point='true']"));const touches=(event:TouchEvent)=>Array.from(event.touches,touch=>({x:touch.clientX,y:touch.clientY}));const touchStart=(event:TouchEvent)=>{if(isControl(event.target)||!event.touches.length)return;event.preventDefault();event.stopPropagation();const active=touches(event);gesture.current.startPoint=active[0];gesture.current.lastPoint=active[0];gesture.current.panning=false;gesture.current.axis=null;gesture.current.startZoom=zoomRef.current;gesture.current.startDistance=active.length>1?distance(active[0],active[1]):0;};const touchMove=(event:TouchEvent)=>{const active=touches(event);if(!active.length)return;if(active.length>1){event.preventDefault();event.stopPropagation();gesture.current.panning=true;setDragging(true);const baseDistance=gesture.current.startDistance||distance(active[0],active[1]);const nextZoom=clampChartZoom(gesture.current.startZoom*(distance(active[0],active[1])/Math.max(baseDistance,1)));commitZoom(()=>nextZoom);return;}const next=active[0],previous=gesture.current.lastPoint;if(!previous)return;const start=gesture.current.startPoint??previous;let deltaX=next.x-previous.x,deltaY=next.y-previous.y;if(!gesture.current.axis){gesture.current.axis=resolveChartPanAxis(next.x-start.x,next.y-start.y);if(!gesture.current.axis){gesture.current.lastPoint=next;return;}deltaX=next.x-start.x;deltaY=next.y-start.y;}gesture.current.lastPoint=next;event.preventDefault();event.stopPropagation();gesture.current.panning=true;setDragging(true);const bounds=surface.getBoundingClientRect();const speed=chartPanSpeedForZoom(zoomRef.current);queuePan({x:gesture.current.axis==="x"?-deltaX*speed/Math.max(bounds.width,1):0,y:gesture.current.axis==="y"?deltaY*speed/Math.max(bounds.height,1):0});};const touchEnd=()=>clearGesture();surface.addEventListener("touchstart",touchStart,{passive:false,capture:true});surface.addEventListener("touchmove",touchMove,{passive:false,capture:true});surface.addEventListener("touchend",touchEnd,{passive:true,capture:true});surface.addEventListener("touchcancel",touchEnd,{passive:true,capture:true});return()=>{surface.removeEventListener("touchstart",touchStart,true);surface.removeEventListener("touchmove",touchMove,true);surface.removeEventListener("touchend",touchEnd,true);surface.removeEventListener("touchcancel",touchEnd,true);};},[]);
  useEffect(()=>{const release=()=>clearGesture();window.addEventListener("pointerup",release,true);window.addEventListener("pointercancel",release,true);return()=>{if(panFrame.current!==undefined)window.cancelAnimationFrame(panFrame.current);window.removeEventListener("pointerup",release,true);window.removeEventListener("pointercancel",release,true);};},[]);
  const viewport={zoom,pan};return <div ref={surfaceRef} className={`${dragging?"chart-panzoom dragging":"chart-panzoom"}${compact?" chart-panzoom-compact":""}`} tabIndex={0} aria-label={compact?"Интерактивный график":"Интерактивный увеличенный график"} onPointerDownCapture={down} onPointerMoveCapture={move} onPointerUpCapture={finish} onPointerCancelCapture={cancel} onLostPointerCapture={cancel} onKeyDown={event=>{if(event.key==="0"){event.preventDefault();reset();}if(event.key==="+"||event.key==="="){event.preventDefault();commitZoom(current=>current+.16);}if(event.key==="-"){event.preventDefault();commitZoom(current=>current-.16);}}}>{!compact&&<div className="chart-panzoom-actions" aria-label="Масштаб графика"><button type="button" onClick={()=>commitZoom(current=>current-.25)} aria-label="Уменьшить масштаб">−</button><b aria-live="polite">{Math.round(zoom*100)}%</b><button type="button" onClick={()=>commitZoom(current=>current+.25)} aria-label="Увеличить масштаб">+</button><button type="button" onClick={reset}>Сброс</button></div>}<div className="chart-panzoom-stage">{typeof children==="function"?children(viewport):children}</div></div>;
}

type ChartExpandButtonProps={title:string;initialView?:MetricChartView;showViewControls?:boolean;children:ReactNode|((view:MetricChartView,viewport:ChartViewport)=>ReactNode)};
function ChartExpandButton({title,initialView="line",showViewControls=false,children}:ChartExpandButtonProps){
  const [open,setOpen]=useState(false); const [expandedView,setExpandedView]=useState<MetricChartView>(initialView);
  const handleOpenChange=(next:boolean)=>{if(next)setExpandedView(initialView);setOpen(next);};
  const keepChartSurfaceInside=(event:{preventDefault:()=>void})=>event.preventDefault();
  return <Dialog open={open} onOpenChange={handleOpenChange}><DialogTrigger asChild><button type="button" className="chart-expand-button" aria-label={`Увеличить график: ${title}`}><Maximize2 size={14}/><span>Увеличить</span></button></DialogTrigger><DialogContent className="chart-expand-dialog" onPointerDownOutside={keepChartSurfaceInside} onInteractOutside={keepChartSurfaceInside}><DialogHeader><DialogTitle>{title}</DialogTitle></DialogHeader>{showViewControls&&<div className="chart-expand-view-control"><ChartViewControls view={expandedView} onChange={setExpandedView}/></div>}<ChartPanZoomSurface>{viewport=><div className="chart-expand-canvas">{typeof children==="function"?children(expandedView,viewport):children}</div>}</ChartPanZoomSurface></DialogContent></Dialog>;
}

type MetricLineChartProps={data:readonly Record<string,unknown>[];lines:MetricLine[];percent?:boolean;unit?:"k"|"m";displayMode?:MetricChartTooltipMode;chartTitle?:string;expanded?:boolean;initialView?:MetricChartView;showViewControls?:boolean;viewport?:ChartViewport};
export function MetricLineChart({data,lines,percent=false,unit="k",displayMode,chartTitle="Детальный график",expanded=false,initialView="line",showViewControls=true,viewport}:MetricLineChartProps){
  if(!expanded&&!viewport)return <ChartPanZoomSurface compact>{compactViewport=><MetricLineChart data={data} lines={lines} percent={percent} unit={unit} displayMode={displayMode} chartTitle={chartTitle} initialView={initialView} showViewControls={showViewControls} viewport={compactViewport}/>}</ChartPanZoomSurface>;
  const [hidden,setHidden]=useState<string[]>([]);
  const [requestedView,setRequestedView]=useState<MetricChartView>(initialView);
  const {theme}=useAudit();
  const palette=chartPalette(theme);
  const mode:MetricChartTooltipMode=displayMode??(percent?"percent":unit==="m"?"million":"amount");
  const activeLines=nonZeroLines(data,lines);
  const visibleLines=activeLines.filter(line=>!hidden.includes(line.key));
  const chartView=resolveMetricChartView(data.length,requestedView);
  const chartLayout=resolveMetricChartLayout(data.length,visibleLines.length);
  const compactViewport=useSmallChartViewport();
  const compactChart=compactViewport&&!expanded;
  const timelineMargin=compactChart?{top:12,right:8,left:0,bottom:4}:{top:18,right:32,left:20,bottom:10};
  const timelineAxisWidth=compactChart?55:78;
  const singleMargin=compactChart?{top:12,right:8,left:0,bottom:4}:{top:16,right:32,left:12,bottom:10};
  const singleAxisWidth=compactChart?94:112;
  const colorFor=(line:MetricLine,index:number)=>theme==="light"?iosPalette[index%iosPalette.length]:line.color;
  const toggle=(key:string)=>setHidden(current=>current.includes(key)?current.filter(value=>value!==key):[...current,key]);
  const chartData=panChartRows(data,viewport);
  const fullPlottedValues=data.flatMap(row=>visibleLines.map(line=>Number(row[line.key]??0))).filter(Number.isFinite);
  const yDomain=viewportChartDomain(fullPlottedValues,viewport,"y",(viewport?.zoom??1)<=1); const ticks=zeroAwareTicks(yDomain);
  const singleRows=visibleLines.map((line,index)=>({label:line.name,value:Number(data[0]?.[line.key]??0),color:colorFor(line,index)}));
  const singleDomain=viewportChartDomain(singleRows.map(row=>row.value),viewport); const singleTicks=zeroAwareTicks(singleDomain);
  const cursor={fill:theme==="light"?"rgba(10,132,255,.08)":"rgba(255,118,95,.08)"};
  const peak=(line:MetricLine)=>Math.max(...data.map(row=>Math.abs(Number(row[line.key]??0))));
  const overlayLines=[...visibleLines].sort((left,right)=>peak(right)-peak(left));
  const chartHeight=expanded?Math.max(520,chartLayout==="single-period-comparison"?singleRows.length*52+72:560):chartLayout==="single-period-comparison"?Math.max(300,singleRows.length*44+48):compactChart?322:306;
  const chartRenderKey=`${chartView}-${visibleLines.map(line=>line.key).join("-")}`;
  if(!activeLines.length)return <div className="metric-chart"><p className="chart-empty">За выбранный период ненулевых значений нет.</p></div>;
  return <div className={expanded?"metric-chart metric-chart-expanded":"metric-chart"}>
    <div className="chart-toolbar"><div className="chart-series-control" aria-label="Управление рядами графика">{activeLines.map((line,index)=>{const muted=hidden.includes(line.key);return <button type="button" aria-pressed={!muted} key={line.key} onClick={()=>toggle(line.key)} className={muted?"series-toggle muted":"series-toggle"}><i style={{background:colorFor(line,index)}}/>{line.name}</button>;})}</div><div className="chart-toolbar-actions">{showViewControls&&data.length>1&&<ChartViewControls view={chartView} onChange={setRequestedView}/>} {!expanded&&<ChartExpandButton title={chartTitle} initialView={chartView} showViewControls={data.length>1}>{(expandedView,expandedViewport)=><MetricLineChart key={expandedView} data={data} lines={lines} percent={percent} unit={unit} displayMode={displayMode} chartTitle={chartTitle} initialView={expandedView} expanded showViewControls={false} viewport={expandedViewport}/>}</ChartExpandButton>}</div></div>
    <ResponsiveContainer key={chartRenderKey} width="100%" height={chartHeight}>
      {chartLayout==="single-period-comparison"?
        <BarChart data={singleRows} layout="vertical" margin={singleMargin} barCategoryGap={10}><CartesianGrid horizontal={false} stroke={palette.grid}/><XAxis type="number" domain={singleDomain} ticks={singleTicks} axisLine={false} tickLine={false} stroke={palette.axis} tick={{fill:palette.tick,fontSize:11}} tickFormatter={value=>chartTick(value,mode)}/><YAxis type="category" dataKey="label" width={singleAxisWidth} axisLine={false} tickLine={false} tick={{fill:palette.tick,fontSize:11}}/><ReferenceLine x={0} stroke={palette.axis} strokeOpacity={.78} strokeWidth={1.2}/><Tooltip cursor={false} wrapperStyle={{pointerEvents:"none",zIndex:20}} content={<TinyTooltip mode={mode}/>}/><Bar dataKey="value" name="Значение" radius={[0,6,6,0]} maxBarSize={28} isAnimationActive={false}>{singleRows.map(row=><Cell key={row.label} fill={row.color}/>)}</Bar></BarChart>
      :chartView==="bar"?
        <BarChart data={chartData} margin={timelineMargin} barCategoryGap={chartData.length===1?"34%":"18%"}><CartesianGrid vertical={false} stroke={palette.grid}/><XAxis dataKey="month" axisLine={false} tickLine={false} stroke={palette.axis}/><YAxis domain={yDomain} ticks={ticks} axisLine={false} tickLine={false} width={timelineAxisWidth} stroke={palette.axis} tick={{fill:palette.tick,fontSize:11}} tickFormatter={value=>chartTick(value,mode)}/><ReferenceLine y={0} stroke={palette.axis} strokeOpacity={.78} strokeWidth={1.2}/><Tooltip cursor={cursor} wrapperStyle={{pointerEvents:"none",zIndex:20}} content={<TinyTooltip mode={mode}/>}/>{visibleLines.map((line,index)=><Bar key={line.key} dataKey={line.key} name={line.name} fill={colorFor(line,index)} radius={[6,6,0,0]} maxBarSize={chartData.length===1?86:undefined} isAnimationActive={false}/>)}</BarChart>
      :chartView==="overlay"?
        <BarChart data={chartData} margin={timelineMargin} barCategoryGap="30%" barGap={0}><CartesianGrid vertical={false} stroke={palette.grid}/><XAxis dataKey="month" axisLine={false} tickLine={false} stroke={palette.axis}/><YAxis domain={yDomain} ticks={ticks} axisLine={false} tickLine={false} width={timelineAxisWidth} stroke={palette.axis} tick={{fill:palette.tick,fontSize:11}} tickFormatter={value=>chartTick(value,mode)}/><ReferenceLine y={0} stroke={palette.axis} strokeOpacity={.78} strokeWidth={1.2}/><Tooltip cursor={cursor} wrapperStyle={{pointerEvents:"none",zIndex:20}} content={<TinyTooltip mode={mode}/>}/>{overlayLines.map((line,index)=>{const color=colorFor(line,visibleLines.indexOf(line));return <Bar key={line.key} dataKey={line.key} name={line.name} fill={color} isAnimationActive={false} shape={(props:{x?:number;y?:number;width?:number;height?:number})=>{const geometry=resolveOverlayBarGeometry(Number(props.x??0),Number(props.width??0),index,overlayLines.length);const bar=normalizeOverlayBarRect(Number(props.y??0),Number(props.height??0));return <rect x={geometry.x} y={bar.y} width={geometry.width} height={bar.height} fill={color} rx={6} ry={6}/>;}}/>;})}</BarChart>
      :<AreaChart data={chartData} margin={timelineMargin}><CartesianGrid vertical={false} stroke={palette.grid}/><XAxis dataKey="month" axisLine={false} tickLine={false} stroke={palette.axis}/><YAxis domain={yDomain} ticks={ticks} axisLine={false} tickLine={false} width={timelineAxisWidth} stroke={palette.axis} tick={{fill:palette.tick,fontSize:11}} tickFormatter={value=>chartTick(value,mode)}/><ReferenceLine y={0} stroke={palette.axis} strokeOpacity={.78} strokeWidth={1.2}/><Tooltip cursor={cursor} wrapperStyle={{pointerEvents:"none",zIndex:20}} content={<TinyTooltip mode={mode}/>}/>{visibleLines.map((line,index)=>{const color=colorFor(line,index);return <Area key={line.key} type="monotone" dataKey={line.key} name={line.name} stroke={color} strokeWidth={2.7} fill={color} fillOpacity={theme==="light"?.14:.18} dot={{r:3.5,stroke:"none",strokeWidth:0,fill:color}} activeDot={{r:6,stroke:"none",strokeWidth:0,fill:color}} isAnimationActive={false}/>})}</AreaChart>}
    </ResponsiveContainer>
  </div>;
}

type BenchmarkBarsProps={data:{store:string;value:number;selected:boolean}[];median:number;mode?:MetricChartTooltipMode;selectedLabel:string;chartTitle?:string;expanded?:boolean;viewport?:ChartViewport};
export function BenchmarkBars({data,median,mode="percent",selectedLabel,chartTitle="Сравнение магазинов",expanded=false,viewport}:BenchmarkBarsProps){
  if(!expanded&&!viewport)return <ChartPanZoomSurface compact>{compactViewport=><BenchmarkBars data={data} median={median} mode={mode} selectedLabel={selectedLabel} chartTitle={chartTitle} viewport={compactViewport}/>}</ChartPanZoomSurface>;
  const {theme}=useAudit();const palette=chartPalette(theme);const medianColor=expanded&&theme==="dark"?"#b694ff":palette.median;const chartData=panChartRows(data,viewport,"y");const baseHeight=Math.max(600,chartData.length*27+70);const height=expanded?Math.max(680,baseHeight):baseHeight;const domain=viewportChartDomain(data.map(row=>row.value),viewport,"x",(viewport?.zoom??1)<=1);const ticks=zeroAwareTicks(domain);
  return <div className={expanded?"benchmark-chart benchmark-chart-expanded":"benchmark-chart"}><div className="chart-toolbar"><div className="median-badge"><i style={{background:medianColor}}/> Медиана сети: <b>{chartTick(median,mode)}</b> · {selectedLabel} — акцентный маркер</div>{!expanded&&<ChartExpandButton title={chartTitle}>{(_view,expandedViewport)=><BenchmarkBars data={data} median={median} mode={mode} selectedLabel={selectedLabel} chartTitle={chartTitle} expanded viewport={expandedViewport}/>}</ChartExpandButton>}</div><ResponsiveContainer width="100%" height={height}><BarChart data={chartData} layout="vertical" margin={{top:16,right:30,left:18,bottom:14}} barCategoryGap={6}><CartesianGrid horizontal={false} stroke={palette.grid}/><XAxis type="number" domain={domain} ticks={ticks} tickFormatter={value=>chartTick(value,mode)} axisLine={false} tickLine={false} stroke={palette.axis} tick={{fill:palette.tick,fontSize:11}}/><YAxis type="category" dataKey="store" width={128} tick={{fontSize:11,fill:palette.tick}} axisLine={false} tickLine={false}/><Tooltip cursor={false} wrapperStyle={{pointerEvents:"none",zIndex:20}} content={<TinyTooltip mode={mode}/>}/><ReferenceLine x={0} stroke={palette.axis} strokeOpacity={.78} strokeWidth={1.2}/><ReferenceLine x={median} stroke={medianColor} strokeWidth={2} strokeDasharray="5 5"/><Bar dataKey="value" name="Значение" radius={[0,6,6,0]} activeBar={false} isAnimationActive animationDuration={650}>{chartData.map(row=><Cell key={row.store} fill={row.selected?palette.selected:palette.bar}/>)}</Bar></BarChart></ResponsiveContainer></div>;
}
